/* Open-sector expeditions: canvas presentation, touch controls and atomic local saves. */
window.MKTYExpedition = (() => {
  'use strict';
  const R=window.ExpeditionRules, KEY='mkty_expeditions_v1', $=id=>document.getElementById(id);
  const tr=(ru,en)=>window.MKTYI18n?window.MKTYI18n.tr(ru,en):(localStorage.getItem('mkty_lang')==='ru'?ru:en);
  let story=null,freeState=null;
  let state;try{state=R.restore(JSON.parse(localStorage.getItem(KEY)));}catch{state=R.restore(null);}
  let selected='rescue',tier=1,paused=true,frame=0,last=0,saveAt=0,hudAt=0,mode='hangar',storageOK=true;
  const input={x:0,y:0,boost:false,action:false},keys=new Set();let stick=null;
  const root=document.createElement('section');root.id='expeditions';root.className='screen exp-screen';root.setAttribute('translate','no');root.dir='ltr';
  root.innerHTML=`
    <div id="expHangar" class="exp-hangar">
      <header class="exp-hangar-head"><div><span class="exp-kicker" id="expHangarKicker">MOONKATTY / DEEP SPACE</span><h1 id="expTitle"></h1></div><button id="expHome" class="exp-quiet"></button></header>
      <div class="exp-hangar-art"><div class="exp-orbit-lines"></div><img src="moonkatty-life4-ship.webp" alt="MOONKATTY 01"><div><span id="expVessel"></span><strong>MK–01</strong><small id="expRank"></small></div></div>
      <div class="exp-hangar-body"><p id="expIntro" class="exp-intro"></p><div id="expProfile" class="exp-profile"></div>
        <div id="expResumeCard" class="exp-resume" hidden><div><strong id="expSaved"></strong><small id="expSavedInfo"></small></div><button id="expResume" class="exp-primary"></button><button id="expAbandon" class="exp-quiet"></button></div>
        <div id="expDispatch"><div class="exp-section-label"><span id="expContractsTitle"></span><span>01—03</span></div><div id="expContracts" class="exp-contracts"></div>
          <div class="exp-section-label"><span id="expSectorTitle"></span><span id="expSectorHint"></span></div><div id="expTiers" class="exp-tiers"></div>
          <button id="expLaunch" class="exp-primary exp-launch"></button>
        </div>
        <div class="exp-section-label"><span id="expUpgradesTitle"></span><span id="expParts"></span></div><div id="expUpgrades" class="exp-upgrades"></div>
        <p id="expLocalNote" class="exp-footnote"></p><p id="expStorage" class="exp-footnote" role="status"></p>
      </div>
    </div>
    <div id="expFlight" class="exp-flight" hidden>
      <header class="exp-flight-head"><div><small id="expFlightSector"></small><strong id="expFlightTitle"></strong></div><button id="expPause" class="exp-quiet"></button></header>
      <div class="exp-vitals"><label><span id="expHullLabel"></span><b id="expHull"></b><i><em id="expHullBar"></em></i></label><label><span id="expEnergyLabel"></span><b id="expEnergy"></b><i><em id="expEnergyBar"></em></i></label><div><span id="expCargoLabel"></span><b id="expCargo"></b></div></div>
      <div id="expViewport" class="exp-viewport"><canvas id="expCanvas" role="img"></canvas><div class="exp-scene-grain"></div>
        <div class="exp-objective"><span id="expObjective"></span><strong id="expBearing"></strong></div>
        <button id="expMap" class="exp-map-button"><canvas id="expRadar" width="112" height="112" aria-hidden="true"></canvas><span id="expMapLabel"></span></button>
        <div id="expNotice" class="exp-notice" role="status" aria-live="polite"></div>
        <div id="expWork" class="exp-work" hidden><span id="expWorkLabel"></span><i><b id="expWorkBar"></b></i></div>
      </div>
      <div class="exp-controls"><div id="expJoystick" class="exp-joystick" role="group"><span></span><i id="expStick"></i></div>
        <div class="exp-actions"><button id="expBoost" class="exp-control"></button><button id="expEMP" class="exp-control"></button><button id="expScan" class="exp-control"></button><button id="expAction" class="exp-primary"></button></div>
      </div>
      <div id="expKeyboard" class="exp-keyboard"></div>
    </div>
    <dialog id="expDialog" class="exp-dialog"><div id="expDialogBody"></div></dialog>`;
  $('app').append(root);
  const ctx=$('expCanvas').getContext('2d'),radar=$('expRadar').getContext('2d');let width=390,height=480,dpr=1,zoom=.7;
  const images={};function loadImages(){if(images.ship)return;for(const [k,url] of Object.entries({ship:'moonkatty-life4-ship.webp',rock:'art/life7-asteroid-v2.webp',space:'art/life7-void.webp'})){const i=new Image();i.onload=()=>{if(active()&&mode==='flight')draw();};i.src=url;images[k]=i;}}
  const stars=Array.from({length:230},(_,i)=>{const rng=R.random(i*6719+492);return{x:rng()*R.SIZE,y:rng()*R.SIZE,r:.5+rng()*1.3,alpha:.18+rng()*.6};});
  const active=()=>root.classList.contains('active');
  const title=type=>({rescue:tr('Никого не оставить','Leave no one behind'),salvage:tr('Чёрный ящик','Black box'),survey:tr('За краем карты','Beyond the chart')})[type];
  const sector=n=>[tr('Тихая орбита','Quiet orbit'),tr('Пояс обломков','Debris belt'),tr('Тёмный сектор','Dark sector')][n-1];
  const kindName=k=>({base:tr('База «Ковчег»','Ark station'),relay:tr('Ретранслятор','Relay'),pod:tr('Спасательная капсула','Escape pod'),wreck:tr('Самописец «Эхо»','Echo black box'),cache:tr('Контейнер деталей','Parts container'),service:tr('Ремонтный дрон','Repair tender')})[k];
  const texts={launch:()=>tr('Сигналы впереди. Проверьте карту и выберите маршрут.','Signals ahead. Check the map and choose your route.'),resumed:()=>tr('Управление восстановлено. Вылет продолжается.','Flight controls restored. Expedition resumed.'),damage:()=>tr('Повреждение корпуса. Меняйте курс!','Hull impact. Change course!'),radiation:()=>tr('Ионное облако повреждает корпус. Покиньте зону.','Ion cloud is damaging the hull. Leave the zone.'),incomplete:()=>tr('Задача ещё не выполнена. Можно вернуться с частью груза.','Contract unfinished. You can return with part of the cargo.'),locked:()=>tr('Самописец обесточен. Активируйте два ретранслятора.','Black box has no power. Activate two relays.'),rescued:()=>tr('Экипаж на борту. Патрули засекли сигнал капсулы!','Crew aboard. Patrols detected the pod signal!'),salvaged:()=>tr('Детали в грузовом отсеке.','Parts secured in the cargo bay.'),relay:()=>tr('Ретранслятор активен. Ближайшие сигналы раскрыты.','Relay online. Nearby signals revealed.'),blackbox:()=>tr('Самописец извлечён. Сработала тревога! Курс на базу.','Black box recovered. Alarm triggered! Return to base.'),repaired:()=>tr('Корпус восстановлен на 45. Батарея заряжена.','Hull restored by 45. Battery recharged.'),scanned:()=>tr('Импульс сканера раскрывает ближайшие объекты.','Scanner pulse reveals nearby objects.'),emp:()=>tr('Импульс: патрули рядом отключены на 6 секунд.','Pulse: nearby patrols disabled for 6 seconds.')};
  function save(){if(story){story.save(structuredClone(state));return;}try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('expStorage').textContent=storageOK?'':tr('Не удалось сохранить вылет: хранилище устройства недоступно.','Flight could not be saved: device storage is unavailable.');}
  function release(){keys.clear();input.x=input.y=0;input.boost=input.action=false;stick=null;$('expStick').style.transform='translate(0,0)';root.querySelectorAll('.is-held').forEach(e=>e.classList.remove('is-held'));}
  function stop(){paused=true;release();cancelAnimationFrame(frame);frame=0;last=0;save();}
  function onScreen(id){if(id!=='expeditions'){if(frame||!paused)stop();if($('expDialog').open)$('expDialog').close();if(story)closeStory();}else $('expStorage').textContent='';}
  function open(){loadImages();if(story)closeStory();show('expeditions');hangar();}
  function hangar(){if(story){const task=story;closeStory();task.exit();return;}stop();mode='hangar';$('expFlight').hidden=true;$('expHangar').hidden=false;if($('expDialog').open)$('expDialog').close();renderHangar();}
  function renderHangar(){
    const p=state.profile,run=state.run?.phase==='flight'?state.run:null;root.dataset.mode='hangar';
    $('expHangarKicker').textContent='MOONKATTY / '+tr('ГЛУБОКИЙ КОСМОС','DEEP SPACE');$('expTitle').textContent=tr('ЭКСПЕДИЦИИ','EXPEDITIONS');$('expHome').textContent=tr('← Главная','← Home');$('expVessel').textContent=tr('ИССЛЕДОВАТЕЛЬСКИЙ КОРАБЛЬ','EXPLORATION VESSEL');$('expRank').textContent=tr('ПИЛОТ / ВЫЛЕТОВ: ','PILOT / FLIGHTS: ')+p.flights;
    $('expIntro').textContent=tr('Чужие сигналы. Живой экипаж. Один путь домой. Выбирайте маршрут, обходите патрули и решайте, стоит ли лишний груз риска.','Unknown signals. Lives on the line. One way home. Pick your route, evade patrols and decide how much cargo is worth the risk.');
    $('expProfile').innerHTML=`<div><b>${p.parts}</b><span>${tr('ДЕТАЛИ','PARTS')}</span></div><div><b>${p.wins}</b><span>${tr('УСПЕШНЫЕ ВЫЛЕТЫ','SUCCESSFUL FLIGHTS')}</span></div><div><b>${p.rescued}</b><span>${tr('СПАСЕНО','RESCUED')}</span></div>`;
    $('expResumeCard').hidden=!run;$('expDispatch').hidden=!!run;
    if(run){$('expSaved').textContent=tr('Вылет сохранён','Flight saved');$('expSavedInfo').textContent=title(run.type)+' · '+Math.ceil(run.ship.hull/R.maxHull(p)*100)+'% '+tr('корпуса','hull');$('expResume').textContent=tr('Продолжить','Resume');$('expAbandon').textContent=tr('Прервать вылет','Abandon flight');}
    $('expContractsTitle').textContent=tr('ВЫБЕРИТЕ КОНТРАКТ','SELECT A CONTRACT');$('expSectorTitle').textContent=tr('ГЛУБИНА СЕКТОРА','SECTOR DEPTH');$('expSectorHint').textContent=tr('Больше риска — больше деталей','More risk · more parts');
    const descriptions={rescue:tr('Найдите две капсулы и верните экипаж живым. В открытом космосе они не переживут потерю корабля.','Recover two escape pods and bring their crew home alive. They cannot survive the loss of your ship.'),salvage:tr('Подайте питание через два ретранслятора, вскройте брошенный корабль и доставьте самописец.','Power up two relays, recover a derelict ship’s black box and bring it back.'),survey:tr('Активируйте три удалённых ретранслятора. Маршрут проходит через территорию патрулей.','Activate three distant relays. Your route crosses patrol territory.')};
    $('expContracts').innerHTML=R.TYPES.map((t,i)=>`<button class="exp-contract ${selected===t?'selected':''}" data-exp-contract="${t}" aria-pressed="${selected===t}"><span class="exp-contract-number">0${i+1}</span><div><strong>${title(t)}</strong><p>${descriptions[t]}</p><small>${[tr('ПОИСК / СПАСЕНИЕ','SEARCH / RESCUE'),tr('ВЗЛОМ / ИЗВЛЕЧЕНИЕ','POWER / RECOVERY'),tr('РАЗВЕДКА / НАВИГАЦИЯ','SURVEY / NAVIGATION')][i]}</small></div><b>↗</b></button>`).join('');
    $('expTiers').innerHTML=[1,2,3].map(n=>`<button data-exp-tier="${n}" class="${tier===n?'selected':''}" aria-pressed="${tier===n}" ${n>R.unlocked(p)?'disabled':''}><strong>0${n}</strong><span>${sector(n)}</span><small>${n>R.unlocked(p)?tr('Побед: ','Wins: ')+(n===2?1:3):tr('Патрулей: ','Patrols: ')+(n===1?1:n+1)}</small></button>`).join('');
    $('expLaunch').textContent=tr('НАЧАТЬ ВЫЛЕТ','LAUNCH EXPEDITION')+' ↗';$('expUpgradesTitle').textContent=tr('МАСТЕРСКАЯ','WORKSHOP');$('expParts').textContent=p.parts+' '+tr('ДЕТАЛЕЙ','PARTS');
    const upgradeInfo={hull:[tr('Усиление корпуса','Hull plating'),tr('+25 прочности за уровень','+25 hull per level')],engine:[tr('Маневровые двигатели','Maneuvering engines'),tr('+25 скорости за уровень','+25 speed per level')],scanner:[tr('Дальний сканер','Deep scanner'),tr('+180 к радиусу импульса','+180 scan range per level')]};
    $('expUpgrades').innerHTML=Object.entries(upgradeInfo).map(([k,[name,desc]])=>`<article><div><strong>${name}</strong><small>${desc}</small><span class="exp-upgrade-level">${[0,1,2].map(i=>`<i class="${p.upgrades[k]>i?'filled':''}"></i>`).join('')}</span></div><button data-exp-buy="${k}" ${run||!R.price(p,k)||p.parts<R.price(p,k)?'disabled':''}>${R.price(p,k)?R.price(p,k)+' '+tr('дет.','parts'):tr('МАКС.','MAX')}</button></article>`).join('');
    $('expLocalNote').textContent=tr('Детали нужны только для корабля. Прогресс сохраняется на этом устройстве. Улучшения устанавливаются между вылетами.','Parts upgrade your ship. Progress is saved on this device. Install upgrades between flights.');
  }
  function closeStory(){if(!story)return;stop();if($('expDialog').open)$('expDialog').close();story=null;state=freeState;freeState=null;mode='hangar';}
  function openStory(task,saved){loadImages();
    if(story)closeStory();stop();freeState=state;
    // Navigation must happen before installing the story session: leaving another screen may save it.
    show('expeditions');story=task;state=R.restore(saved);
    if(!state.run||state.run.seed!==task.seed||state.run.type!==task.contract||state.run.tier!==task.tier){const profile=R.profile();profile.upgrades.hull=task.chapter>=7?2:task.chapter>=4?1:0;profile.upgrades.scanner=task.chapter>=6?1:0;state={version:1,profile,run:R.create(task.seed,task.contract,task.tier,profile)};if(task.chapter<=2)state.run.ship.invulnerable=2;}
    state.trace=Array.isArray(saved?.trace)&&saved?.run?.seed===task.seed?structuredClone(saved.trace):[];
    localStorage.setItem('mkty_current_chapter',String(task.chapter));save();
    if(state.run.phase==='result'){mode='flight';root.dataset.mode='flight';$('expHangar').hidden=true;$('expFlight').hidden=false;resize();labels();hud();draw();result();}else flight(!!saved);
  }
  function storyResult(){const a=state.run.report;if(!a.success)window.MKTYPace?.fail(story.chapter,story.simulation?'training':'flight','c'+story.chapter+':t'+story.id+':s'+state.run.seed);const kicker=tr('ГЛАВА ','CHAPTER ')+story.chapter+' / '+(story.id+1)+' '+tr('ИЗ 8','OF 8');modal(`<span class="exp-kicker">${kicker}</span><h2>${tr(...story.title)}</h2><p>${a.success?tr('Задание выполнено. Данные и экипаж доставлены. Можно продолжить план главы.','Assignment complete. Data and crew delivered. Continue the chapter plan.'):tr('Задание не завершено. Активированные ретрансляторы сохранятся при повторе. Предыдущие этапы главы сохранены.','Assignment unfinished. Activated relays are kept on retry. Previous chapter stages are saved.')}</p><button data-exp-dialog="${a.success?'story-complete':'story-retry'}" class="exp-primary">${a.success?tr('ЗАВЕРШИТЬ ЭТАП','COMPLETE STAGE'):tr('ПОВТОРИТЬ ВЫЛЕТ','RETRY FLIGHT')}</button><button data-exp-dialog="hangar" class="exp-quiet">${tr('К плану главы','Chapter plan')}</button>`,{preferQuiet:!a.success});}
  function launch(){if(state.run?.phase==='flight')return flight(true);state.run=R.create(crypto.getRandomValues(new Uint32Array(1))[0],selected,tier,state.profile);save();flight(false);}
  function flight(resume){hudAt=0;saveAt=0;mode='flight';root.dataset.mode='flight';$('expHangar').hidden=true;$('expFlight').hidden=false;resize();labels();hud();draw();brief(resume);}
  function labels(){const r=state.run;$('expFlightSector').textContent='0'+r.tier+' / '+sector(r.tier).toUpperCase();$('expFlightTitle').textContent=story?tr(...story.title):title(r.type);if(story)$('expFlightSector').textContent=tr('ГЛАВА ','CHAPTER ')+story.chapter+' / '+(story.simulation?tr('СИМУЛЯТОР','SIMULATOR'):tr('ДИСТАНЦИОННЫЙ ВЫЛЕТ','REMOTE FLIGHT'));$('expHangarKicker').textContent='MOONKATTY / '+tr('ГЛУБОКИЙ КОСМОС','DEEP SPACE');$('expPause').textContent=tr('Пауза','Pause');$('expHullLabel').textContent=tr('КОРПУС','HULL');$('expEnergyLabel').textContent=tr('БАТАРЕЯ','BATTERY');$('expCargoLabel').textContent=tr('ГРУЗ','CARGO');$('expMapLabel').textContent=tr('КАРТА','MAP');$('expJoystick').setAttribute('aria-label',tr('Джойстик полёта. На клавиатуре — стрелки или WASD.','Flight joystick. Keyboard: arrows or WASD.'));$('expCanvas').setAttribute('aria-label',tr('Космический сектор: корабль, астероиды, сигналы и патрули. Цели доступны на карте.','Space sector with your ship, asteroids, signals and patrols. Objectives are available on the map.'));$('expKeyboard').textContent=tr('WASD / стрелки — полёт · Shift — ускорение · E — действие · Q — сканер · пробел — импульс','WASD / arrows: fly · Shift: boost · E: interact · Q: scan · Space: pulse');}
  function modal(html,opts){stop();$('expDialogBody').innerHTML=html;if(story){$('expDialogBody').querySelectorAll('[data-exp-dialog=hangar]').forEach(b=>b.textContent=tr('К плану главы','Chapter plan'));}if(!$('expDialog').open)$('expDialog').showModal();const body=$('expDialogBody');const quiet=body.querySelector('.exp-quiet');const primary=body.querySelector('.exp-primary');const focusTarget=opts&&opts.preferQuiet&&quiet?quiet:primary||quiet;queueMicrotask(()=>{try{focusTarget?.focus({preventScroll:true});}catch{focusTarget?.focus();}});$('expDialog').dataset.blockSpace=opts&&opts.preferQuiet?'1':'0';}
  function brief(resume){const r=state.run;modal(`<span class="exp-kicker">${tr('БРИФИНГ / MK–01','BRIEFING / MK–01')}</span><h2>${story?tr(...story.title):resume?tr('Продолжить вылет','Resume flight'):title(r.type)}</h2><p>${r.type==='rescue'?tr('Заберите экипаж из двух капсул и вернитесь к кольцевой станции. Жёлтый указатель ведёт к ближайшей цели.','Pick up the crew from two pods and return to the ring station. The amber marker points to the nearest objective.'):r.type==='salvage'?tr('Активируйте два ретранслятора. Затем извлеките самописец из корабля «Эхо» и вернитесь на станцию.','Activate two relays. Then recover the black box from Echo and return to the station.'):tr('Активируйте три ретранслятора и доставьте карту сектора на станцию.','Activate three relays and bring the sector chart back to the station.')}</p><ol><li>${tr('Джойстик слева — полёт. Отпустите его, чтобы затормозить.','Left joystick: fly. Release it to brake.')}</li><li>${tr('Подлетите к объекту и удерживайте кнопку действия.','Approach an object and hold the interaction button.')}</li><li>${tr('Красная линия предупреждает о выстреле. Уходите в сторону или используйте импульс.','A red line warns of a shot. Dodge or use the pulse.')}</li><li>${tr('Ускорение, сканер и импульс расходуют общую батарею. Она восстанавливается сама.','Boost, scan and pulse share a battery. It recharges automatically.')}</li></ol><p class="exp-dialog-note">${tr('Потеря корабля уничтожает груз этого вылета. Уже купленные улучшения сохраняются.','Losing the ship destroys this flight’s cargo. Installed upgrades are permanent.')}</p><button data-exp-dialog="resume" class="exp-primary">${resume?tr('ПРОДОЛЖИТЬ','RESUME'):tr('ВЗЯТЬ УПРАВЛЕНИЕ','TAKE CONTROL')}</button><button data-exp-dialog="hangar" class="exp-quiet">${tr('В ангар','Hangar')}</button>`);}
  let traceAccumulator=0;
  function resume(){traceAccumulator=0;if(state.run?.phase!=='flight')return;if($('expDialog').open)$('expDialog').close();release();paused=false;last=0;saveAt=state.run.time;cancelAnimationFrame(frame);frame=requestAnimationFrame(tick);}
  function pause(){if(!active()||mode!=='flight'||paused)return;modal(`<span class="exp-kicker">${tr('ВЫЛЕТ НА ПАУЗЕ','FLIGHT ON HOLD')}</span><h2>${tr('Вылет на паузе','Flight paused')}</h2><p>${tr('Корабль и патрули остановлены. Позиция, груз и работа с объектами сохранены.','Ship and patrols are stopped. Position, cargo and interaction progress are saved.')}</p><button data-exp-dialog="resume" class="exp-primary">${tr('ПРОДОЛЖИТЬ','RESUME')}</button><button data-exp-dialog="brief" class="exp-quiet">${tr('Управление и задача','Controls & objective')}</button><button data-exp-dialog="hangar" class="exp-quiet">${tr('Сохранить и выйти в ангар','Save & return to hangar')}</button>`);}
  function abandon(){modal(`<h2>${tr('Прервать вылет?','Abandon this flight?')}</h2><p>${tr('Груз и спасённый на борту экипаж будут потеряны. Детали в мастерской и улучшения останутся.','Cargo and crew aboard will be lost. Workshop parts and upgrades will remain.')}</p><button data-exp-dialog="cancel-abandon" class="exp-primary">${tr('ОСТАВИТЬ ВЫЛЕТ','KEEP FLIGHT')}</button><button data-exp-dialog="abandon" class="exp-quiet">${tr('Прервать и вернуться','Abandon & return')}</button>`);}
  function earlyReturn(){modal(`<h2>${tr('Вернуться без выполнения?','Return without completing?')}</h2><p>${tr('Контракт не выполнен. Разгрузка принесёт 35% собранных деталей, контракт не будет засчитан. Спасённый экипаж останется на базе.','Contract unfinished. Unloading banks 35% of collected parts, but the contract will not count. Rescued crew will stay at the base.')}</p><button data-exp-dialog="resume" class="exp-primary">${tr('ПРОДОЛЖИТЬ ВЫЛЕТ','CONTINUE FLIGHT')}</button><button data-exp-dialog="extract" class="exp-quiet">${tr('Завершить: +','Finish: +')+Math.floor(state.run.cargo*.35)+' '+tr('дет.','parts')}</button>`);}
  function result(){stop();if(story){storyResult();return;}const a=state.run.report;modal(`<span class="exp-kicker">${tr('ЭКСПЕДИЦИЯ','EXPEDITION')} / ${a.success?tr('ЗАВЕРШЕНА','COMPLETE'):a.abort?tr('ВОЗВРАТ','RETURN'):tr('СИГНАЛ ПОТЕРЯН','SIGNAL LOST')}</span><h2>${a.success?tr('Вы вернулись.','You made it home.'):a.abort?tr('Вылет завершён','Flight ended'):tr('Корабль потерян','Ship lost')}</h2><p>${a.success?tr('Контракт выполнен. Груз доставлен в мастерскую. Новый вылет изменит расположение объектов и астероидов.','Contract completed. Cargo delivered to the workshop. Your next flight changes object and asteroid positions.'):a.abort?tr('Контракт не засчитан. Можно выбрать новый маршрут и попробовать снова.','Contract not completed. Choose a new route and try again.'):tr('Груз этого вылета потерян. Используйте предупреждения патрулей, импульс и ремонтный дрон.','This flight’s cargo was lost. Use patrol warnings, pulse and the repair tender.')}</p><div class="exp-result-stats"><div><strong>+${a.reward}</strong><span>${tr('ДЕТАЛЕЙ','PARTS')}</span></div><div><strong>${a.rescued}</strong><span>${tr('СПАСЕНО','RESCUED')}</span></div><div><strong>${Math.floor(a.time/60)}:${String(a.time%60).padStart(2,'0')}</strong><span>${tr('ВРЕМЯ','TIME')}</span></div></div>${a.success&&state.profile.wins===1?'<p class="exp-unlock">'+tr('Открыт пояс обломков. В мастерской доступно первое улучшение.','Debris belt unlocked. Your first upgrade is available in the workshop.')+'</p>':a.success&&state.profile.wins===3?'<p class="exp-unlock">'+tr('Открыт тёмный сектор.','Dark sector unlocked.')+'</p>':''}<button data-exp-dialog="hangar" class="exp-primary">${tr('В МАСТЕРСКУЮ','TO THE WORKSHOP')}</button>`,{preferQuiet:!a.success&&!a.abort});}
  function map(){const r=state.run;modal(`<span class="exp-kicker">${tr('КАРТА СЕКТОРА','SECTOR MAP')} / ${r.seed.toString(16).toUpperCase()}</span><h2>${tr('Выберите маршрут','Plot your route')}</h2><canvas id="expFullMap" width="660" height="660"></canvas><p class="exp-map-key">${tr('Ромб — цель · круг — объект · красный — патруль · облако — радиация','Diamond: objective · circle: object · red: patrol · cloud: radiation')}</p><div class="exp-map-targets">${[{...R.BASE,id:'base',kind:'base',seen:true},...r.points.filter(p=>!p.done&&(p.seen||R.primary(r,p)))].map(p=>`<button data-exp-waypoint="${p.id}"><span>${p.seen||p.kind==='base'?kindName(p.kind):tr('Неизвестный сигнал','Unknown signal')}${R.locked(r,p)?' / '+tr('Нет питания','No power'):''}</span><b>${Math.round(R.distance(p,r.ship))} m ↗</b></button>`).join('')}</div><button data-exp-dialog="resume" class="exp-primary">${tr('ВЕРНУТЬСЯ В ПОЛЁТ','BACK TO FLIGHT')}</button>`);drawMap($('expFullMap').getContext('2d'),660,true);}
  function command(a){if(a==='story-complete'&&story&&state.run.report?.success){const task=story,record=structuredClone(state);closeStory();task.complete(record);return;}if(a==='story-retry'&&story){if(typeof story.retry==='function'){const task=story;closeStory();task.retry();return;}const failed=state.run;state.run=R.softRestart(failed,state.profile);save();flight(true);return;}if(a==='repair'||a==='strip'){flightAction(a);save();hud();resume();}if(a==='resume')resume();if(a==='hangar')hangar();if(a==='brief')brief(true);if(a==='cancel-abandon'){if(mode==='flight')resume();else{$('expDialog').close();renderHangar();}}if(a==='abandon'){R.finish(state.run,state.profile,false);save();hangar();}if(a==='extract'){R.finish(state.run,state.profile,false,true);save();result();}}
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.expContract){selected=b.dataset.expContract;renderHangar();}if(b.dataset.expTier){tier=Number(b.dataset.expTier);renderHangar();}if(b.dataset.expBuy&&state.run?.phase!=='flight'){R.buy(state.profile,b.dataset.expBuy);save();renderHangar();}if(b.dataset.expDialog)command(b.dataset.expDialog);if(b.dataset.expWaypoint){state.run.target=b.dataset.expWaypoint;save();resume();}});
  $('expDialog').addEventListener('cancel',e=>{e.preventDefault();if(mode==='flight'&&state.run?.phase==='flight')resume();else hangar();});
  $('expHome').onclick=()=>show('home');$('expLaunch').onclick=launch;$('expResume').onclick=()=>flight(true);$('expAbandon').onclick=abandon;$('expPause').onclick=pause;$('expMap').onclick=map;
  function beginAction(){if(paused)return;const n=R.near(state.run);if(n?.kind==='service'&&Math.hypot(state.run.ship.vx,state.run.ship.vy)<65){modal(`<span class="exp-kicker">${tr('ПОЛЕВОЙ ДРОН / ОДИН РАЗ','FIELD TENDER / ONE USE')}</span><h2>${tr('Ремонт или добыча?','Repair or salvage?')}</h2><p>${tr('Дрон можно использовать один раз. Восстановите корабль сейчас или заберите его детали. После разборки ремонта здесь не будет.','The tender can be used once. Restore your ship now or take its parts. Salvaging it removes this repair opportunity.')}</p><button data-exp-dialog="repair" class="exp-primary">${tr('РЕМОНТ +45 / БАТАРЕЯ 100%','REPAIR +45 / BATTERY 100%')}</button><button data-exp-dialog="strip" class="exp-quiet">${tr('Забрать 40 деталей в груз','Salvage 40 parts as cargo')}</button><button data-exp-dialog="resume" class="exp-quiet">${tr('Решить позже','Decide later')}</button>`);return;}if(n?.kind==='base'&&!R.ready(state.run)){earlyReturn();return;}input.action=true;}
  function bindHold(id,key){const b=$(id);b.addEventListener('pointerdown',e=>{if(paused||b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);b.classList.add('is-held');if(key==='action')beginAction();else input[key]=true;});const end=()=>{input[key]=false;b.classList.remove('is-held');};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,end);}
  bindHold('expBoost','boost');bindHold('expAction','action');
  $('expEMP').onclick=()=>{if(!paused){flightAction('emp');save();hud();}};$('expScan').onclick=()=>{if(!paused){flightAction('scan');save();hud();}};
  const joy=$('expJoystick');function moveStick(e){if(e.pointerId!==stick||paused)return;const b=joy.getBoundingClientRect(),dx=e.clientX-b.x-b.width/2,dy=e.clientY-b.y-b.height/2,dist=Math.hypot(dx,dy),limit=b.width*.32,scale=Math.min(1,limit/(dist||1));input.x=dx*scale/limit;input.y=dy*scale/limit;$('expStick').style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
  joy.addEventListener('pointerdown',e=>{if(paused)return;e.preventDefault();stick=e.pointerId;joy.setPointerCapture(stick);moveStick(e);});joy.addEventListener('pointermove',moveStick);for(const name of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(name,e=>{if(e.pointerId===stick){stick=null;input.x=input.y=0;$('expStick').style.transform='translate(0,0)';}});
  const gameKeys=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight','KeyE','KeyQ','Space','Escape','KeyM'];
  document.addEventListener('keydown',e=>{if($('expDialog')?.open&&e.code==='Space'){e.preventDefault();return;}if(!active()||mode!=='flight'||!gameKeys.includes(e.code))return;if(e.code==='Escape'){if(!paused){e.preventDefault();pause();}return;}if(paused)return;e.preventDefault();if(e.repeat)return;keys.add(e.code);if(e.code==='KeyE')beginAction();if(e.code==='KeyQ')flightAction('scan');if(e.code==='Space')flightAction('emp');if(e.code==='KeyM')map();});
  $('expDialog').addEventListener('keydown',e=>{if(e.code==='Space'&&$('expDialog').dataset.blockSpace==='1'){e.preventDefault();e.stopPropagation();}});
  document.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='KeyE')input.action=false;});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);window.addEventListener('pagehide',stop);
  function flightAction(kind){if(story){state.trace??=[];state.trace.push(['act',kind]);}return R.action(state.run,state.profile,kind);}
  function traceTick(control){if(!story)return;state.trace??=[];const row=['tick',1,control.x,control.y,!!control.boost,!!control.action],last=state.trace.at(-1);if(last?.[0]==='tick'&&row.slice(2).every((v,i)=>v===last[i+2]))last[1]++;else state.trace.push(row);}
  function tick(now){if(paused||!active()||mode!=='flight')return;const dt=last?Math.min((now-last)/1000,.06):0;last=now;
    if(stick===null){input.x=Number(keys.has('ArrowRight')||keys.has('KeyD'))-Number(keys.has('ArrowLeft')||keys.has('KeyA'));input.y=Number(keys.has('ArrowDown')||keys.has('KeyS'))-Number(keys.has('ArrowUp')||keys.has('KeyW'));}
    const control={...input,x:Math.round(input.x*1000)/1000,y:Math.round(input.y*1000)/1000,boost:input.boost||keys.has('ShiftLeft')||keys.has('ShiftRight')};traceAccumulator+=dt;
    while(traceAccumulator>=.02&&state.run.phase==='flight'){traceTick(control);R.step(state.run,state.profile,control,.02);traceAccumulator-=.02;}
    if(state.run.phase==='result'){save();hud();draw();result();return;}
    if(state.run.time-saveAt>=1){save();saveAt=state.run.time;}
    if(state.run.time-hudAt>=.09){hud();hudAt=state.run.time;}
    draw();frame=requestAnimationFrame(tick);
  }
  function hud(){const r=state.run;if(!r)return;const p=state.profile,s=r.ship,n=R.near(r),t=R.target(r),done=r.points.filter(p=>p.done&&R.primary(r,p)).length,total=r.points.filter(p=>R.primary(r,p)).length;
    $('expHull').textContent=Math.ceil(s.hull)+' / '+R.maxHull(p);$('expEnergy').textContent=Math.floor(s.energy)+'%';$('expHullBar').style.width=s.hull/R.maxHull(p)*100+'%';$('expHullBar').classList.toggle('critical',s.hull<35);$('expEnergyBar').style.width=s.energy+'%';$('expCargo').textContent=r.cargo+' '+tr('дет.','parts');
    $('expObjective').textContent=R.ready(r)?tr('ЗАДАЧА ВЫПОЛНЕНА · ВЕРНИТЕСЬ НА БАЗУ','OBJECTIVE COMPLETE · RETURN TO BASE'):tr('ЦЕЛИ ','OBJECTIVES ')+done+' / '+total+' · '+(r.type==='rescue'?tr('СПАСИТЕ ЭКИПАЖ','RESCUE THE CREW'):r.type==='salvage'?tr('ИЗВЛЕКИТЕ САМОПИСЕЦ','RECOVER THE BLACK BOX'):tr('ВОССТАНОВИТЕ СЕТЬ','RESTORE THE NETWORK'));
    const dist=t?Math.round(R.distance(s,t)):0;$('expBearing').textContent=t?(t.seen||t.kind==='base'?kindName(t.kind):tr('Сигнал','Signal'))+' · '+dist+' m'+(dist<=105?' · '+tr('В ЗОНЕ','IN RANGE'):''):'';$('expAction').classList.toggle('exp-action-ready',!!n&&!R.locked(r,n)&&!(n.kind==='base'&&!R.ready(r)&&r.cargo===0));
    $('expBoost').innerHTML=`<b>↗</b><span>${tr('УСКОРЕНИЕ','BOOST')}</span>`;
    $('expEMP').innerHTML=`<b>${r.emp>0?Math.ceil(r.emp)+'s':'◎'}</b><span>${tr('ИМПУЛЬС','PULSE')}</span>`;$('expEMP').disabled=r.emp>0||s.energy<35;
    $('expScan').innerHTML=`<b>${r.scan>0?Math.ceil(r.scan)+'s':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 1v5m0 12v5M1 12h5m12 0h5"/></svg>'}</b><span>${tr('СКАНЕР','SCAN')}</span>`;$('expScan').disabled=r.scan>0||s.energy<15;
    $('expAction').disabled=!n||R.locked(r,n)||(n.kind==='base'&&!R.ready(r)&&r.cargo===0);$('expAction').textContent=!n?tr('ПОДЛЕТИТЕ К ЦЕЛИ','APPROACH TARGET'):R.locked(r,n)?tr('НУЖНЫ 2 РЕТРАНСЛЯТОРА','NEEDS 2 RELAYS'):n.kind==='base'&&r.cargo===0&&!R.ready(r)?tr('ПОКИНЬТЕ СТАНЦИЮ','LEAVE THE STATION'):n.kind==='base'?R.ready(r)?tr('УДЕРЖИВАЙТЕ: СТЫКОВКА','HOLD: DOCK'):tr('ДОСРОЧНЫЙ ВОЗВРАТ','RETURN EARLY'):n.kind==='pod'?tr('УДЕРЖИВАЙТЕ: СПАСЕНИЕ','HOLD: RESCUE'):n.kind==='service'?tr('УДЕРЖИВАЙТЕ: РЕМОНТ','HOLD: REPAIR'):tr('УДЕРЖИВАЙТЕ: ДЕЙСТВИЕ','HOLD: INTERACT');
    const work=r.points.find(p=>p.id===r.interacting);$('expWork').hidden=!work;if(work){$('expWorkLabel').textContent=kindName(work.kind)+' '+Math.round(work.work*100)+'%';$('expWorkBar').style.width=work.work*100+'%';}
    const note=r.time<r.noticeUntil?texts[r.notice]?.()||'':r.alert>0?tr('ПАТРУЛИ ИДУТ ПО СИГНАЛУ · ','PATROLS TRACKING SIGNAL · ')+Math.ceil(r.alert)+'s':n&&Math.hypot(s.vx,s.vy)>65?tr('Отпустите джойстик, чтобы начать работу.','Release the joystick to interact.'):s.hull<35?tr('Корпус повреждён. Найдите ремонтный дрон.','Hull damaged. Find the repair tender.'):tr('Дополнительный груз увеличивает награду при возвращении.','Optional cargo increases your return reward.');if($('expNotice').textContent!==note)$('expNotice').textContent=note;
    drawMap(radar,112,false);
  }
  function resize(){if(mode!=='flight')return;const box=$('expViewport').getBoundingClientRect();width=Math.max(1,box.width);height=Math.max(1,box.height);dpr=Math.min(window.devicePixelRatio||1,2);const c=$('expCanvas');c.width=Math.round(width*dpr);c.height=Math.round(height*dpr);zoom=R.clamp(Math.min(width/600,height/740),.48,.9);if(paused)draw();}
  new ResizeObserver(resize).observe($('expViewport'));
  function poly(c,points,fill,stroke){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.stroke();}}
  function circle(c,x,y,r,stroke,fill){c.beginPath();c.arc(x,y,r,0,Math.PI*2);if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.stroke();}}
  function draw(){const r=state.run;if(!r||!width||!height)return;const c=ctx,s=r.ship,time=r.time;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,width,height);c.fillStyle='#040911';c.fillRect(0,0,width,height);
    if(images.space.complete&&images.space.naturalWidth){const im=images.space,scale=Math.max(width/im.width,height/im.height)*1.22,w=im.width*scale,h=im.height*scale;c.globalAlpha=.38;c.drawImage(im,(width-w)/2-s.x/R.SIZE*35,(height-h)/2-s.y/R.SIZE*35,w,h);c.globalAlpha=1;}
    const camera={x:s.x-width/(2*zoom),y:s.y-height/(2*zoom)};
    c.save();c.scale(zoom,zoom);c.translate(-camera.x,-camera.y);
    for(const a of stars){const x=((a.x-s.x*.1+R.SIZE)%R.SIZE),y=((a.y-s.y*.1+R.SIZE)%R.SIZE);c.globalAlpha=a.alpha;circle(c,x,y,a.r/zoom,null,'#c1d9e8');}c.globalAlpha=1;
    c.lineWidth=1/zoom;c.strokeStyle='#6b92a414';c.beginPath();for(let x=Math.floor(camera.x/200)*200;x<camera.x+width/zoom;x+=200){c.moveTo(x,camera.y);c.lineTo(x,camera.y+height/zoom);}for(let y=Math.floor(camera.y/200)*200;y<camera.y+height/zoom;y+=200){c.moveTo(camera.x,y);c.lineTo(camera.x+width/zoom,y);}c.stroke();c.strokeStyle='#92a9b74d';c.strokeRect(40,40,R.SIZE-80,R.SIZE-80);
    for(const f of r.fields){if(!visible(f,f.r,camera))continue;const g=c.createRadialGradient(f.x,f.y,0,f.x,f.y,f.r);g.addColorStop(0,'#79915c28');g.addColorStop(.75,'#627b5335');g.addColorStop(1,'#b1aa4e00');circle(c,f.x,f.y,f.r,null,g);c.setLineDash([8,12]);circle(c,f.x,f.y,f.r,'#a69a625a');c.setLineDash([]);c.fillStyle='#b9ac78';c.font='11px monospace';c.textAlign='center';c.fillText('ION FIELD',f.x,f.y);}
    base(c,time);
    for(const rock of r.rocks){if(!visible(rock,rock.r+30,camera))continue;c.save();c.translate(rock.x,rock.y);c.rotate(rock.rotation);circle(c,7,12,rock.r*.98,null,'#0009');if(images.rock.complete&&images.rock.naturalWidth)c.drawImage(images.rock,-rock.r,-rock.r,rock.r*2,rock.r*2);else circle(c,0,0,rock.r,'#677b89','#283540');c.restore();}
    for(const p of r.points){if(!visible(p,150,camera))continue;point(c,p,r,time);}
    for(const d of r.drones){if(!visible(d,700,camera))continue;if(d.aim){c.lineWidth=2/zoom;c.setLineDash([9,8]);c.strokeStyle='#ef7767';c.beginPath();c.moveTo(d.x,d.y);c.lineTo(d.targetX,d.targetY);c.stroke();c.setLineDash([]);circle(c,d.targetX,d.targetY,30,'#ff8b7488');}c.save();c.translate(d.x,d.y);c.rotate(Math.atan2(s.y-d.y,s.x-d.x)+Math.PI/2);poly(c,[[0,-24],[22,14],[8,10],[0,18],[-8,10],[-22,14]],'#26333c',d.disabled?'#7ba0ad':'#ae7162');c.fillStyle=d.disabled?'#7ba0ad':'#f48b73';c.fillRect(-3,-9,6,10);c.restore();if(d.disabled){c.setLineDash([5,4]);circle(c,d.x,d.y,34,'#82bcd0');c.setLineDash([]);}}
    for(const b of r.shots){c.strokeStyle='#ffcbb1';c.lineWidth=3;c.beginPath();c.moveTo(b.x,b.y);c.lineTo(b.x-b.vx*.03,b.y-b.vy*.03);c.stroke();}
    if(r.scanWave){c.globalAlpha=r.scanWave/1.3;circle(c,s.x,s.y,(1.3-r.scanWave)*(850+state.profile.upgrades.scanner*180)/1.3,'#91c2d9');c.globalAlpha=1;}
    if(r.pulse){c.lineWidth=3;circle(c,s.x,s.y,(.65-r.pulse)*370/.65,'#bce7ef');}
    c.save();c.translate(s.x,s.y);c.rotate(s.angle);const moving=Math.hypot(s.vx,s.vy)>25;
    if(moving){const length=(input.boost?80:35)+(Math.sin(time*31)+1)*8;const g=c.createLinearGradient(0,12,0,70+length);g.addColorStop(0,'#b4e9ff9c');g.addColorStop(1,'#82bbff00');poly(c,[[-18,15],[-25,40+length],[0,28],[25,40+length],[18,15]],g);}
    if(images.ship.complete&&images.ship.naturalWidth)c.drawImage(images.ship,-51,-35,102,67.3);else poly(c,[[0,-30],[28,22],[0,10],[-28,22]],'#c8d8df');
    c.restore();if(s.invulnerable>0)circle(c,s.x,s.y,60,'#e29c7588');
    c.restore();
    const t=R.target(r);if(t){const x=(t.x-camera.x)*zoom,y=(t.y-camera.y)*zoom;if(x<42||x>width-42||y<80||y>height-60){const a=Math.atan2(y-height/2,x-width/2),vx=Math.cos(a),vy=Math.sin(a),factor=Math.min((width/2-28)/Math.max(Math.abs(vx),.001),(height/2-62)/Math.max(Math.abs(vy),.001));c.save();c.translate(width/2+vx*factor,height/2+vy*factor);c.rotate(a);poly(c,[[12,0],[-7,-7],[-3,0],[-7,7]],'#d4bd80');c.restore();}}
    const vignette=c.createRadialGradient(width/2,height/2,Math.min(width,height)*.3,width/2,height/2,Math.max(width,height)*.7);vignette.addColorStop(0,'#0000');vignette.addColorStop(1,'#0008');c.fillStyle=vignette;c.fillRect(0,0,width,height);
    if(r.damage){c.fillStyle=`rgba(155,52,35,${r.damage*.4})`;c.fillRect(0,0,width,height);}
    c.strokeStyle='#769eb62b';c.lineWidth=1;c.strokeRect(width/2-54*zoom,height/2-54*zoom,108*zoom,108*zoom);
  }
  function visible(o,r,cam){return o.x+r>cam.x&&o.x-r<cam.x+width/zoom&&o.y+r>cam.y&&o.y-r<cam.y+height/zoom;}
  function base(c,t){const b=R.BASE;c.save();c.translate(b.x,b.y);c.lineWidth=2;circle(c,0,0,105,'#708697','#12212ccc');circle(c,0,0,82,'#bad5df4d','#08111bcc');c.save();c.rotate(.15);for(let i=0;i<8;i++){c.rotate(Math.PI/4);poly(c,[[-20,-91],[-14,-124],[14,-124],[20,-91]],'#22323f','#566e7d');c.fillStyle='#afd0da';c.fillRect(-7,-113,14,3);}c.restore();c.setLineDash([6,7]);circle(c,0,0,62,'#9ecec199');c.setLineDash([]);c.fillStyle='#b8d3d7';c.textAlign='center';c.font='12px monospace';c.fillText('ARK / DOCK',0,-12);c.fillStyle='#79bdb9';c.fillRect(-15,8,30,2);c.fillRect(-1,-6,2,30);c.restore();}
  function point(c,p,r,t){c.save();c.translate(p.x,p.y);c.globalAlpha=p.done?.45:1;const color=p.done?'#83b7a7':R.primary(r,p)?'#d7bd7a':'#8dacbf';c.lineWidth=1.5;circle(c,0,0,85,color+'55');
    if(p.kind==='relay'){poly(c,[[-14,-24],[14,-24],[23,18],[0,34],[-23,18]],'#283e4c','#9eb6be');c.fillStyle='#244452';for(const x of [-65,25]){c.fillRect(x,-17,40,34);c.strokeStyle='#62808e';c.strokeRect(x,-17,40,34);for(let j=1;j<4;j++){c.beginPath();c.moveTo(x+j*10,-17);c.lineTo(x+j*10,17);c.stroke();}}circle(c,0,-8,8,p.done?'#bce8c1':color,p.done?'#8dbcae':'#1a272e');}
    if(p.kind==='pod'){poly(c,[[0,-38],[20,-17],[20,23],[10,35],[-10,35],[-20,23],[-20,-17]],'#a6adb0','#d0d7d7');c.fillStyle='#122732';c.fillRect(-11,-10,22,19);c.fillStyle=p.done?'#769080':'#dccba0';c.fillRect(-7,19,14,4);c.strokeStyle='#67777c';c.beginPath();c.moveTo(-17,13);c.lineTo(17,13);c.stroke();}
    if(p.kind==='wreck'){c.rotate(-.48);poly(c,[[-76,0],[-28,-24],[-13,-63],[18,-48],[32,-10],[88,22],[60,37],[20,23],[-22,32]],'#2b373c','#7d8178');poly(c,[[-20,-25],[16,-29],[24,15],[-24,18]],'#384954','#83989c');c.fillStyle='#091722';c.fillRect(-11,-24,20,24);for(let i=0;i<4;i++){c.fillStyle=i%2?'#4b4b40':'#b49b61';c.fillRect(39+i*7,14,5,7);}c.rotate(.48);}
    if(p.kind==='cache'){for(let i=0;i<3;i++){const x=(i-1)*20,y=i===1?-12:6;poly(c,[[x-13,y-16],[x+13,y-16],[x+17,y+13],[x-17,y+13]],'#536068','#9babb0');c.fillStyle='#bda675';c.fillRect(x-8,y-3,16,3);}}
    if(p.kind==='service'){circle(c,0,0,30,'#8dabaf','#21383f');for(let i=-1;i<=1;i+=2){c.fillStyle='#839899';c.fillRect(i*31-6,-20,12,40);}c.fillStyle='#c4dcd0';c.fillRect(-12,-3,24,6);c.fillRect(-3,-12,6,24);}
    c.globalAlpha=1;c.fillStyle=color;c.textAlign='center';c.font='11px monospace';c.fillText(p.done?'✓':p.id.toUpperCase(),0,112);if(!p.done&&p.work>0){c.lineWidth=4;c.strokeStyle=color;c.beginPath();c.arc(0,0,88,-Math.PI/2,-Math.PI/2+p.work*Math.PI*2);c.stroke();}c.restore();}
  function drawMap(c,size,full){const r=state.run;if(!r)return;const k=size/R.SIZE;c.clearRect(0,0,size,size);c.fillStyle='#0a151f';c.fillRect(0,0,size,size);c.strokeStyle='#49687933';c.lineWidth=1;for(let i=1;i<8;i++){c.beginPath();c.moveTo(i*size/8,0);c.lineTo(i*size/8,size);c.moveTo(0,i*size/8);c.lineTo(size,i*size/8);c.stroke();}for(const f of r.fields)circle(c,f.x*k,f.y*k,f.r*k,'#a39d6744','#93885225');
    if(full)for(const a of r.rocks)circle(c,a.x*k,a.y*k,Math.max(1,a.r*k),null,'#6c7a8660');
    const t=R.target(r);if(t){c.setLineDash([3,4]);c.strokeStyle='#dbc28c77';c.beginPath();c.moveTo(r.ship.x*k,r.ship.y*k);c.lineTo(t.x*k,t.y*k);c.stroke();c.setLineDash([]);}
    for(const p of [{...R.BASE,id:'base',kind:'base',seen:true},...r.points]){if(!p.seen&&!R.primary(r,p))continue;const x=p.x*k,y=p.y*k,a=full?7:2.8,col=p.done?'#5e7c74':R.primary(r,p)?'#dbbc7e':'#9fc3d1';if(R.primary(r,p))poly(c,[[x,y-a],[x+a,y],[x,y+a],[x-a,y]],p.seen?col:null,col);else circle(c,x,y,a,col,p.kind==='base'?col:null);if(full){c.font='15px monospace';c.fillStyle=col;c.textAlign='center';c.fillText(p.kind==='base'?'ARK':p.seen?p.id.toUpperCase():'?',x,y+a+18);}}
    for(const d of r.drones)if(full||R.distance(d,r.ship)<800)circle(c,d.x*k,d.y*k,full?5:2,null,d.disabled?'#7899a0':'#d28272');
    const s=r.ship;c.save();c.translate(s.x*k,s.y*k);c.rotate(s.angle);const a=full?10:4;poly(c,[[0,-a],[a*.7,a*.7],[0,a*.4],[-a*.7,a*.7]],'#fff');c.restore();}
  // A prominent entry point is independent of campaign progression and rewards.
  const homeButton=$('expeditionEntry')||document.createElement('button');homeButton.id='expeditionEntry';homeButton.className='exp-entry';homeButton.setAttribute('translate','no');homeButton.onclick=open;
  if(!homeButton.isConnected)$('enterBtn').before(homeButton);
  const chapterButton=document.createElement('button');chapterButton.id='expeditionChapterEntry';chapterButton.className='exp-chapter-entry';chapterButton.setAttribute('translate','no');chapterButton.onclick=open;$('chapterList').before(chapterButton);
  function entryLabels(){homeButton.innerHTML=`<span><small>${tr('ГЛУБОКИЙ КОСМОС','DEEP SPACE')} / ${tr('НОВЫЙ РЕЖИМ','NEW MODE')}</small><strong>${tr('ВЫЛЕТ В ОТКРЫТЫЙ СЕКТОР','EXPLORE OPEN SPACE')}</strong><em>${tr('Исследуйте. Спасайте. Улучшайте корабль.','Explore. Rescue. Upgrade your ship.')}</em></span><b>↗</b>`;chapterButton.textContent=tr('ЭКСПЕДИЦИИ · СВОБОДНЫЙ ПОЛЁТ ↗','EXPEDITIONS · FREE FLIGHT ↗');}
  entryLabels();new MutationObserver(entryLabels).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  return {open,onScreen,openStory,snapshot:()=>structuredClone(state)};
})();
