/* Spatial mission rules. Deterministic state, no timers or DOM dependencies. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FieldRules=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 'use strict';
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
 const kinds=['','rover','crew','trajectory','survey','thermal','docking','stealth','signal','convoy'];
 function random(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
 function create(n,stage,seed){const rnd=random(seed),s={version:1,n,stage,seed:seed>>>0,kind:kinds[n],seconds:0,moves:0,errors:0,complete:false,notice:'intro',selected:0};
  if(n===1||n===7){s.pos=30;s.collected=[];s.turn=0;s.energy=4;s.alert=0;s.scanned=false;s.pos=layout(s).start;}
  if(n===2){s.jobs=[];s.crew=0;s.energy=3;s.selected=0;}
  if(n===3){s.angle=40;s.power=48;s.burn=0;s.trails=[];}
  if(n===4){s.scans=[];s.pad=null;s.samples=[];s.selected=0;}
  if(n===5){s.valves=[25,50,75];s.stable=0;}
  if(n===6){s.ship={x:80,y:370,vx:0,vy:0};s.docked=0;s.integrity=100;s.hold=0;s.impacts=0;}
  if(n===8){s.angles=[20,150,270];s.station=0;s.samples=[false,false,false];s.pin=null;}
  if(n===9){s.ships=[[0,1,2],[0,2,1],[2,0,1],[1,0,2]][stage%4].slice();s.selected=0;s.gate=false;s.cells=3;s.evacuated=[];}
  return s;
 }
 function layout(s){const rnd=random(s.seed),n=s.n,t=s.stage;
  if(n===1||n===7){const rotation=(s.seed+t)%4,flip=((s.seed>>>2)+t)%2,transform=i=>{let x=i%6,y=Math.floor(i/6);if(flip)x=5-x;for(let j=0;j<rotation;j++)[x,y]=[5-y,x];return y*6+x;};const walls=[7,8,10,13,16,19,22,25];return {size:6,start:transform(30),walls:walls.map(transform),targets:(t%2?[2,15,33]:[9,17,27]).map(transform),exit:transform(5),cover:[0,6,12,18,24,30,31,32,33,34,35,5,11,17,23,29].map(transform),hazards:n===1?[9,20,27].map(transform):[],watchers:[{at:transform(14),dir:(s.turn+1+rotation)%4},{at:transform(21),dir:(s.turn+3+rotation)%4}]};}
  if(n===2){const roles=[1,0,2,1,2,0],permutation=[0,1,2,3,4,5].map(i=>(i+t*2)%6),jobs=[];roles.forEach((role,i)=>jobs[permutation[i]]={role:(role+t)%3,requires:(i===0||i===1?[]:i===2?[0]:i===3?[1]:i===4?[2,3]:[4]).map(j=>permutation[j]),cost:i===2?2:1,gain:i===0||i===1?2:i===3?1:0});return {jobs};}
  if(n===3){const targets=Array.from({length:3},(_,i)=>{const angle=35+Math.floor(rnd()*34),power=43+Math.floor(rnd()*21),p=trajectory(angle,power);return{...p,angle,power,radius:22-Math.min(t,3)*2};});return {origin:{x:70,y:390},target:targets[s.burn]||targets[2],targets};}
  if(n===4){const safe=(s.seed%4)*6+8,tiles=Array.from({length:36},(_,i)=>({slope:2+Math.floor(rnd()*13),wind:3+Math.floor(rnd()*19),strength:35+Math.floor(rnd()*60)}));tiles[safe]={slope:2,wind:6,strength:92};tiles[(safe+11)%36]={slope:4,wind:9,strength:85};return{tiles,safe,requiredStrength:70+t*3,maxWind:12-t,maxSlope:5};}
  if(n===5){const target=[35+Math.floor(rnd()*31),35+Math.floor(rnd()*31),35+Math.floor(rnd()*31)];return {target,desired:thermal(target),tolerance:3.5-Math.min(t,3)*.4};}
  if(n===6){const bays=t%2?[{x:115,y:100},{x:435,y:90},{x:470,y:345}]:[{x:470,y:345},{x:435,y:90},{x:115,y:100}];return{bays,target:bays[s.docked]||bays[2],walls:[{x:235,y:185,w:125,h:85}],accel:70+t*8};}
  if(n===8){const source={x:210+rnd()*190,y:115+rnd()*165},stations=[{x:65,y:365},{x:525,y:365},{x:290,y:48}];return{source,stations,bearings:stations.map(a=>(Math.atan2(source.y-a.y,source.x-a.x)*180/Math.PI+360)%360),tolerance:7-Math.min(t,3)};}
  if(n===9)return {nodes:[{x:75,y:350},{x:75,y:225},{x:75,y:100},{x:240,y:335},{x:245,y:100},{x:360,y:245},{x:420,y:95},{x:485,y:320},{x:530,y:170}],edges:[[0,3],[1,3],[1,4],[2,4],t%4===2?[3,4]:[3,5],[4,5],t%4===3?[3,6]:[4,6],[5,7],[6,8],[7,8]],charger:5,gateNode:t%2?7:6,destination:8};
  return {};
 }
 function trajectory(angle,power){const a=angle*Math.PI/180,t=4;return{x:70+Math.cos(a)*power*1.8*t,y:390-Math.sin(a)*power*1.8*t+64};}
 function thermal(v){return[.7*v[0]+.2*v[1]+.1*v[2],.15*v[0]+.65*v[1]+.2*v[2],.2*v[0]+.15*v[1]+.65*v[2]];}
 function watched(s,at){const b=layout(s);if(b.cover.includes(at))return false;return b.watchers.some(w=>{const x=at%6,y=Math.floor(at/6),wx=w.at%6,wy=Math.floor(w.at/6);return w.dir===0?x===wx&&y<wy:w.dir===1?y===wy&&x>wx:w.dir===2?x===wx&&y>wy:y===wy&&x<wx;});}
 function signal(s,i){const b=layout(s),delta=Math.abs(((s.angles[i]-b.bearings[i]+540)%360)-180);return Math.round(clamp(100-delta*3,0,100));}
 function reject(s,notice){s.errors++;s.notice=notice;return false;}
 function act(s,action,value){if(!s||s.complete)return false;if(['angle','power'].includes(action)&&!Number.isFinite(Number(value)))return false;if(action==='valve'&&(!Array.isArray(value)||!Number.isFinite(Number(value[1]))))return false;const b=layout(s);s.notice='working';
  if(s.n===1||s.n===7){
   if(action==='scan'){s.scanned=true;s.notice='scan';return true;}
   if(action==='wait'){s.turn++;s.moves++;s.notice='wait';return true;}
   if(action==='pulse'){if(s.energy<1)return reject(s,'energy');s.energy--;s.alert=0;s.turn++;s.notice='pulse';return true;}
   if(action!=='move'||!Number.isInteger(value)||value<0||value>=36)return false;
   if(Math.abs(value%6-s.pos%6)+Math.abs(Math.floor(value/6)-Math.floor(s.pos/6))!==1||b.walls.includes(value))return reject(s,'blocked');
   if(s.n===1&&b.hazards.includes(value)&&!s.scanned)return reject(s,'scan-first');
   s.pos=value;s.turn++;s.moves++;
   if(s.n===7&&watched(s,value)){s.alert++;s.notice='detected';if(s.alert>=3){s.pos=b.start;s.alert=0;s.errors++;s.notice='checkpoint';}}
   if(b.targets.includes(s.pos)&&!s.collected.includes(s.pos)){s.collected.push(s.pos);s.energy=Math.min(4,s.energy+1);s.notice='collected';}
   if(s.pos===b.exit){if(s.collected.length===3)s.complete=true;else s.notice='missing';}return true;
  }
  if(s.n===2){if(action==='select'){s.selected=clamp(value|0,0,5);return true;}if(action==='role'){s.crew=clamp(value|0,0,2);return true;}if(action!=='assign')return false;const job=b.jobs[s.selected];if(s.jobs.includes(s.selected))return false;if(!job.requires.every(i=>s.jobs.includes(i)))return reject(s,'dependency');if(s.crew!==job.role)return reject(s,'specialist');if(s.energy<job.cost)return reject(s,'energy');s.energy+=job.gain-job.cost;s.jobs.push(s.selected);s.moves++;s.notice='assigned';s.complete=s.jobs.length===6;return true;}
  if(s.n===3){if(action==='angle'||action==='power'){s[action]=clamp(Number(value),action==='angle'?15:20,action==='angle'?80:90);return true;}if(action!=='burn')return false;const p=trajectory(s.angle,s.power);s.trails=[...s.trails.slice(-3),{angle:s.angle,power:s.power,hit:distance(p,b.target)<=b.target.radius}];s.moves++;if(distance(p,b.target)>b.target.radius)return reject(s,'trajectory-miss');s.burn++;s.complete=s.burn===3;s.notice='burn-ok';return true;}
  if(s.n===4){if(action==='select'){s.selected=clamp(value|0,0,35);return true;}if(action==='scan'){for(let i=0;i<36;i++)if(Math.floor(i/6)===Math.floor(s.selected/6)&&!s.scans.includes(i))s.scans.push(i);s.moves++;s.notice='scan';return true;}if(action==='sample'){if(!s.scans.includes(s.selected))return reject(s,'scan-first');if(!s.samples.includes(s.selected))s.samples.push(s.selected);s.notice='sample';return true;}if(action!=='land')return false;const a=b.tiles[s.selected];if(!s.samples.includes(s.selected))return reject(s,'sample-first');if(a.slope>b.maxSlope||a.wind>b.maxWind||a.strength<b.requiredStrength)return reject(s,'unsafe-pad');s.pad=s.selected;s.complete=true;s.moves++;return true;}
  if(s.n===5){if(action==='valve'&&Array.isArray(value)&&Number.isInteger(value[0])&&value[0]>=0&&value[0]<3){s.valves[value[0]]=clamp(Number(value[1]),0,100);s.moves++;return true;}if(action!=='stabilize')return false;if(thermal(s.valves).some((v,i)=>Math.abs(v-b.desired[i])>b.tolerance))return reject(s,'thermal-range');s.complete=true;s.notice='balanced';return true;}
  if(s.n===6){if(action==='brake'){s.ship.vx*=.2;s.ship.vy*=.2;s.moves++;return true;}if(action!=='dock')return false;if(distance(s.ship,b.target)>30)return reject(s,'approach');if(Math.hypot(s.ship.vx,s.ship.vy)>12)return reject(s,'slow');s.docked++;s.moves++;s.ship.vx=s.ship.vy=0;s.integrity=Math.min(100,s.integrity+12);s.complete=s.docked===3;s.notice='docked';return true;}
  if(s.n===8){if(action==='station'){s.station=clamp(value|0,0,2);return true;}if(action==='angle'){s.angles[s.station]=clamp(Number(value),0,359);s.samples[s.station]=false;return true;}if(action==='sample'){if(signal(s,s.station)<100-b.tolerance*3)return reject(s,'weak-signal');s.samples[s.station]=true;s.moves++;s.notice='bearing';return true;}if(action==='pin'&&value&&Number.isFinite(value.x)&&Number.isFinite(value.y)){s.pin={x:clamp(value.x,0,600),y:clamp(value.y,0,450)};return true;}if(action!=='locate')return false;if(!s.samples.every(Boolean))return reject(s,'all-bearings');if(!s.pin||distance(s.pin,b.source)>32)return reject(s,'intersection');s.complete=true;s.notice='source';return true;}
  if(s.n===9){if(action==='select'){s.selected=clamp(value|0,0,2);return true;}if(action==='gate'){if(s.ships[1]!==b.gateNode)return reject(s,'engineer-gate');if(s.gate){s.notice='gate';return true;}if(s.cells<1)return reject(s,'energy');s.cells--;s.gate=true;s.notice='gate';return true;}if(action!=='move'||!Number.isInteger(value)||value<0||value>8)return false;const at=s.ships[s.selected];if(at===8)return false;if(!b.edges.some(([a,z])=>a===at&&z===value||z===at&&a===value))return reject(s,'blocked');if(value===8&&!s.gate)return reject(s,'gate-closed');if(s.selected===2&&value===6)return reject(s,'cargo-clearance');if(value!==8&&s.ships.some((v,i)=>i!==s.selected&&v===value))return reject(s,'occupied');s.ships[s.selected]=value;s.moves++;if(value===5&&!s.evacuated.includes(s.selected)){s.cells++;s.evacuated.push(s.selected);}s.complete=s.ships.every(v=>v===8);return true;}
  return false;
 }
 function tick(s,dt,input={}){if(s.complete)return;s.seconds+=clamp(dt,0,.05);if(s.n!==6)return;const b=layout(s),p=s.ship,d=clamp(dt,0,.04),mag=Math.max(1,Math.hypot(input.x||0,input.y||0));p.vx+=(input.x||0)/mag*b.accel*d;p.vy+=(input.y||0)/mag*b.accel*d;p.vx*=Math.exp(-.9*d);p.vy*=Math.exp(-.9*d);p.x=clamp(p.x+p.vx*d,25,575);p.y=clamp(p.y+p.vy*d,25,425);for(const w of b.walls)if(p.x>w.x-14&&p.x<w.x+w.w+14&&p.y>w.y-14&&p.y<w.y+w.h+14){const edges=[{d:Math.abs(p.x-w.x+14),x:w.x-15,y:p.y},{d:Math.abs(p.x-w.x-w.w-14),x:w.x+w.w+15,y:p.y},{d:Math.abs(p.y-w.y+14),x:p.x,y:w.y-15},{d:Math.abs(p.y-w.y-w.h-14),x:p.x,y:w.y+w.h+15}].sort((a,b)=>a.d-b.d);p.x=edges[0].x;p.y=edges[0].y;p.vx*=.1;p.vy*=.1;s.integrity=Math.max(25,s.integrity-8);s.impacts++;s.notice='impact';}}
 function restore(v,n,stage,seed){if(!v||v.version!==1||v.n!==n||v.stage!==stage||v.seed!==(seed>>>0)||v.kind!==kinds[n]||!Number.isFinite(v.seconds)||v.seconds<0||typeof v.complete!=='boolean'||!Number.isInteger(v.moves)||v.moves<0||!Number.isInteger(v.errors)||v.errors<0)return null;const s=create(n,stage,seed),ints=(a,max,len)=>Array.isArray(a)&&(len===undefined||a.length===len)&&a.every(x=>Number.isInteger(x)&&x>=0&&x<=max)&&a.length<=36,nums=(a,len)=>Array.isArray(a)&&a.length===len&&a.every(x=>Number.isFinite(x)&&x>=0&&x<=100);
  if((n===1||n===7)&&(!Number.isInteger(v.pos)||v.pos<0||v.pos>35||!ints(v.collected,35)||new Set(v.collected).size!==v.collected.length||!v.collected.every(i=>layout(s).targets.includes(i))||!Number.isInteger(v.turn)||v.turn<0||!Number.isFinite(v.alert)||v.alert<0||v.alert>2||!Number.isFinite(v.energy)||v.energy<0||v.energy>4))return null;
  if(n===2&&(!Number.isInteger(v.selected)||v.selected<0||v.selected>5||!Number.isInteger(v.crew)||v.crew<0||v.crew>2||!ints(v.jobs,5)||new Set(v.jobs).size!==v.jobs.length||!v.jobs.every(i=>layout(s).jobs[i].requires.every(j=>v.jobs.includes(j)))||!Number.isFinite(v.energy)||v.energy<0||v.energy>10))return null;
  if(n===3&&(!Number.isInteger(v.burn)||v.burn<0||v.burn>3||!Number.isFinite(v.angle)||v.angle<15||v.angle>80||!Number.isFinite(v.power)||v.power<20||v.power>90||!Array.isArray(v.trails)||v.trails.length>4||v.trails.some(t=>!Number.isFinite(t.angle)||!Number.isFinite(t.power))))return null;
  if(n===4&&(!Number.isInteger(v.selected)||v.selected<0||v.selected>35||v.pad!==null&&(!Number.isInteger(v.pad)||v.pad<0||v.pad>35)||!ints(v.scans,35)||!ints(v.samples,35)||!v.samples.every(i=>v.scans.includes(i))))return null;
  if(n===5&&!nums(v.valves,3))return null;
  if(n===6&&(!v.ship||!['x','y','vx','vy'].every(k=>Number.isFinite(v.ship[k]))||v.ship.x<25||v.ship.x>575||v.ship.y<25||v.ship.y>425||Math.abs(v.ship.vx)>200||Math.abs(v.ship.vy)>200||!Number.isInteger(v.docked)||v.docked<0||v.docked>3||!Number.isFinite(v.integrity)||v.integrity<25||v.integrity>100))return null;
  if(n===8&&(!Array.isArray(v.angles)||v.angles.length!==3||v.angles.some(x=>!Number.isFinite(x)||x<0||x>359)||!Array.isArray(v.samples)||v.samples.length!==3||v.samples.some(x=>typeof x!=='boolean')||!Number.isInteger(v.station)||v.station<0||v.station>2||v.pin&&(!Number.isFinite(v.pin.x)||!Number.isFinite(v.pin.y)||v.pin.x<0||v.pin.x>600||v.pin.y<0||v.pin.y>450)))return null;
  if(n===9&&(!Number.isInteger(v.selected)||v.selected<0||v.selected>2||!ints(v.ships,8,3)||typeof v.gate!=='boolean'||!Number.isFinite(v.cells)||v.cells<0||v.cells>6||!ints(v.evacuated,2)||new Set(v.evacuated).size!==v.evacuated.length))return null;
  const result={...s,...JSON.parse(JSON.stringify(v))};if(v.complete&&!won(result))return null;return result;
 }
 function won(s){const b=layout(s);if(s.n===1||s.n===7)return s.collected.length===3&&s.pos===b.exit;if(s.n===2)return s.jobs.length===6;if(s.n===3)return s.burn===3;if(s.n===4){const t=b.tiles[s.pad];return !!t&&s.samples.includes(s.pad)&&t.slope<=b.maxSlope&&t.wind<=b.maxWind&&t.strength>=b.requiredStrength;}if(s.n===5)return thermal(s.valves).every((v,i)=>Math.abs(v-b.desired[i])<=b.tolerance);if(s.n===6)return s.docked===3;if(s.n===8)return s.samples.every(Boolean)&&s.angles.every((_,i)=>signal(s,i)>=100-b.tolerance*3)&&s.pin&&distance(s.pin,b.source)<=32;if(s.n===9)return s.gate&&s.ships.every(v=>v===8);return false;}
 return {create,layout,act,tick,restore,won,signal,thermal,trajectory,watched,random,clamp,distance,kinds};
});
