/* Campaign legacy: crew decisions (chapter 2), the Echo contact (finale 8) and earlier precision shape later stages and the finale-9 epilogue.
   Stored on this device in localStorage.mkty_legacy_v1. Every effect is a small bounded modifier validated by FieldRules.cleanMods. */
window.MKTYLegacy=(()=>{
 'use strict';
 const KEY='mkty_legacy_v1',tr=(ru,en)=>window.MKTYI18n?window.MKTYI18n.tr(ru,en):(localStorage.getItem('mkty_lang')==='ru'?ru:en);
 const LEADS=['navigator','engineer','scout'];
 /* One unique chapter event (chapters 1, 3–7, 9; chapter 2 has the council/airlock, chapter 8 the Echo call). Shown before the chapter's second field operation. */
 const opt=(id,label,detail)=>({id,label,detail});
 const EVENTS={
  1:()=>({art:'life1-base.webp',kicker:tr('ГЛАВА 01 · СОБЫТИЕ','CHAPTER 01 · EVENT'),title:tr('Метеоритный дождь над базой','Meteor shower over the base'),text:tr('Осколки бьют по куполу. Энергии хватит на одно: прогнать сканер по разломам или укрыть дальнюю антенну.','Fragments are hitting the dome. There is power for one job: sweep the fractures with the scanner or shelter the far antenna.'),options:[opt('scan',tr('Сканировать разломы','Scan the fractures'),tr('Оставшиеся вылазки ровера начнутся с готовым сканом.','The rover’s remaining runs start with the scan done.')),opt('antenna',tr('Укрыть антенну','Shelter the antenna'),tr('Антенна уцелеет: +1 фильтр при расшифровке «Эха» (гл. 8).','The antenna survives: +1 filter when decoding Echo (ch. 8).'))]}),
  3:()=>({art:'launch-bridge-v3.webp',kicker:tr('ГЛАВА 03 · СОБЫТИЕ','CHAPTER 03 · EVENT'),title:tr('Солнечная вспышка','Solar flare'),text:tr('Датчики слепнут от вспышки. Можно экранировать навигацию или записать вспышку для расчёта будущего шлюза.','The flare is blinding the sensors. Shield the navigation, or record the flare to model the future gate.'),options:[opt('shield',tr('Экранировать навигацию','Shield navigation'),tr('Окна захвата в этой главе шире.','Wider capture windows in this chapter.')),opt('record',tr('Записать вспышку','Record the flare'),tr('+5 к стабильности финального шлюза (гл. 9).','+5 final gate stability (ch. 9).'))]}),
  4:()=>({art:'life4-landing.webp',kicker:tr('ГЛАВА 04 · ВЫБОР ПЛОЩАДКИ','CHAPTER 04 · SITE CHOICE'),title:tr('Где искать посадку?','Where do we land?'),text:tr('Разведка нашла два района. От выбора зависят местность и допуски оставшихся операций.','Reconnaissance found two regions. The choice changes the terrain and limits for the remaining operations.'),options:[opt('north',tr('Северное ледяное плато','Northern ice plateau'),tr('Ледяной пейзаж, ветер слабее: допуск ветра +3.','Ice landscape with calmer air: +3 wind limit.')),opt('south',tr('Южный пыльный кратер','Southern dust crater'),tr('Скалистый кратер, плотный грунт: требование прочности −10.','Rocky crater with firm ground: −10 strength requirement.'))]}),
  5:()=>({art:'life5-reactor-v2.webp',kicker:tr('ГЛАВА 05 · СОБЫТИЕ','CHAPTER 05 · EVENT'),title:tr('Утечка хладагента','Coolant leak'),text:tr('Контур C течёт. Сбросить хладагент — проще балансировать сейчас; сохранить — пригодится для ремонта корпуса.','Loop C is leaking. Venting makes balancing easier now; keeping it will help repair the hull later.'),options:[opt('vent',tr('Сбросить хладагент','Vent the coolant'),tr('Допуск контуров в этой главе шире.','Wider loop tolerance in this chapter.')),opt('keep',tr('Сохранить хладагент','Keep the coolant'),tr('+4% к ремонту при стыковках (гл. 6, 9).','+4% docking repairs (ch. 6, 9).'))]}),
  6:()=>({art:'life6-launchpad.webp',kicker:tr('ГЛАВА 06 · СОБЫТИЕ','CHAPTER 06 · EVENT'),title:tr('Обломки на орбите','Debris in orbit'),text:tr('На пути стыковки дрейфует повреждённый зонд. Расчистить коридор или взять зонд на буксир?','A damaged probe is drifting across the docking lane. Clear the corridor or take the probe in tow?'),options:[opt('clear',tr('Расчистить коридор','Clear the corridor'),tr('+3% к ремонту при стыковках этой главы.','+3% docking repairs in this chapter.')),opt('tow',tr('Взять зонд на буксир','Tow the probe'),tr('Батарея зонда: +1 энергия конвою (гл. 9).','The probe’s battery: +1 convoy power (ch. 9).'))]}),
  7:()=>({art:'life7-void.webp',kicker:tr('ГЛАВА 07 · СОБЫТИЕ','CHAPTER 07 · EVENT'),title:tr('Сигнал бедствия в пустоте','Distress call in the void'),text:tr('Спасательная капсула просит помощи прямо в зоне патрулей. Подобрать её или пройти незамеченными?','An escape pod is calling for help inside the patrol zone. Pick it up or slip through unseen?'),options:[opt('rescue',tr('Подобрать капсулу','Pick up the pod'),tr('Пилот капсулы поможет у шлюза: +5 стабильности (гл. 9).','The pod pilot helps at the gate: +5 stability (ch. 9).')),opt('hide',tr('Остаться в тени','Stay hidden'),tr('Сохранённая маршрутная карта: +1 ускоритель шлюза (гл. 9).','A saved route map: +1 gate booster (ch. 9).'))]}),
  9:()=>({art:'orbit-v2.webp',kicker:tr('ГЛАВА 09 · СОБЫТИЕ','CHAPTER 09 · EVENT'),title:tr('Отставшие корабли','Stragglers'),text:tr('Два малых корабля отстали от конвоя. Ждать их или уходить сейчас?','Two small ships have fallen behind the convoy. Wait for them or leave now?'),options:[opt('wait',tr('Дождаться отставших','Wait for the stragglers'),tr('Их пилоты помогут удержать шлюз: +5 стабильности.','Their pilots help hold the gate: +5 stability.')),opt('go',tr('Уходить сейчас','Leave now'),tr('Сэкономленная энергия: +1 энергия конвою в этой главе.','Saved power: +1 convoy power in this chapter.'))]})};
 function read(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&v.version===1)return {version:1,lead:LEADS.includes(v.lead)?v.lead:null,airlock:['crew','cargo'].includes(v.airlock)?v.airlock:null,echo:['answer','silent'].includes(v.echo)?v.echo:null,decodeNoise:Number.isFinite(v.decodeNoise)?v.decodeNoise:null,events:Object.fromEntries(Object.entries(v.events||{}).filter(([n,c])=>EVENTS[n]&&EVENTS[n]().options.some(o=>o.id===c)))};}catch{}return {version:1,lead:null,airlock:null,echo:null,decodeNoise:null,events:{}};}
 function set(k,v){const s=read();s[k]=v;try{localStorage.setItem(KEY,JSON.stringify(s));}catch{}return s;}
 function precise(){let count=0,total=0;for(let n=1;n<=8;n++){try{const p=JSON.parse(localStorage.getItem('mkty_story_plan_'+n+'_v1'));for(const t of Object.values(p?.tasks||{}))if(t?.performance){total++;if(t.performance.precise===true)count++;}}catch{}}return {count,total};}
 /** Modifiers for a story/finale stage. Training (daily) stages never receive campaign modifiers. */
 function mods(chapter,mechanic){const s=read(),m={};
  if(mechanic===2&&chapter===2&&s.lead)m.role=LEADS.indexOf(s.lead);
  if(s.lead==='navigator'){if(mechanic===3&&chapter>=3)m.radius=4;if(mechanic===11)m.preview=1;}
  if(s.lead==='engineer'){if(mechanic===5)m.tolerance=.6;if(mechanic===6)m.repair=6;}
  if(s.lead==='scout'&&mechanic===10)m.charges=1;
  if(mechanic===9&&chapter===9&&s.airlock==='crew')m.cells=1;
  if(mechanic===11){let stability=Math.min(20,precise().count*2);if(s.airlock==='cargo')stability+=10;if(stability)m.stability=stability;let charges=(m.charges||0)+(s.echo==='answer'?1:0);if(charges)m.charges=charges;}
  const e=s.events||{},add=(k,v,max)=>{m[k]=Math.min(max,(m[k]||0)+v);};
  if(chapter===1&&mechanic===1&&e[1]==='scan')m.scanned=1;
  if(mechanic===10&&e[1]==='antenna')add('charges',1,3);
  if(chapter===3&&mechanic===3&&e[3]==='shield')add('radius',2,6);
  if(chapter===4&&mechanic===4&&e[4]){m.site=e[4]==='south'?1:0;if(e[4]==='north')m.wind=3;else m.strength=10;}
  if(chapter===5&&mechanic===5&&e[5]==='vent')add('tolerance',.4,1);
  if(mechanic===6&&e[5]==='keep')add('repair',4,10);
  if(chapter===6&&mechanic===6&&e[6]==='clear')add('repair',3,10);
  if(chapter===9&&mechanic===9){if(e[6]==='tow')add('cells',1,2);if(e[9]==='go')add('cells',1,2);}
  if(mechanic===11){if(e[3]==='record')add('stability',5,40);if(e[7]==='rescue')add('stability',5,40);if(e[9]==='wait')add('stability',5,40);if(e[7]==='hide')add('charges',1,3);}
  return m;}
 // ---------- decision dialog (shares the field-mission dialog look) ----------
 const dlg=document.createElement('dialog');dlg.id='legacyDialog';dlg.className='legacy-dialog';dlg.setAttribute('aria-labelledby','legacyTitle');
 dlg.innerHTML='<div class="legacy-art" aria-hidden="true"></div><small id="legacyKicker" class="legacy-kicker"></small><h2 id="legacyTitle"></h2><p id="legacyText"></p><div id="legacyOptions" class="legacy-options"></div>';
 document.body.append(dlg);dlg.addEventListener('cancel',e=>e.preventDefault());
 function ask({kicker,title,text,art,options},done){dlg.querySelector('.legacy-art').style.backgroundImage=`url('art/${art}')`;dlg.dataset.kind=art;$l('legacyKicker').textContent=kicker;$l('legacyTitle').textContent=title;$l('legacyText').textContent=text;
  $l('legacyOptions').innerHTML=options.map(o=>`<button type="button" data-legacy-choice="${o.id}"><strong>${o.label}</strong><small>${o.detail}</small></button>`).join('');
  $l('legacyOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>{dlg.close();done(b.dataset.legacyChoice);});if(!dlg.open)dlg.showModal();}
 function $l(id){return document.getElementById(id);}
 const council=done=>ask({art:'crew-bridge-v3.webp',kicker:tr('ГЛАВА 02 · СОВЕТ ЭКИПАЖА','CHAPTER 02 · CREW COUNCIL'),title:tr('Кто возглавит экспедицию?','Who leads the expedition?'),text:tr('Moonkatty выбирает ведущего специалиста. Его работы в этой главе стоят на 1 энергию меньше, а опыт пригодится позже — выбор нельзя изменить.','Moonkatty picks a lead specialist. Their jobs in this chapter cost 1 less power, and their expertise pays off later. This choice is final.'),
  options:[{id:'navigator',label:tr('Штурман','Navigator'),detail:tr('Шире окна захвата в манёврах (гл. 3, 8) и подсказка окна в финальном шлюзе.','Wider capture windows in burns (ch. 3, 8) and a window countdown at the final gate.')},{id:'engineer',label:tr('Инженер','Engineer'),detail:tr('Шире допуск тепловых контуров (гл. 5) и усиленный ремонт при стыковке (гл. 6, 9).','Wider thermal tolerance (ch. 5) and stronger docking repairs (ch. 6, 9).')},{id:'scout',label:tr('Разведчик','Scout'),detail:tr('Дополнительный фильтр помех при расшифровке сигнала «Эхо» (гл. 8).','An extra interference filter while decoding the Echo signal (ch. 8).')}]},v=>{set('lead',v);done();});
 const airlock=done=>ask({art:'life2-crew.webp',kicker:tr('ГЛАВА 02 · АВАРИЯ ШЛЮЗА','CHAPTER 02 · AIRLOCK FAILURE'),title:tr('Шлюз грузового отсека заклинило','The cargo-bay airlock has jammed'),text:tr('За дверью техник Мира и последний контейнер с запасами. Воздуха хватит, чтобы открыть шлюз только один раз.','Behind the door are technician Mira and the last supply container. There is air to cycle the lock only once.'),
  options:[{id:'crew',label:tr('Спасти Миру','Rescue Mira'),detail:tr('Мира присоединится к экипажу: +1 энергия конвою в финале и место в эпилоге.','Mira joins the crew: +1 convoy power in the finale and a place in the epilogue.')},{id:'cargo',label:tr('Спасти запасы','Save the supplies'),detail:tr('Запасы укрепят финальный шлюз: +10 к его стабильности.','The supplies reinforce the final gate: +10 gate stability.')}]},v=>{set('airlock',v);done();});
 /** Before a chapter-2 story field stage: council first, the airlock event before the third stage. Returns true when a decision is shown. */
 function before(task,go){if(!task?.legacy||task.daily)return false;const s=read();if(EVENTS[task.chapter]&&task.fieldStage>=1&&!s.events[task.chapter]){const ev=EVENTS[task.chapter]();ask(ev,v=>{const cur=read();cur.events[task.chapter]=v;set('events',cur.events);go();});return true;}if(task.chapter!==2)return false;if(!s.lead){council(go);return true;}if(task.fieldStage>=2&&!s.airlock){airlock(go);return true;}return false;}
 function epilogue(done){const s=read(),p=precise(),lead={navigator:tr('Штурман','Navigator'),engineer:tr('Инженер','Engineer'),scout:tr('Разведчик','Scout')}[s.lead]||tr('не назначен','not assigned');
  const lines=[[tr('Ведущий специалист','Lead specialist'),lead],[tr('Техник Мира','Technician Mira'),s.airlock==='crew'?tr('вернулась домой с экипажем','came home with the crew'):s.airlock==='cargo'?tr('осталась на станции — запасы удержали шлюз','stayed behind; the supplies held the gate'):tr('судьба неизвестна','fate unknown')],[tr('Станция «Эхо»','Echo station'),s.echo==='answer'?tr('ответила и прикрыла переход','answered and shielded the crossing'):s.echo==='silent'?tr('осталась тайной','remains a mystery'):tr('не обнаружена','not contacted')],[tr('Точные операции','Precise operations'),p.count+' / '+p.total],[tr('События глав','Chapter events'),Object.keys(s.events).length+' / '+Object.keys(EVENTS).length]];
  ask({art:'orbit-v2.webp',kicker:tr('ГЛАВА 09 · ЭПИЛОГ','CHAPTER 09 · EPILOGUE'),title:tr('Moonkatty вернулась домой','Moonkatty is home'),text:tr('Шлюз закрылся за последним кораблём. Вот как ваши решения изменили путь домой:','The gate closed behind the last ship. This is how your decisions shaped the way home:'),options:[{id:'done',label:tr('ЗАВЕРШИТЬ ПУТЕШЕСТВИЕ','COMPLETE THE JOURNEY'),detail:''}]},()=>done());
  const list=document.createElement('dl');list.className='legacy-epilogue';list.innerHTML=lines.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');$l('legacyOptions').before(list);dlg.addEventListener('close',()=>list.remove(),{once:true});}
 return {read,set,mods,before,epilogue,precise,council,airlock,EVENTS};
})();
