/* Mission control: real local records, server standings and playable daily training. */
window.MKTYHub=(()=>{
 'use strict';
 const $=id=>document.getElementById(id),tr=(ru,en)=>window.MKTYI18n?window.MKTYI18n.tr(ru,en):(localStorage.getItem('mkty_lang')==='ru'?ru:en);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
 const number=n=>Math.max(0,Number(n)||0),done=n=>localStorage.getItem('mkty_life'+n)==='complete';
 const titles=[['Пробуждение','The Awakening'],['Экипаж','The Crew'],['Код запуска','The Launch Code'],['Спуск','The Descent'],['Зажигание','Ignition'],['Взлёт','Liftoff'],['Пустота','The Void'],['Сигнал','The Signal'],['Возвращение','The Return']];
 const art=['life1-base.webp','crew-bridge-v3.webp','launch-bridge-v3.webp','life4-landing.webp','life5-reactor-v2.webp','life6-launchpad.webp','life7-void.webp','world-orbital.webp','orbit-v2.webp'];
 const routes={crew:['Экипаж','Crew'],ranking:['Рейтинг и рекорды','Standings & records'],more:['Центр управления','Mission control'],settings:['Настройки','Settings'],journal:['Бортовой журнал','Flight journal'],daily:['Тренировка дня','Daily training'],cinema:['Киноархив','Film archive'],community:['Связь с экипажем','Crew communications']};
 const base='https://moonkattymky.github.io/moonkatty-game/',endpoint='https://lswbmgoeinblzuqzakvi.supabase.co/functions/v1/mission-control';
 const root=document.createElement('section');root.id='missionControl';root.className='screen hub-screen';root.setAttribute('translate','no');root.dir='ltr';
 root.innerHTML='<header class="hub-head"><div><small>MOONKATTY / MISSION CONTROL</small><h1 id="hubTitle" tabindex="-1"></h1></div><button id="hubBack" class="hub-icon"></button></header><div id="hubBody"></div><p id="hubNotice" class="hub-notice" role="status" aria-live="polite"></p><nav class="hub-nav" aria-label="Mission control"></nav>';$('app').append(root);
 let route='crew',tab='local',request=null,requestID=0,crewDetail='',journalChapter=0;
 const navItems=[['home','⌂',['Главная','Home']],['chapters','↗',['Миссии','Missions']],['crew','♙',['Экипаж','Crew']],['ranking','▥',['Рейтинг','Standings']],['more','•••',['Ещё','More']]];
 const card=(action,title,detail,icon='↗')=>`<button class="hub-link" data-hub="${action}"><span class="hub-link-icon" aria-hidden="true">${icon}</span><span><strong>${title}</strong><small>${detail}</small></span><b aria-hidden="true">›</b></button>`;
 const metric=(v,l)=>`<div><strong>${esc(v)}</strong><small>${l}</small></div>`;
 function nav(){root.querySelector('.hub-nav').innerHTML=navItems.map(([id,icon,label])=>`<button data-hub="${id}" ${id===(['crew','ranking'].includes(route)?route:'more')?'aria-current="page"':''}><b aria-hidden="true">${icon}</b><span>${tr(...label)}</span></button>`).join('');}
 function notice(text){$('hubNotice').textContent=text;}
 function open(next){if(next==='home'||next==='chapters'){show(next);return;}if(!routes[next])return;route=next;crewDetail='';journalChapter=0;show('missionControl');render();$('hubTitle').focus({preventScroll:true});}
 function onScreen(id){if(id!=='missionControl'){request?.abort();requestID++;root.querySelector('video')?.pause();}if(id==='home')homeLabels();}
 function totalStages(){return Array.from({length:9},(_,i)=>MKTYStory.read(i+1)?.done.length||0).reduce((a,b)=>a+b,0);}
 function profile(){return MKTYExpedition.snapshot().profile;}
 function crew(){const p=profile(),cleared=titles.filter((_,i)=>done(i+1)).length,verified=typeof mktyServerPlayer!=='undefined'&&mktyServerPlayer;
  const name=verified?.first_name||window.Telegram?.WebApp?.initDataUnsafe?.user?.first_name||tr('Пилот','Pilot');
  const joined=done(2)?['Navigator','Engineer','Scout']:read('mkty_campaign_checkpoint_2',{}).joined||[];
  const roles=[['Navigator','НАВИГАТОР','Лётные коридоры, траектории и точная стыковка.','Flight corridors, trajectories and precision docking.'],['Engineer','ИНЖЕНЕР','Энергосистемы, ремонт и тепловой баланс станции.','Power systems, repairs and station thermal balance.'],['Scout','РАЗВЕДЧИК','Поиск сигналов, безопасных маршрутов и ресурсов.','Signals, safe routes and resource reconnaissance.']];
  return `<div class="hub-cover" style="--hub-art:url('art/crew-bridge-v3.webp')"><span>${tr('ЛИЧНОЕ ДЕЛО','PERSONNEL FILE')}</span><h2>${esc(name)}</h2><p>${cleared===9?tr('Командир экспедиции','Expedition commander'):cleared>=3?tr('Офицер лунной миссии','Lunar mission officer'):tr('Участник лунной миссии','Lunar mission crew')}</p></div>
  <div class="hub-metrics">${metric(cleared+' / 9',tr('ГЛАВ ПРОЙДЕНО','CHAPTERS COMPLETE'))}${metric(totalStages()+' / 72',tr('ЭТАПОВ МАРШРУТА','ROUTE STAGES'))}${metric(p.rescued,tr('СПАСЕНО В ВЫЛЕТАХ','RESCUED IN FLIGHTS'))}</div>
  <h2 class="hub-section-title">${tr('Специалисты','Specialists')} <small>${joined.length} / 3</small></h2><div class="hub-role-grid">${roles.map(([id,ru,desc,en],i)=>`<button data-role="${id}" class="hub-role ${joined.includes(id)?'joined':''}" aria-expanded="${crewDetail===id}"><span class="hub-role-mark">0${i+1}</span><small>${joined.includes(id)?tr('В ЭКИПАЖЕ','ON BOARD'):tr('ЗНАКОМСТВО В ГЛАВЕ 2','MEET IN CHAPTER 2')}</small><strong>${tr(ru,id)}</strong><span>${tr(desc,en)}</span></button>`).join('')}</div>
  ${crewDetail?`<div class="hub-panel"><h3>${esc(crewDetail)}</h3><p>${joined.includes(crewDetail)?tr('Специалист присоединился к экипажу. Его задачи входят в маршрут второй главы.','This specialist has joined your crew. Their assignments are part of chapter two.'):tr('Встретьте специалиста на мостике во второй главе и пройдите его испытание.','Meet this specialist on the chapter two bridge and complete their trial.')}</p><button class="hub-primary" data-hub="chapters">${tr('К главам','Open chapters')}</button></div>`:''}
  <h2 class="hub-section-title">${tr('Ваш корабль','Your spacecraft')}</h2><div class="hub-panel"><div class="hub-metrics">${metric(p.parts,tr('ДЕТАЛИ','PARTS'))}${metric(p.wins,tr('УСПЕШНЫЕ ВЫЛЕТЫ','SUCCESSFUL FLIGHTS'))}${metric(p.flights,tr('ВСЕГО ВЫЛЕТОВ','TOTAL FLIGHTS'))}</div><div class="hub-upgrades">${['hull','engine','scanner'].map((k,i)=>`<span>${tr(...[['Корпус','Hull'],['Двигатель','Engine'],['Сканер','Scanner']][i])}<b>${p.upgrades[k]} / 3</b></span>`).join('')}</div><button class="hub-primary" data-hub="hangar">${tr('ОТКРЫТЬ АНГАР И УЛУЧШЕНИЯ','OPEN HANGAR & UPGRADES')} ↗</button></div>${card('community',tr('Пригласить друга','Invite a friend'),tr('Отправить ссылку на игру','Share the game link'),'↗')}`;
 }
 function chapterData(n){const s=MKTYStory.read(n),tasks=Object.values(s?.tasks||{}),finale=MKTYSpatialFinale.read(n),extra=number(read('mkty_operations_'+n+'_v1',{}).seconds)+number(finale?.seconds)+number(finale?.checkpoint?.seconds);return {s,stages:s?.done.length||0,seconds:extra+number(s?.coreSeconds)+tasks.reduce((v,t)=>v+number(t.seconds)+number(t.checkpoint?.seconds||t.checkpoint?.run?.time),0),errors:tasks.reduce((v,t)=>v+number(t.errors),0),precise:tasks.filter(t=>t.performance?.precise).length};}
 const time=s=>Math.floor(number(s)/60)+':'+String(Math.floor(number(s)%60)).padStart(2,'0');
 function ranking(){return `<div class="hub-tabs" role="group" aria-label="${tr('Источник результатов','Results source')}"><button data-rank="local" aria-pressed="${tab==='local'}">${tr('Мои результаты','My records')}</button><button data-rank="online" aria-pressed="${tab==='online'}">${tr('Общий рейтинг','Global standings')}</button></div>${tab==='local'?localRecords():`<div class="hub-panel"><h2>${tr('Лунные очки','Moon Points')}</h2><p>${tr('Данные серверных профилей. Пилоты представлены позывными; личные данные не публикуются. Результаты на этом устройстве могут отличаться.','Server profile standings. Pilots use callsigns; personal data is not published. Results on this device may differ.')}</p><button class="hub-secondary" id="hubRefresh">${tr('Обновить рейтинг','Refresh standings')}</button></div><div id="hubStandings" aria-live="polite"><p class="hub-empty">${tr('Устанавливаем связь…','Establishing contact…')}</p></div>`}`;}
 function localRecords(){const p=profile();return `<div class="hub-panel"><h2>${tr('Журнал достижений','Achievement log')}</h2><p>${tr('Текущие маршруты на этом устройстве. Ошибки и время учитываются по сохранённым этапам; старые прохождения без телеметрии отмечены отдельно.','Current routes on this device. Time and errors come from saved stages; legacy completions without telemetry are marked separately.')}</p></div><div class="hub-records">${titles.map((title,i)=>{const n=i+1,d=chapterData(n);return `<button class="hub-record" data-journal="${n}"><b>${String(n).padStart(2,'0')}</b><span><strong>${tr(...title)}</strong><small>${d.s?d.stages+'/8 · '+tr('время ','time ')+time(d.seconds)+' · '+tr('ошибки ','errors ')+d.errors:done(n)?tr('Пройдено · без телеметрии','Complete · no telemetry'):tr('Ещё не начато','Not started')}</small></span><em>${done(n)?'✓':'›'}</em></button>`;}).join('')}</div><h2 class="hub-section-title">${tr('Лучшие вылеты','Flight records')}</h2><div class="hub-metrics">${p.records.map((v,i)=>metric(v||'—',tr('УРОВЕНЬ ','TIER ')+(i+1))).join('')}</div><p class="hub-muted">${tr('Лучшее число деталей за успешный вылет на каждом уровне сложности.','Most parts earned in a successful flight at each difficulty tier.')}</p>${card('hangar',tr('В свободный полёт','Free flight'),tr('Три типа контрактов и улучшение корабля','Three contract types and ship upgrades'))}`;}
 async function standings(){request?.abort();request=new AbortController();const controller=request,id=++requestID,timer=setTimeout(()=>controller.abort(),12000);$('hubRefresh').disabled=true;
  try{const initData=window.Telegram?.WebApp?.initData;let response=await fetch(endpoint,{method:initData?'POST':'GET',headers:initData?{'Content-Type':'application/json'}:{},body:initData?JSON.stringify({initData}):undefined,signal:request.signal,cache:'no-store'});
   if(response.status===401&&initData)response=await fetch(endpoint,{signal:request.signal,cache:'no-store'});
   const data=await response.json();if(!response.ok||!data.ok||!Array.isArray(data.entries))throw Error('unavailable');if(id!==requestID||route!=='ranking'||tab!=='online')return;
   $('hubStandings').innerHTML=`<div class="hub-ranking-meta"><span>${tr('ПИЛОТОВ В РЕЙТИНГЕ','RANKED PILOTS')}: ${number(data.total)}</span><span>${tr('ОБНОВЛЕНО','UPDATED')}: ${new Date(data.updatedAt).toLocaleTimeString(localStorage.getItem('mkty_lang')||'en',{hour:'2-digit',minute:'2-digit'})}</span></div>${data.entries.length?`<ol class="hub-standings">${data.entries.map(e=>`<li class="${e.self?'self':''}"><b>${number(e.rank)}</b><span><strong>${esc(e.callsign)}${e.self?' · '+tr('ВЫ','YOU'):''}</strong><small>${number(e.chapters)} / 9 ${tr('глав','chapters')}</small></span><em>${number(e.points)} ⭐</em></li>`).join('')}</ol>`:`<p class="hub-empty">${tr('В рейтинге пока нет подтверждённых очков.','No confirmed points in the standings yet.')}</p>`}${data.self?`<p class="hub-panel">${tr('Ваше место','Your rank')}: <strong>${number(data.self.rank)}</strong> · ${number(data.self.points)} ⭐</p>`:''}<p class="hub-muted">${tr('До 50 пилотов. Сначала очки, затем пройденные главы. Равные результаты делят место.','Up to 50 pilots. Points first, then completed chapters. Equal results share a rank.')}</p>`;
  }catch{if(id===requestID&&$('hubStandings'))$('hubStandings').innerHTML=`<div class="hub-panel hub-error"><h3>${tr('Связь с рейтингом потеряна','Standings connection lost')}</h3><p>${tr('Проверьте интернет и повторите загрузку. Ваши местные результаты доступны во вкладке «Мои результаты».','Check your connection and retry. Your local records remain available in My records.')}</p></div>`;}finally{clearTimeout(timer);if(id===requestID&&$('hubRefresh'))$('hubRefresh').disabled=false;}
 }
 function more(){return `<div class="hub-cover compact" style="--hub-art:url('art/launch-bridge-v3.webp')"><span>${tr('СИСТЕМЫ СТАНЦИИ','STATION SYSTEMS')}</span><h2>${tr('Всё под контролем','At your command')}</h2></div><div class="hub-menu">${[
  ['daily',tr('Тренировка дня','Daily training'),tr('Новая задача, сохранение и личный результат','A new task, saved progress and a personal result'),'◈'],
  ['journal',tr('Бортовой журнал','Flight journal'),tr('Маршруты, разведданные и достижения','Routes, intelligence and achievements'),'≡'],
  ['cinema',tr('Киноархив','Film archive'),tr('Просмотр открытых вступлений','Replay unlocked chapter introductions'),'▷'],
  ['hangar',tr('Ангар','Hangar'),tr('Корабль, детали и свободные вылеты','Ship, parts and free flights'),'↗'],
  ['community',tr('Пригласить в игру','Invite to the game'),tr('Отправить ссылку или скопировать её','Share or copy the game link'),'↗'],
  ['settings',tr('Настройки','Settings'),tr('Звук, эффекты и язык','Sound, effects and language'),'⚙'],
  ['rules',tr('Правила и награды','Rules & rewards'),tr('Жизни, очки и условия начисления','Lives, points and reward conditions'),'≡']
 ].map(x=>card(...x)).join('')}</div>`;}
 function settings(){return `<div class="hub-panel"><h2>${tr('Звук и изображение','Sound & picture')}</h2><p>${tr('Облегчённые эффекты уменьшают анимацию и отключают фоновое видео. Системное уменьшение движения тоже учитывается.','Light effects reduce animation and pause background video. Your system motion preference is also respected.')}</p><div id="hubOptions" class="experience-options"></div></div>${card('language',tr('Язык интерфейса','Interface language'),tr('Русский / English и языки базовых глав','Russian / English and base chapter languages'),'◎')}<div class="hub-panel"><h2>${tr('Прогресс','Progress')}</h2><p>${tr('Маршруты и достижения сохраняются на этом устройстве автоматически. Смена языка и настроек их не удаляет.','Routes and achievements are saved automatically on this device. Language and settings changes preserve them.')}</p><p>${tr('Версия','Version')}: <strong>20261005-control-1</strong></p></div>`;}
 function journal(){if(journalChapter){const n=journalChapter,d=chapterData(n),plan=StoryPlan.plan(n,d.s?.edition||2);return `<div class="hub-cover compact" style="--hub-art:url('art/${art[n-1]}')"><span>${tr('ГЛАВА','CHAPTER')} ${n} / 9</span><h2>${tr(...titles[n-1])}</h2></div><div class="hub-metrics">${metric(d.stages+' / 8',tr('ЭТАПЫ','STAGES'))}${metric(time(d.seconds),tr('УЧТЁННОЕ ВРЕМЯ','RECORDED TIME'))}${metric(d.precise,tr('ТОЧНЫЕ ОПЕРАЦИИ','PRECISE OPERATIONS'))}</div><ol class="hub-task-log">${plan.steps.map(t=>`<li class="${d.s?.done.includes(t.id)?'done':''}"><b>${d.s?.done.includes(t.id)?'✓':String(t.id+1).padStart(2,'0')}</b><span><strong>${tr(...t.title)}</strong><small>${d.s?.done.includes(t.id)?tr('Завершено','Complete'):d.s?.tasks[t.id]?.checkpoint?tr('Есть сохранение','Checkpoint saved'):tr('Не завершено','Incomplete')}</small></span></li>`).join('')}</ol><p class="hub-muted">${n===3?tr('Секретный код доступен только в предусмотренных сюжетом окнах показа и подсказке.','The secret code is only available during the story reveal and hint windows.'):tr('Откройте главу, чтобы продолжить доступные задачи.','Open the chapter to continue available assignments.')}</p><button class="hub-primary" data-hub="chapters">${tr('ВЫБРАТЬ ГЛАВУ','CHOOSE CHAPTER')}</button><button class="hub-secondary" data-hub="journal">${tr('Все главы','All chapters')}</button>`;}
 return `<div class="hub-panel"><h2>${tr('Маршрут экспедиции','Expedition route')}</h2><p>${tr('Пройдены главы','Chapters completed')}: ${titles.filter((_,i)=>done(i+1)).length} / 9 · ${tr('этапы текущих маршрутов','current route stages')}: ${totalStages()} / 72</p><progress max="72" value="${totalStages()}" aria-label="${tr('Этапы маршрута','Route stages')}"></progress></div><div class="hub-records">${titles.map((t,i)=>`<button class="hub-record" data-journal="${i+1}"><b>${String(i+1).padStart(2,'0')}</b><span><strong>${tr(...t)}</strong><small>${done(i+1)?tr('Глава пройдена','Chapter complete'):MKTYStory.read(i+1)?tr('Маршрут начат','Route started'):tr('Маршрут не начат','Route not started')}</small></span><em>›</em></button>`).join('')}</div>`;
 }
 const day=()=>new Date().toISOString().slice(0,10);
 function dailySpec(date=day()){const seed=Number(date.replaceAll('-',''))>>>0,n=[1,2,3,4,5,7,8,9][Math.floor(Date.parse(date)/86400000)%8];return {date,seed,n,key:'mkty_training_'+date};}
 function trainingRecord(spec){const record=read(spec.key,{}),state=FieldRules.restore(record.checkpoint,spec.n,2,spec.seed);return {state,result:state?.complete&&FieldRules.won(state)?FieldRules.performance(state):null};}
 function daily(){const spec=dailySpec(),record=trainingRecord(spec);return `<div class="hub-cover" style="--hub-art:url('art/${art[spec.n-1]}')"><span>${tr('ТРЕНИРОВОЧНЫЙ ЦЕНТР','TRAINING CENTRE')} / ${spec.date}</span><h2>${tr(...titles[spec.n-1])}</h2><p>${tr('Ежедневная полевая задача','Daily field assignment')}</p></div><div class="hub-panel"><h2>${record.result?tr('Задача выполнена','Assignment complete'):record.state?tr('Можно продолжить','Ready to resume'):tr('Новая тренировка','New training')}</h2><p>${tr('Одна общая задача на день. Прогресс сохраняется после каждого действия. Результат остаётся на этом устройстве; тренировка не расходует жизни и не начисляет лунные очки.','One shared assignment each day. Every action is saved. Results stay on this device; training uses no lives and awards no Moon Points.')}</p>${record.result?`<div class="hub-metrics">${metric(time(record.state.seconds),tr('ВРЕМЯ','TIME'))}${metric(record.result.errors,tr('ОШИБКИ','ERRORS'))}${metric(record.result.precise?'✓':'—',tr('БЕЗ ОШИБОК','ERROR FREE'))}</div>`:''}<button class="hub-primary" data-daily="${record.result?'replay':'start'}">${record.result?tr('ПОВТОРИТЬ ТРЕНИРОВКУ','REPLAY TRAINING'):record.state?tr('ПРОДОЛЖИТЬ ТРЕНИРОВКУ','RESUME TRAINING'):tr('НАЧАТЬ ТРЕНИРОВКУ','START TRAINING')} →</button><p class="hub-muted">${tr('Следующая задача — в 00:00 UTC.','Next assignment at 00:00 UTC.')}</p></div>`;}
 function startDaily(replay){const spec=dailySpec(),record=trainingRecord(spec);let state=replay?null:record.state;
  const save=checkpoint=>{try{localStorage.setItem(spec.key,JSON.stringify({checkpoint}));}catch{notice(tr('Не удалось сохранить тренировку. Проверьте свободное место.','Could not save training. Check available storage.'));}};
  const task={chapter:spec.n,mechanic:spec.n,daily:true,id:0,phaseCount:1,fieldStage:2,seed:spec.seed,title:[`Тренировка · ${spec.date}`,`Training · ${spec.date}`],save,complete:checkpoint=>{const checked=FieldRules.restore(checkpoint,spec.n,2,spec.seed);if(!checked?.complete||!FieldRules.won(checked))return;save(checked);open('daily');},exit:()=>open('daily')};MKTYField.open(task,state);
 }
 function cinema(){return `<p class="hub-muted">${tr('Вступления открываются по ходу кампании. Просмотр не меняет прохождение.','Introductions unlock with campaign progress. Replays do not change your progress.')}</p><div id="hubPlayer"></div><div class="hub-films">${titles.map((title,i)=>{const unlocked=i===0||done(i);return unlocked?`<button data-film="${i+1}" style="--hub-art:url('art/${art[i]}')"><span>0${i+1} / 09</span><strong>${tr(...title)}</strong><b>▷ ${tr('Смотреть','Watch')}</b></button>`:`<article class="locked"><span>0${i+1} / 09</span><strong>${tr(...title)}</strong><small>${tr('После главы ','After chapter ')}${i}</small></article>`;}).join('')}</div>`;}
 function film(n){if(n<1||n>9||n>1&&!done(n-1))return;const player=$('hubPlayer');player.innerHTML=`<div class="hub-panel"><h2>${tr(...titles[n-1])}</h2><video controls playsinline preload="metadata" poster="art/${art[n-1]}" aria-label="${tr(...titles[n-1])}"></video><p class="hub-muted" id="hubVideoStatus"></p><button class="hub-secondary" id="hubVideoClose">${tr('Закрыть просмотр','Close player')}</button></div>`;const video=player.querySelector('video'),status=$('hubVideoStatus');video.src='life-'+n+'.mp4';video.addEventListener('error',()=>{status.textContent=tr('Не удалось загрузить видео. Проверьте интернет и откройте его снова.','Could not load video. Check your connection and open it again.');});video.play().catch(()=>{status.textContent=tr('Нажмите ▶ на видео, чтобы начать просмотр.','Press ▶ on the video to start playback.');});$('hubVideoClose').onclick=()=>{video.pause();player.replaceChildren();};player.scrollIntoView({behavior:'instant',block:'start'});}
 function community(){return `<div class="hub-cover compact" style="--hub-art:url('art/crew-bridge-v3.webp')"><span>${tr('ОТКРЫТЫЙ КАНАЛ','OPEN CHANNEL')}</span><h2>${tr('Соберите свой экипаж','Bring your crew')}</h2></div><div class="hub-panel"><h2>MOONKATTY: 9 LIVES</h2><p>${tr('Пригласите друга пройти девять глав. Это ссылка на игру; само приглашение не приносит очков.','Invite a friend to play the nine chapters. This is a game link; sharing alone does not award points.')}</p><label class="hub-url-label" for="hubShareURL">${tr('Ссылка на игру','Game link')}</label><input id="hubShareURL" readonly value="${base}" dir="ltr"><div class="hub-actions"><button class="hub-primary" data-share="native">${tr('Поделиться','Share')}</button><button class="hub-secondary" data-share="copy">${tr('Скопировать ссылку','Copy link')}</button><a class="hub-secondary" target="_blank" rel="noopener noreferrer" href="https://t.me/share/url?url=${encodeURIComponent(base)}&text=${encodeURIComponent('MOONKATTY: 9 LIVES')}">${tr('Отправить в Telegram','Share via Telegram')} ↗</a></div></div>`;}
 async function share(kind){const text=tr('MOONKATTY: 9 LIVES — девять глав лунной экспедиции.','MOONKATTY: 9 LIVES — nine chapters of a lunar expedition.');if(kind==='native'&&navigator.share){try{await navigator.share({title:'MOONKATTY: 9 LIVES',text,url:base});notice(tr('Ссылка отправлена.','Link shared.'));return;}catch(e){if(e.name==='AbortError'){notice(tr('Отправка отменена.','Sharing cancelled.'));return;}}}
  try{await navigator.clipboard.writeText(base);notice(tr('Ссылка скопирована. Отправьте её другу.','Link copied. Send it to a friend.'));}catch{$('hubShareURL').focus();$('hubShareURL').select();notice(tr('Ссылка выделена. Выберите «Копировать» в меню устройства.','Link selected. Choose Copy in your device menu.'));}
 }
 function render(){request?.abort();requestID++;root.querySelector('video')?.pause();$('hubTitle').textContent=tr(...routes[route]);$('hubBack').textContent='←';$('hubBack').setAttribute('aria-label',tr('На главный экран','Back to home'));$('hubBody').innerHTML=({crew,ranking,more,settings,journal,daily,cinema,community})[route]();notice('');nav();
  if(route==='settings'){MKTYExperience.mountOptions($('hubOptions'));for(const b of $('hubOptions').children){const label=b.hasAttribute('data-control-sound')?tr('Звук управления','Control sound'):tr('Облегчённые эффекты','Light effects');const update=()=>{b.textContent=label+': '+(b.getAttribute('aria-pressed')==='true'?tr('ВКЛ','ON'):tr('ВЫКЛ','OFF'));};b.addEventListener('click',update);update();}}
  if(route==='ranking'&&tab==='online'){$('hubRefresh').onclick=standings;standings();}
 }
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.hub){const id=b.dataset.hub;if(id==='hangar')MKTYExpedition.open();else if(['rules','language'].includes(id))show(id);else open(id);}else if(b.dataset.role){crewDetail=crewDetail===b.dataset.role?'':b.dataset.role;render();}else if(b.dataset.rank){tab=b.dataset.rank;render();}else if(b.dataset.journal){route='journal';journalChapter=Number(b.dataset.journal);render();window.scrollTo(0,0);}else if(b.dataset.daily)startDaily(b.dataset.daily==='replay');else if(b.dataset.film)film(Number(b.dataset.film));else if(b.dataset.share)share(b.dataset.share);});
 $('hubBack').onclick=()=>show('home');
 function homeLabels(){const nav=document.querySelector('#home .mk-bottom-nav');nav.setAttribute('aria-label',tr('Основная навигация','Main navigation'));[...nav.children].forEach((b,i)=>{const [id,icon,label]=navItems[i];b.type='button';b.dataset.homeNav=id;b.setAttribute('translate','no');b.innerHTML=`<b aria-hidden="true">${icon}</b><span>${tr(...label)}</span>`;if(id==='home')b.setAttribute('aria-current','page');b.onclick=()=>open(id);});$('rulesBtn').textContent='≡';$('rulesBtn').setAttribute('aria-label',tr('Правила и награды','Rules and rewards'));$('settingsBtn').textContent='⚙';$('settingsBtn').setAttribute('aria-label',tr('Настройки','Settings'));}
 $('settingsBtn').onclick=()=>open('settings');
 const teaser=document.querySelector('.mk-life-teaser');const teaserButton=document.createElement('button');teaserButton.className=teaser.className;teaserButton.type='button';teaserButton.innerHTML=teaser.innerHTML;teaserButton.onclick=()=>{open('cinema');film(1);};teaser.replaceWith(teaserButton);
 new MutationObserver(()=>{homeLabels();if(root.classList.contains('active'))render();}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
 homeLabels();return {open,onScreen};
})();
