/* Campaign pacing is a design target, never a countdown or a completion requirement. */
(function(root){
 'use strict';
 const chapters=[
  {n:1,title:['Пробуждение','The awakening'],art:'life1-base.webp',minutes:[12,16],brief:['База замолчала. Восстановите сеть, обследуйте окрестности дистанционным зондом и подготовьте выход Moonkatty на поверхность.','The base has gone silent. Restore its network, survey the surroundings by remote probe and prepare Moonkatty’s surface excursion.'],steps:[['Карта аварийного выхода','Emergency exit route'],['Резервная электросеть','Backup power bus'],['Разведывательный зонд','Reconnaissance probe'],['Позывной базы','Base call sign'],['Аварийные запасы','Emergency supplies'],['Защита телеметрии','Telemetry protection'],['Сигналы спасательных капсул','Escape-pod signals'],['Системы пробуждения','Wake-up systems']]},
  {n:2,title:['Экипаж','The crew'],art:'crew-bridge-v3.webp',minutes:[13,17],brief:['Каждый специалист должен подготовить свой участок. Пройдите навигационную и спасательную симуляции, затем соберите и синхронизируйте экипаж.','Each specialist must prepare their station. Complete navigation and rescue simulations, then assemble and synchronize the crew.'],steps:[['Маршрут штурмана','Navigator’s route'],['Контуры инженера','Engineer’s circuits'],['Симулятор разведчика','Scout simulation'],['Каналы связи экипажа','Crew communication channels'],['Снаряжение специалистов','Specialist equipment'],['Резервные защитные узлы','Backup protection nodes'],['Спасательная симуляция','Rescue simulation'],['Общий план действий','Joint operations plan']]},
  {n:3,title:['Код запуска','The launch code'],art:'launch-bridge-v3.webp',minutes:[14,18],brief:['Сверьте полётный план, проверьте автоматику и отработайте аварийный сценарий. Допуск из первой главы проверяется перед началом подготовки.','Verify the flight plan, check automation and rehearse the emergency procedure. The code from chapter one is checked before preparation begins.'],steps:[['Программа выхода на орбиту','Orbital insertion program'],['Пусковая автоматика','Launch automation'],['Репетиция связи','Communications rehearsal'],['Авторизация команд','Command authentication'],['Развесовка топлива','Propellant distribution'],['Защита пускового контура','Launch circuit shielding'],['Симуляция потери телеметрии','Telemetry loss simulation'],['Последовательность запуска','Launch sequence']]},
  {n:4,title:['Спуск','The descent'],art:'life4-landing.webp',minutes:[16,20],brief:['Посадочная зона повреждена. Разведайте подходы, восстановите маяки и найдите уцелевший регистратор перед ручным спуском.','The landing zone is damaged. Survey approaches, restore beacons and recover the surviving recorder before the manual descent.'],steps:[['Рельеф посадочной зоны','Landing-zone terrain'],['Питание наземных маяков','Ground-beacon power'],['Разведка посадочного сектора','Landing-sector reconnaissance'],['Идентификация маяков','Beacon identification'],['Баланс посадочного модуля','Lander balance'],['Защита от обломков','Debris shielding'],['Регистратор прошлого рейса','Previous flight recorder'],['Резервы посадки','Landing reserves']]},
  {n:5,title:['Зажигание','Ignition'],art:'life5-reactor-v2.webp',minutes:[17,21],brief:['Реактор нельзя запустить одним нажатием. Восстановите снабжение, определите исправные контуры и доставьте данные аварийной диагностики.','The reactor needs more than a start command. Restore supply, identify working circuits and recover emergency diagnostic data.'],steps:[['Маршрут ремонтного зонда','Repair-probe route'],['Магистрали охлаждения','Cooling mainlines'],['Сеть диагностических маяков','Diagnostic beacon network'],['Ключ аварийного журнала','Emergency log key'],['Запас реагентов','Reagent stores'],['Магнитная изоляция','Magnetic isolation'],['Самописец реакторного модуля','Reactor-module black box'],['Порядок восстановления','Recovery sequence']]},
  {n:6,title:['Взлёт','Liftoff'],art:'life6-launchpad.webp',minutes:[16,20],brief:['Подготовьте корабль к тяжёлому взлёту. Проверьте коридор, приведите груз к норме и очистите сеть связи перед стартом.','Prepare the ship for a difficult ascent. Survey the corridor, balance the payload and restore communications before launch.'],steps:[['Траектория взлёта','Ascent trajectory'],['Силовая шина двигателей','Engine power bus'],['Контроль орбитальных маяков','Orbital beacon inspection'],['Диспетчерский допуск','Traffic-control clearance'],['Размещение грузовых модулей','Payload module placement'],['Защита внешнего корпуса','Outer hull shielding'],['Эвакуация из коридора','Corridor evacuation'],['Предстартовый резерв','Preflight reserves']]},
  {n:7,title:['Пустота','The void'],art:'life7-void.webp',minutes:[17,21],brief:['Впереди нет безопасной прямой. Найдите проход, сохраните связь и подберите экипаж потерянного корабля перед пересечением пояса.','There is no safe straight line ahead. Find a passage, maintain the link and recover a lost ship’s crew before crossing the belt.'],steps:[['Карта опасных проходов','Hazardous passage chart'],['Резервное питание радара','Radar backup power'],['Разведка дальнего сектора','Deep-sector reconnaissance'],['Чужой идентификатор','Unknown identifier'],['Перераспределение массы','Mass redistribution'],['Многослойная защита','Layered shielding'],['Экипаж в поясе обломков','Crew in the debris belt'],['Аварийные системы перехода','Transit emergency systems']]},
  {n:8,title:['Сигнал','The signal'],art:'orbit-v2.webp',minutes:[16,20],brief:['Сообщение разбито между несколькими источниками. Восстановите ретрансляторы, извлеките журнал и подготовьте приёмник к финальной расшифровке.','The message is split between several sources. Restore relays, recover the log and prepare the receiver for final decoding.'],steps:[['Геометрия приёма','Reception geometry'],['Питание антенной сети','Antenna-network power'],['Триангуляция источников','Source triangulation'],['Ключ первого слоя','First-layer key'],['Баланс антенных модулей','Antenna-module balance'],['Подавление помех','Interference suppression'],['Архив потерянной станции','Lost-station archive'],['Сборка приёмного комплекса','Receiver commissioning']]},
  {n:9,title:['Возвращение','The return'],art:'orbit-v2.webp',minutes:[18,24],brief:['Путь домой требует работающей сети и полного экипажа. Восстановите маршрут, эвакуируйте людей и подготовьте шлюз для последней передачи.','The way home needs a working network and a complete crew. Restore the route, evacuate survivors and prepare the gate for the final transmission.'],steps:[['Коридор возвращения','Return corridor'],['Питание шлюзовой сети','Gate-network power'],['Восстановление дальних узлов','Remote-node recovery'],['Подтверждение домашнего адреса','Home-address verification'],['Баланс возвращаемого груза','Return payload balance'],['Защита перехода','Gate transit shielding'],['Последняя эвакуация','Final evacuation'],['Резервы жизнеобеспечения','Life-support reserves']]}
 ];
 const fieldNames=[
[['Периметр базы','Base perimeter'],['Питание обсерватории','Observatory power'],['Повреждённый сектор','Damaged sector'],['Выход к маяку','Reach the beacon']],
[['Дежурная смена','Duty crew'],['Ремонт магистрали','Mainline repair'],['Эвакуационный план','Evacuation plan'],['Совместная операция','Joint operation']],
[['Первый импульс','First impulse'],['Орбитальный захват','Orbital capture'],['Коррекция траектории','Trajectory correction'],['Три манёвра до орбиты','Three burns to orbit']],
[['Лидарная разведка','Lidar survey'],['Опорная площадка','Landing foundation'],['Поиск защищённого плато','Sheltered plateau'],['Последний участок захода','Final approach site']],
[['Каскад охлаждения','Cooling cascade'],['Перекрёстные контуры','Coupled loops'],['Тепловая диагностика','Thermal diagnostics'],['Рабочий режим ядра','Core operating mode']],
[['Стыковочный тренажёр','Docking rehearsal'],['Перенос орбитального модуля','Orbital module transfer'],['Три узла обслуживания','Three service ports'],['Чистый коридор','Clear corridor']],
[['За границей радара','Beyond radar'],['Тихая разведка','Silent reconnaissance'],['Данные из опасной зоны','Hazard-zone data'],['Безопасный выход','Safe extraction']],
[['Первый пеленг','First bearing'],['Сеть дальних антенн','Deep-array network'],['Пересечение лучей','Beam intersection'],['Источник за горизонтом','Source beyond the horizon']],
[['Сбор конвоя','Assemble the convoy'],['Разделение маршрутов','Split routes'],['Питание перехода','Transit power'],['Никого не оставить','Leave no one behind']]];
 const prerequisites=[[],[],[0,1],[2],[2],[3,4],[5],[6]],boards=[4,5,null,8,6,7,null,9];
 function plan(n,edition=2){const c=chapters[n-1];if(!c)return null;const level=n<=2?0:n<=5?1:2;const result={...c,steps:c.steps.map((title,i)=>({id:i,title,requires:prerequisites[i].slice(),kind:boards[i]?'board':'flight',board:boards[i],round:Math.min(2,level+(i===7?1:0)),contract:i===2?'survey':n===3||n===4||n===5||n===8?'salvage':'rescue',tier:n<=3?1:n<=6?2:3,simulation:n===2||n===3}))};if(edition===2){result.steps[2].contract=['survey','rescue','salvage','survey','salvage','rescue','rescue','survey','salvage'][n-1];result.steps[2].title=({survey:['Разведка дальнего сектора','Distant sector survey'],rescue:['Эвакуация экипажа','Crew evacuation'],salvage:['Извлечение самописца','Black box recovery']})[result.steps[2].contract];const ids=[0,3,5,6],names=fieldNames[n-1];for(const [stage,id]of ids.entries())Object.assign(result.steps[id],{kind:'field',fieldStage:stage,title:names[stage],board:null});result.steps[1].board=({1:5,2:6,3:9,4:4,5:5,6:6,7:7,8:8,9:9})[n];result.steps[4].board=({1:6,2:9,3:6,4:9,5:6,6:4,7:4,8:5,9:6})[n];result.steps[7].board=({1:9,2:5,3:5,4:6,5:9,6:9,7:9,8:8,9:7})[n];const labels={4:['Навигационный маршрут','Navigation route'],5:['Энергетическая магистраль','Power mainline'],6:['Распределение массы','Mass distribution'],7:['Защитный экран','Shield array'],8:['Ключ ретранслятора','Relay key'],9:['Резервы операции','Operation reserves']};for(const id of [1,4,7])result.steps[id].title=labels[result.steps[id].board];}return result;}
 function fresh(n,seed,edition=2){return {version:1,edition,n,seed:seed>>>0,phase:'operations',done:[],tasks:{},coreSeconds:0,createdAt:Date.now()};}
 function available(s,i){return !s.done.includes(i)&&plan(s.n,s.edition||1).steps[i].requires.every(j=>s.done.includes(j));}
 function restore(value){if(!value||value.version!==1||!Number.isInteger(value.n)||value.n<1||value.n>9||!Number.isInteger(value.seed)||value.seed<0||value.seed>4294967295||!['operations','core','complete'].includes(value.phase)||!Array.isArray(value.done)||value.done.some(i=>!Number.isInteger(i)||i<0||i>7)||new Set(value.done).size!==value.done.length)return null;const edition=value.edition===undefined?1:value.edition;if(![1,2].includes(edition))return null;const p=plan(value.n,edition);if(value.done.some(i=>!p.steps[i].requires.every(j=>value.done.includes(j)))||value.phase!=='operations'&&value.done.length!==8)return null;const s=fresh(value.n,value.seed,edition);s.phase=value.phase;s.done=value.done.slice();s.tasks={};if(value.tasks&&typeof value.tasks==='object'&&!Array.isArray(value.tasks))for(const [id,t]of Object.entries(value.tasks)){if(!/^[0-7]$/.test(id)||!t||typeof t!=='object'||Array.isArray(t))continue;s.tasks[id]={kind:p.steps[Number(id)].kind,attempt:Number.isInteger(t.attempt)&&t.attempt>=0&&t.attempt<=10000?t.attempt:0,seconds:Number.isFinite(t.seconds)&&t.seconds>=0?Math.min(t.seconds,1e7):0,hints:Number.isFinite(t.hints)&&t.hints>=0?t.hints:0,errors:Number.isFinite(t.errors)&&t.errors>=0?t.errors:0};if(t.checkpoint&&typeof t.checkpoint==='object'&&!Array.isArray(t.checkpoint))s.tasks[id].checkpoint=t.checkpoint;}s.coreSeconds=Number.isFinite(value.coreSeconds)&&value.coreSeconds>=0?Math.min(value.coreSeconds,1e7):0;return s;}
 function seedFor(s,i,attempt=0){return (s.seed+Math.imul(i+1,2654435761)+Math.imul(attempt,7919))>>>0;}
 const api={chapters,plan,fresh,available,restore,seedFor};if(typeof module==='object'&&module.exports)module.exports=api;else root.StoryPlan=api;
})(typeof globalThis!=='undefined'?globalThis:this);
