// Run with Node.js and Playwright installed; see README.md. No account or live rewards are used.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'moonkatty-qa-'));
fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.mp4':'video/mp4'};
const server=http.createServer((req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(data);});}catch{res.writeHead(400).end();}});
let browser;const report={errors:[],bad:[]};
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(6000);p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.url().includes('127.0.0.1')&&r.status()>=400)report.bad.push(r.url());});await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date('2026-10-04T12:00Z')});await p.clock.pauseAt(new Date('2026-10-04T12:00Z'));await p.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});
const click=s=>p.locator(s).click(),run=ms=>p.clock.runFor(ms),shot=name=>p.screenshot({path:out+'/'+name+'.png'});
async function pause(n){await click('#mission'+n+' .chapter-menu');assert(await p.locator('#chapterGuide').isVisible());}
async function reopen(){await p.reload();await click('#enterBtn');assert(await p.locator('#chapterGuide').isVisible());}
await p.evaluate(()=>{setLang('en');for(let n=1;n<=6;n++){localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life'+n+'_awarded','yes');}localStorage.setItem('mkty_points','5500');localStorage.setItem('mkty_current_chapter','6');localStorage.setItem('mkty_life1_code_presented','yes');localStorage.setItem('mkty_life3_memory_verified','yes');show('home');});await click('#enterBtn');assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission7');await run(2000);await pause(7);const before=await p.evaluate(()=>({cp:JSON.parse(localStorage.getItem('mkty_campaign_checkpoint_7')),ys:[...document.querySelectorAll('.asteroid7')].map(e=>e.offsetTop)}));assert(before.cp.distance>5);assert(before.cp.rocks.length>0);await run(5000);await p.waitForTimeout(250);assert.equal(await p.locator('#distance7').textContent(),String(Math.round(before.cp.distance)));assert.deepEqual(await p.locator('.asteroid7').evaluateAll(es=>es.map(e=>e.offsetTop)),before.ys);await reopen();assert.equal(await p.locator('#distance7').textContent(),String(Math.round(before.cp.distance)));assert.equal(await p.locator('.asteroid7').count(),before.cp.rocks.length);const afterYs=await p.locator('.asteroid7').evaluateAll(es=>es.map(e=>e.offsetTop));assert(afterYs.every((y,i)=>Math.abs(y-before.ys[i])<=2));await click('#guideMissions');assert(await p.locator('[data-chapter="7"]').isEnabled());report.chapter7ResumeWithRocksAndPause=true;
await p.evaluate(()=>{const key='mkty_campaign_checkpoint_7',cp=JSON.parse(localStorage.getItem(key));Object.assign(cp,{distance:99.6,rocks:[]});localStorage.setItem(key,JSON.stringify(cp));});await click('[data-chapter="7"]');await click('#guideResume');await run(200);assert(await p.locator('#life7Complete').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'7250');await click('#life7ReturnBtn');await click('#missionsBtn');await click('[data-chapter="7"]');assert(await p.locator('#life7Complete').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'7250');report.chapter7CompletedReview=true;
await click('#continueLife8Btn');await click('#life8SkipBtn');for(let v=20;v<=80;v++){await p.locator('#freq8').fill(String(v));if(await p.locator('#strengthFill8').evaluate(e=>parseFloat(e.style.width))>=96)break;}await click('#lockFreq8');await pause(8);await reopen();assert.equal(await p.locator('#mission8').getAttribute('data-stage'),'phase');await click('#guideResume');await p.locator('#phase8').fill(String(await p.locator('.phase-scope8').evaluate(e=>parseFloat(e.style.getPropertyValue('--phase-target')))));await click('#lockPhase8');await run(2850);
for(let round=1;round<=3;round++){const seq=await p.locator('#pulseDisplay8 span').allTextContents();assert(seq.every(s=>['◯','△','◇'].includes(s)));await run(3000);await click('[data-pulse8="'+['◯','△','◇'].indexOf(seq[0])+'"]');if(round===1){await pause(8);await reopen();assert.equal(await p.locator('#pulseRound8').textContent(),'1');assert.equal(await p.locator('#pulseDisplay8 .filled').count(),1);await click('#guideResume');}for(const s of seq.slice(1))await click('[data-pulse8="'+['◯','△','◇'].indexOf(s)+'"]');if(round<3)await run(650);}
assert(await p.locator('#life8Complete').isVisible());const coords=await p.evaluate(()=>localStorage.getItem('mkty_life9_coordinates'));assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'9250');await click('#life8ReturnBtn');await p.reload();await click('#missionsBtn');await click('[data-chapter="8"]');assert(await p.locator('#life8Complete').isVisible());assert((await p.locator('#coordinatesValue8').textContent()).includes(coords.split(',')[0]));report.chapter8StageInputAndCoordinatesPreserved=true;
await click('#continueLife9Btn');await click('#life9SkipBtn');const parts=coords.split(',');await p.locator('#coordLat9').fill(parts[0].replace('.',','));await p.locator('#coordLon9').fill(parts[1].replace('.',','));await click('#verifyCoords9');assert.equal(await p.locator('#mission9').getAttribute('data-stage'),'corridor');assert.equal(await p.locator('#core9').textContent(),'100');await pause(9);await reopen();assert.equal(await p.locator('#mission9').getAttribute('data-stage'),'corridor');await click('#guideResume');await p.locator('#navDial9').fill(String(await p.locator('.corridor-meter9').evaluate(e=>parseFloat(e.style.getPropertyValue('--corridor-target')))));await click('#lockNav9');report.decimalCommaAcceptedWithoutPenalty=true;
for(let round=1;round<=3;round++){const seq=await p.locator('#syncSequence9 span').allTextContents();assert(seq.every(s=>['A','B','C'].includes(s)));await run(2700);await click('[data-sync9="'+['A','B','C'].indexOf(seq[0])+'"]');if(round===2){await pause(9);await reopen();assert.equal(await p.locator('#syncRound9').textContent(),'2');assert.equal(await p.locator('#syncSequence9 .filled').count(),1);await click('#guideResume');}for(const s of seq.slice(1))await click('[data-sync9="'+['A','B','C'].indexOf(s)+'"]');if(round<3)await run(550);}
const final=await p.locator('#finalCode9 span').allTextContents();await run(2700);for(const s of final.slice(0,2))await click('[data-final9="'+['▲','●','◆','■'].indexOf(s)+'"]');await pause(9);const power=await p.locator('#core9').textContent();await run(5000);assert.equal(await p.locator('#core9').textContent(),power);await reopen();assert.equal(await p.locator('#core9').textContent(),power);assert.equal(await p.locator('#finalCode9 .filled').count(),2);await click('#guideResume');for(const s of final.slice(2))await click('[data-final9="'+['▲','●','◆','■'].indexOf(s)+'"]');await run(1000);assert(await p.locator('#life9Complete').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_final_moon_points')),'12250');report.finaleResumesPartialCodeAndPower=true;report.finalBalanceLocksImmediately=true;
await click('#life9ReturnBtn');await p.reload();await click('#missionsBtn');assert.equal(await p.locator('[data-chapter]:enabled').count(),9);for(let n=7;n<=9;n++){await click('[data-chapter="'+n+'"]');assert(await p.locator('#life'+n+'Complete').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');await click('#life'+n+'ReturnBtn');await click('#missionsBtn');}report.allContinuationChaptersReopenWithoutDuplicateAwards=true;
assert.deepEqual(report.errors,[]);assert.deepEqual(report.bad,[]);fs.writeFileSync(out+'/continuation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(e=>{report.failure=e.stack;fs.writeFileSync(out+'/continuation.json',JSON.stringify(report,null,2));console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve));});
