/* New multi-step objectives must survive real browser pause/reload. */
const {chromium}=require('./pace-hook.cjs'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),http=require('http'),R=require('../field-model.js'),solve=require('./field-browser-helper.cjs');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||'/tmp/detail-ui';fs.mkdirSync(out,{recursive:true});let browser,p;
const report={errors:[],checkpoints:[],layouts:[],legacy:[]};
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://a'),f=path.join(root,u.pathname==='/'?'index.html':u.pathname);fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.css':'text/css','.js':'application/javascript'})[path.extname(f)]||'application/octet-stream'});res.end(e?'':b);});});
async function open(n,legacy=false){await p.evaluate(({n,legacy})=>{const key='detail-test-'+n;let saved=JSON.parse(localStorage.getItem(key)||'null');if(legacy){saved=FieldRules.create(n,3,21);saved.version=1;for(const k of ['detections','trim','sites','load','diagnosed','isolated','surveyed'])delete saved[k];}MKTYField.open({chapter:n,id:0,fieldStage:3,seed:21,title:['Проверка продолжения','Resume review'],save:s=>localStorage.setItem(key,JSON.stringify(s)),complete:s=>{window.detailResult=s;show('chapters');},exit:()=>show('chapters')},saved);},{n,legacy});await p.locator('#fieldResume').click();}
(async()=>{await new Promise(r=>server.listen(0,r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(6500);p.on('pageerror',e=>report.errors.push(e.message));await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date(new Date('2026-10-05T12:00Z').getTime()-60000)});await p.clock.pauseAt(new Date('2026-10-05T12:00Z'));await p.goto('http://localhost:'+server.address().port);await p.evaluate(()=>setLang('ru'));
const click=selector=>p.locator(selector).click(),action=(a,v)=>click('[data-field-action="'+a+'"]'+(v===undefined?'':'[data-value="'+v+'"]')),snap=()=>p.evaluate(()=>MKTYField.snapshot());
for(const n of [3,4,5,9]){
 await open(n);const s=await snap(),b=R.layout(s);
 if(n===3){for(const key of ['angle','power','trim'])await p.locator('[data-field-slider="'+key+'"]').fill(String(b.target[key]));await click('#fieldSubmit');assert.equal((await snap()).burn,1);}
 if(n===4){await click('[data-field-cell="'+b.safe+'"]');await action('scan');await action('sample');await click('#fieldSubmit');assert.equal((await snap()).sites.length,1);assert(!(await snap()).complete);}
 if(n===5){await action('diagnose');await action('isolate',b.fault);for(let i=0;i<3;i++)await p.locator('[data-field-slider="valve"][data-index="'+i+'"]').fill(String(b.target[i]));await click('#fieldSubmit');assert.equal((await snap()).load,1);}
 if(n===9){await action('select',0);const at=s.ships[0],to=b.edges.flatMap(([a,z])=>a===at?[z]:z===at?[a]:[]).find(i=>!s.ships.includes(i));assert(to>2);await click('[data-field-cell="'+to+'"]');assert((await snap()).surveyed.includes(to));}
 const before=await snap();await click('#fieldPause');await p.clock.runFor(3000);await click('#fieldExit');await p.reload();await open(n);assert.deepEqual(await snap(),before);await solve(p);assert(await p.evaluate(()=>detailResult.complete));report.checkpoints.push(n);
}
for(const n of [3,5]){await open(n,true);if(n===3)assert.equal(await p.locator('[data-field-slider="trim"]').count(),0);if(n===5)assert.equal(await p.locator('[data-field-action="diagnose"]').count(),0);await solve(p);report.legacy.push(n);}
for(const lang of ['ru','en'])for(const [width,height]of [[320,480],[390,844],[568,320],[844,390]]){
 await p.setViewportSize({width,height});await p.evaluate(l=>{setLang(l);localStorage.removeItem('detail-test-5');},lang);await open(5);if(await p.locator('.field-guide summary').isVisible()){await p.locator('.field-guide summary').click();assert(await p.locator('#fieldBrief').isVisible());await p.locator('.field-guide summary').click();}else{await click('#fieldPause');assert(await p.locator('#fieldDialogText').isVisible());assert((await p.locator('#fieldDialogText').innerText()).length>30);await click('#fieldResume');}
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);for(let i=0;i<3;i++)await p.locator('[data-field-slider="valve"][data-index="'+i+'"]').click();await solve(p,{finish:false});assert(await p.locator('#fieldReview').isVisible());assert.equal(await p.locator('#fieldControls').isVisible(),false);await p.screenshot({path:out+'/thermal-'+lang+'-'+width+'.png',fullPage:true});await click('#fieldSubmit');report.layouts.push({lang,width,height});
}
assert.deepEqual(report.errors,[]);console.log(JSON.stringify(report));
})().catch(async e=>{report.failure=e.stack;console.error(e);await p?.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/detail-ui.json',JSON.stringify(report,null,2));await browser?.close();server.close();});
