/* Actual keyboard/pointer journeys. Snapshot is read-only; no flight progress is injected. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'mkty-exp-'));fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png'})[path.extname(file)]||'application/octet-stream'});res.end(e?'':b);});});
const report={errors:[],bad:[],journeys:[],layouts:[]};let browser,p;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
// A* plots a course around the same visible asteroid and ion-cloud geometry a player can inspect.
function pathTo(r,target){const step=45,n=72,id=(x,y)=>y*n+x,pos=i=>({x:i%n*step,y:Math.floor(i/n)*step}),grid=o=>id(Math.round(o.x/step),Math.round(o.y/step));const start=grid(r.ship),end=grid(target),open=[start],previous=new Map(),cost=new Map([[start,0]]),seen=new Set(),blocked=new Map();const safe=i=>{if(!blocked.has(i)){const a=pos(i);blocked.set(i,a.x<60||a.x>3140||a.y<60||a.y>3140||r.rocks.some(b=>distance(a,b)<b.r+48)||r.fields.some(b=>distance(a,b)<b.r+45));}return i===start||i===end||!blocked.get(i);};let found=false;while(open.length){open.sort((a,b)=>(cost.get(a)+distance(pos(a),target))-(cost.get(b)+distance(pos(b),target)));const a=open.shift();if(a===end){found=true;break;}if(seen.has(a))continue;seen.add(a);const x=a%n,y=Math.floor(a/n);for(const [dx,dy]of[[0,1],[0,-1],[1,0],[-1,0],[1,1],[-1,1],[1,-1],[-1,-1]]){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=n||yy>=n)continue;const b=id(xx,yy);if(!safe(b)||(dx&&dy&&(!safe(id(x+dx,y))||!safe(id(x,y+dy)))))continue;const value=cost.get(a)+Math.hypot(dx,dy)*step;if(value<(cost.get(b)??Infinity)){cost.set(b,value);previous.set(b,a);open.push(b);}}}assert(found,'No clear navigation path');const points=[];for(let a=end;a!==start;a=previous.get(a))points.unshift(pos(a));points.push(target);return points;}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(7000);p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.url().includes('127.0.0.1')&&r.status()>=400)report.bad.push(r.url());});await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date('2026-10-04T18:00Z')});await p.clock.pauseAt(new Date('2026-10-04T18:00Z'));const url='http://127.0.0.1:'+server.address().port;await p.goto(url,{waitUntil:'domcontentloaded'});await p.evaluate(()=>{setLang('ru');localStorage.setItem('mkty_points','12250');localStorage.setItem('mkty_final_moon_points','12250');for(let n=1;n<=9;n++)localStorage.setItem('mkty_life'+n,'complete');});
const click=s=>p.locator(s).click(),run=ms=>p.clock.runFor(ms),snapshot=()=>p.evaluate(()=>MKTYExpedition.snapshot());let held=new Set();
async function steer(x,y){const next=new Set([...(x>.25?['ArrowRight']:x<-.25?['ArrowLeft']:[]),...(y>.25?['ArrowDown']:y<-.25?['ArrowUp']:[])]);for(const k of held)if(!next.has(k))await p.keyboard.up(k);for(const k of next)if(!held.has(k))await p.keyboard.down(k);held=next;}
async function fly(target){let data=await snapshot(),route=pathTo(data.run,target),i=0,ticks=0;while(i<route.length&&ticks++<1600){data=await snapshot();const r=data.run;assert.equal(r.phase,'flight','Ship lost during a clear plotted route');const node=route[i],d=distance(node,r.ship);if(d<(i===route.length-1?45:29)){i++;continue;}const dx=node.x-r.ship.x,dy=node.y-r.ship.y;await steer(dx/Math.max(Math.abs(dx),Math.abs(dy)),dy/Math.max(Math.abs(dx),Math.abs(dy)));if(r.drones.some(d=>!d.disabled&&distance(d,r.ship)<320)&&r.emp===0&&r.ship.energy>=35)await p.keyboard.press('Space');await run(160);}assert(i===route.length,'Flight timed out');await steer(0,0);await run(700);}
async function interact(id){const a=(await snapshot()).run.points.find(o=>o.id===id);await fly(a);await p.keyboard.down('KeyE');await run(id==='wreck'?4500:3000);await p.keyboard.up('KeyE');assert((await snapshot()).run.points.find(o=>o.id===id).done,'Interaction incomplete: '+id);}
await click('#expeditionEntry');
for(const [index,type]of ['rescue','salvage','survey'].entries()){
  await click('[data-exp-contract="'+type+'"]');await click('[data-exp-tier="'+(index===0?1:2)+'"]');await click('#expLaunch');assert(await p.locator('#expDialog').isVisible());await click('[data-exp-dialog="resume"]');await run(200);const initial=await snapshot();
  if(index===0){
    // Actual pointer capture, boost and cancel must release both axes.
    const box=await p.locator('#expJoystick').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width*.8,box.y+box.height/2);await run(700);await p.mouse.up();await run(900);assert((await snapshot()).run.ship.x>initial.run.ship.x+50);assert(Math.abs((await snapshot()).run.ship.vx)<1);
    await p.keyboard.down('ArrowUp');await run(600);await click('#expPause');const pause=await snapshot();await run(20000);assert.deepEqual((await snapshot()).run,pause.run);await click('[data-exp-dialog="resume"]');await p.keyboard.up('ArrowUp');await run(1000);assert(Math.abs((await snapshot()).run.ship.vy)<1);
    await click('#expScan');assert((await snapshot()).run.scan>0);
    const saved=(await snapshot()).run;await p.reload();await click('#expeditionEntry');await click('#expResume');assert.deepEqual((await snapshot()).run.ship,saved.ship);assert(await p.locator('#expDialog').isVisible());await click('[data-exp-dialog="resume"]');
    await click('#expMap');assert(await p.locator('#expFullMap').isVisible());await click('[data-exp-waypoint="pod-a"]');assert.equal((await snapshot()).run.target,'pod-a');
  }
  if(type==='rescue'){await interact('pod-a');await interact('pod-b');}
  if(type==='salvage'){await interact('relay-a');await interact('relay-b');await interact('wreck');}
  if(type==='survey'){await interact('relay-a');await interact('relay-b');await interact('relay-c');}
  await fly({x:1600,y:2880});await p.keyboard.down('KeyE');await run(120);await p.keyboard.up('KeyE');const end=await snapshot();assert.equal(end.run.phase,'result');assert.equal(end.run.report.success,true);assert.equal(end.profile.wins,index+1);report.journeys.push({type,time:end.run.time,hull:end.run.ship.hull,report:end.run.report});console.log('Journey',JSON.stringify(report.journeys.at(-1)));
  await run(4000);assert.equal((await snapshot()).profile.parts,end.profile.parts);await p.reload();await click('#expeditionEntry');assert.equal((await snapshot()).profile.parts,end.profile.parts);assert(await p.locator('#expDispatch').isVisible());
  if(index===0){await click('[data-exp-buy="hull"]');const upgraded=await snapshot();assert.equal(upgraded.profile.upgrades.hull,1);assert.equal(upgraded.profile.parts,end.profile.parts-80);}
}
assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_final_moon_points')),'12250');
// Workshop/flight in both supported text variants and short / wide / desktop viewports.
for(const lang of ['ru','en'])for(const [width,height]of [[320,480],[390,844],[568,320],[844,390],[1280,800]]){await p.evaluate(l=>localStorage.setItem('mkty_lang',l),lang);await p.setViewportSize({width,height});await p.evaluate(()=>MKTYExpedition.open());const unlocked=await p.locator('[data-exp-tier="3"]').isEnabled();assert(unlocked);await click('#expLaunch');await click('[data-exp-dialog="resume"]');await run(300);const layout=await p.locator('#expFlight').evaluate(e=>({body:document.documentElement.scrollWidth,canvas:e.querySelector('#expViewport').getBoundingClientRect().toJSON(),controls:[...e.querySelectorAll('button')].map(b=>({id:b.id,...b.getBoundingClientRect().toJSON()}))}));assert(layout.body<=width);assert(layout.canvas.height>100);for(const b of layout.controls){assert(b.x>=0&&b.right<=width+1&&b.y>=0&&b.bottom<=height+1,JSON.stringify({width,height,b}));assert(b.width>=43&&b.height>=43,JSON.stringify(b));}report.layouts.push({lang,width,height});await click('#expPause');await click('[data-exp-dialog="hangar"]');await click('#expAbandon');await click('[data-exp-dialog="abandon"]');}
// Malformed run recovery preserves earned workshop progress.
const bank=(await snapshot()).profile.parts;await p.addInitScript(()=>{const x=JSON.parse(localStorage.getItem('mkty_expeditions_v1'));x.run.ship.x='broken';localStorage.setItem('mkty_expeditions_v1',JSON.stringify(x));});await p.reload();await click('#expeditionEntry');assert.equal((await snapshot()).run,null);assert.equal((await snapshot()).profile.parts,bank);
assert.deepEqual(report.errors,[]);assert.deepEqual(report.bad,[]);fs.writeFileSync(out+'/expeditions.json',JSON.stringify(report,null,2));console.log('PASS',report.journeys.length,'actual contract journeys;',report.layouts.length,'layouts; pause, reload, pointer, upgrades and campaign reward isolation');
})().catch(async e=>{report.failure=e.stack;console.error(e);await p?.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/expeditions.json',JSON.stringify(report,null,2));await browser?.close();await new Promise(r=>server.close(r));});
