const {chromium}=require('./pace-hook.cjs'),assert=require('node:assert/strict'),R=require('../expedition-model.js'),fs=require('fs'),http=require('http'),path=require('path');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||'/tmp/mkty-exp-edges';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://local').pathname,f=path.join(root,name==='/'?'index.html':name);fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.css':'text/css','.js':'application/javascript'})[path.extname(f)]||'application/octet-stream'});res.end(e?'':b);});});
let browser,p;const report={errors:[],checks:[]};
(async()=>{await new Promise(r=>server.listen(0,r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});
async function fixture(change){await p?.close();p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.on('pageerror',e=>report.errors.push(e.message));await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));const profile=R.profile(),run=R.create(53,'rescue',1,profile);change(run,profile);await p.addInitScript(data=>{if(!localStorage.getItem('fixture')){localStorage.setItem('mkty_lang','ru');localStorage.setItem('mkty_expeditions_v1',JSON.stringify(data));localStorage.setItem('fixture','yes');}},{version:1,profile,run});await p.clock.install({time:new Date('2026-10-04T12:00Z')});await p.clock.pauseAt(new Date('2026-10-04T12:00Z'));await p.goto('http://localhost:'+server.address().port);await p.click('#expeditionEntry');await p.click('#expResume');await p.click('[data-exp-dialog="resume"]');await p.clock.runFor(160);}
const snap=()=>p.evaluate(()=>MKTYExpedition.snapshot()),time=ms=>p.clock.runFor(ms);
for(const choice of ['repair','strip']){await fixture(r=>{const a=r.points.find(o=>o.kind==='service');Object.assign(r.ship,{x:a.x,y:a.y,hull:30});});await p.keyboard.press('KeyE');assert(await p.locator('[data-exp-dialog="'+choice+'"]').isVisible());await p.click('[data-exp-dialog="'+choice+'"]');const s=await snap();assert(s.run.points.find(o=>o.kind==='service').done);assert.equal(s.run.cargo,choice==='strip'?40:0);assert.equal(s.run.ship.hull,choice==='repair'?75:30);assert(!await p.locator('#expDialog').isVisible());report.checks.push('tender-'+choice);}
await fixture(r=>{const a=r.points.find(o=>o.id==='pod-a');Object.assign(r.ship,{x:a.x,y:a.y});});const button=await p.locator('#expAction').boundingBox();await p.mouse.move(button.x+button.width/2,button.y+button.height/2);await p.mouse.down();await time(550);await p.evaluate(()=>window.dispatchEvent(new Event('blur')));const paused=(await snap()).run;assert(paused.points.find(o=>o.id==='pod-a').work>0);assert(!paused.points.find(o=>o.id==='pod-a').done);await time(15000);assert.deepEqual((await snap()).run,paused);await p.mouse.up();await p.reload();await p.click('#expeditionEntry');await p.click('#expResume');const restored=(await snap()).run;assert.equal(restored.points.find(o=>o.id==='pod-a').work,paused.points.find(o=>o.id==='pod-a').work);await p.click('[data-exp-dialog="resume"]');await time(800);assert.equal((await snap()).run.points.find(o=>o.id==='pod-a').work,paused.points.find(o=>o.id==='pod-a').work);await p.keyboard.down('KeyE');await time(2600);await p.keyboard.up('KeyE');assert((await snap()).run.points.find(o=>o.id==='pod-a').done);assert((await snap()).run.alert>0);report.checks.push('partial-rescue-blur-reload-release');
await fixture(r=>{r.ship.x=450;r.ship.y=700;r.ship.hull=2;r.cargo=60;});await time(800);assert.equal((await snap()).run.phase,'result');assert.equal((await snap()).profile.parts,0);assert(await p.locator('#expDialog').isVisible());await p.keyboard.press('Escape');assert(await p.locator('#expDispatch').isVisible());await p.click('#expLaunch');assert.equal((await snap()).run.ship.hull,100);await p.click('[data-exp-dialog="resume"]');await time(100);assert.equal((await snap()).run.phase,'flight');report.checks.push('radiation-failure-report-escape-new-flight');
await fixture(r=>{r.cargo=85;r.rescued=1;r.points.find(o=>o.id==='pod-a').done=true;});await p.keyboard.press('KeyE');assert(await p.locator('[data-exp-dialog="extract"]').isVisible());await p.click('[data-exp-dialog="extract"]');assert.equal((await snap()).profile.parts,29);assert.equal((await snap()).profile.rescued,1);assert.equal((await snap()).profile.wins,0);await p.reload();await p.click('#expeditionEntry');assert.equal((await snap()).profile.parts,29);report.checks.push('early-return-survivors-partial-reward-no-duplication');
await fixture(r=>{r.type='salvage';const a=r.points.find(o=>o.kind==='wreck');Object.assign(r.ship,{x:a.x,y:a.y});});assert(await p.locator('#expAction').isDisabled());await p.keyboard.down('KeyE');await time(4500);await p.keyboard.up('KeyE');assert(!(await snap()).run.points.find(o=>o.kind==='wreck').done);report.checks.push('black-box-power-gate');
assert.deepEqual(report.errors,[]);console.log(JSON.stringify(report));
})().catch(async e=>{report.failure=e.stack;console.error(e);await p?.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/edges.json',JSON.stringify(report,null,2));await browser?.close();await new Promise(r=>server.close(r));});
