const assert=require('node:assert/strict'),R=require('../expedition-model.js');
const advance=(r,p,input,seconds)=>{for(let t=0;t<seconds;t+=.02)R.step(r,p,input,.02);};
// Settlements must be at the station, require actual objectives and be idempotent.
for(const type of R.TYPES){const p=R.profile(),r=R.create(34,type,1,p);assert.equal(R.finish(r,p,true),null);assert.equal(p.parts,0);for(const o of r.points.filter(o=>R.primary(r,o)))o.done=true;r.ship.x=400;assert.equal(R.finish(r,p,true),null);Object.assign(r.ship,R.BASE);const report=R.finish(r,p,true);assert(report.success);const bank=p.parts;R.finish(r,p,true);assert.equal(p.parts,bank);assert.equal(p.wins,1);const save=R.restore(JSON.parse(JSON.stringify({version:1,profile:p,run:r})));assert.equal(save.profile.parts,bank);assert.equal(save.run.phase,'result');assert.equal(R.finish(save.run,save.profile,true).reward,bank);assert.equal(save.profile.parts,bank);}
// All generated interactions have clear approaches, and saves restore only seeded geometry.
for(let seed=1;seed<=240;seed++){const p=R.profile(),r=R.create(seed,R.TYPES[seed%3],seed%3+1,p);assert(r.rocks.length>50);for(const o of r.points){assert(!r.rocks.some(a=>R.distance(a,o)<180));assert(R.distance(o,R.BASE)>330);}advance(r,p,{x:.2,y:-1},1);const data={version:1,profile:p,run:r},restored=R.restore(JSON.parse(JSON.stringify(data)));assert(restored.run);assert.deepEqual(restored.run.ship,r.ship);assert.deepEqual(restored.run.rocks,r.rocks);assert.deepEqual(restored.run.drones,r.drones);data.run.rocks=[];assert(R.restore(data).run.rocks.length>0);}
let p=R.profile(),r=R.create(52,'salvage',1,p);const wreck=r.points.find(o=>o.kind==='wreck');Object.assign(r.ship,{x:wreck.x,y:wreck.y});r.drones=[];advance(r,p,{action:true},5);assert(!wreck.done);r.points.filter(o=>o.kind==='relay').slice(0,2).forEach(o=>o.done=true);advance(r,p,{action:true},4.2);assert(wreck.done);assert(R.ready(r));assert.equal(r.cargo,65);
// Boost / braking / defense / radar change real simulation state.
p=R.profile();r=R.create(1,'rescue',1,p);advance(r,p,{x:1,boost:true},1);assert(r.ship.x>R.BASE.x+150);assert(r.ship.energy<80);advance(r,p,{},1);assert(Math.abs(r.ship.vx)<1);assert(r.ship.energy>85);r.ship.energy=100;const d=r.drones[0];Object.assign(r.ship,{x:d.x+100,y:d.y});assert(R.action(r,p,'emp'));assert.equal(d.disabled,6);assert.equal(r.ship.energy,65);assert(!R.action(r,p,'emp'));assert(R.action(r,p,'scan'));assert.equal(r.ship.energy,50);assert(r.points.some(o=>o.seen));
// Telegraphs precede real projectiles; pulse removes nearby projectiles.
r=R.create(2,'survey',1,p);Object.assign(r.ship,{x:r.drones[0].x+200,y:r.drones[0].y});r.drones[0].cooldown=0;R.step(r,p,{},.02);assert(r.drones[0].aim>0);assert.equal(r.shots.length,0);advance(r,p,{},1);assert(r.shots.length>0);assert(R.action(r,p,'emp'));assert.equal(r.shots.length,0);
// Optional repair and salvage are mutually exclusive and require proximity.
r=R.create(2,'rescue',1,p);assert(!R.action(r,p,'strip'));const repair=r.points.find(o=>o.kind==='service');Object.assign(r.ship,{x:repair.x,y:repair.y,hull:30});assert(R.action(r,p,'repair'));assert.equal(r.ship.hull,75);assert(!R.action(r,p,'strip'));assert.equal(r.cargo,0);
r=R.create(3,'rescue',1,p);const tender=r.points.find(o=>o.kind==='service');Object.assign(r.ship,{x:tender.x,y:tender.y,hull:30});assert(R.action(r,p,'strip'));assert.equal(r.ship.hull,30);assert.equal(r.cargo,40);assert(!R.action(r,p,'repair'));
// Failure loses carried goods, early docking delivers only a fraction and actual survivors.
p=R.profile();r=R.create(2,'rescue',1,p);r.cargo=100;r.rescued=1;r.ship.x=200;assert.equal(R.finish(r,p,false,true),null);Object.assign(r.ship,R.BASE);R.finish(r,p,false,true);assert.equal(p.parts,35);assert.equal(p.rescued,1);assert.equal(p.wins,0);r=R.create(2,'rescue',1,p);r.cargo=100;r.ship.hull=0;advance(r,p,{},.04);assert.equal(r.phase,'result');assert.equal(p.parts,35);
// Purchase gates, upgrade caps and malformed saves cannot break the next flight.
p.parts=1000;assert(R.buy(p,'hull'));assert.equal(p.parts,920);assert.equal(R.maxHull(p),125);R.buy(p,'hull');R.buy(p,'hull');assert(!R.buy(p,'hull'));assert(!R.buy(p,'bogus'));assert.equal(R.unlocked(p),1);p.wins=1;assert.equal(R.unlocked(p),2);p.wins=3;assert.equal(R.unlocked(p),3);
const data={version:1,profile:p,run:R.create(73,'rescue',1,p)};data.run.ship.energy=NaN;assert.equal(R.restore(data).run,null);assert.equal(R.restore(data).profile.parts,p.parts);data.run=R.create(73,'rescue',1,p);data.run.points[0].work=2;assert.equal(R.restore(data).run,null);assert.deepEqual(R.restore({version:99}).profile,R.profile());
console.log('PASS: 240 seeded sectors, movement, boost, collision rules, telegraphs, pulse, scan, repairs, extraction, settlement, upgrades and save validation');
