const {chromium}=require('./pace-hook.cjs'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),http=require('http'),solve=require('./field-browser-helper.cjs');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||'/tmp/field-ui';fs.mkdirSync(out,{recursive:true});let browser,p;const report={errors:[],chapters:[],layouts:[]};
const server=http.createServer((req,res)=>{const f=path.join(root,new URL(req.url,'http://a').pathname==='/'?'index.html':new URL(req.url,'http://a').pathname);fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[path.extname(f)]||'application/octet-stream'});res.end(e?'':b);});});
(async()=>{await new Promise(r=>server.listen(0,r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(6000);p.on('pageerror',e=>report.errors.push(e.message));await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date(new Date('2026-10-04T21:00Z').getTime()-60000)});await p.clock.pauseAt(new Date('2026-10-04T21:00Z'));await p.goto('http://localhost:'+server.address().port);await p.evaluate(()=>{setLang('ru');for(let n=1;n<=9;n++){localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life'+n+'_awarded','yes');}localStorage.setItem('mkty_points','12250');localStorage.setItem('mkty_final_moon_points','12250');localStorage.setItem('mkty_life1_code_presented','yes');localStorage.setItem('mkty_life3_memory_verified','yes');});
 for(let n=1;n<=9;n++){await p.evaluate(n=>{localStorage.setItem('mkty_legacy_v1',JSON.stringify({version:1,lead:'engineer',airlock:'crew',events:{1:'scan',3:'shield',4:'north',5:'vent',6:'clear',7:'rescue',9:'wait'}}));const s=StoryPlan.fresh(n,100+n,2);localStorage.setItem('mkty_story_plan_'+n+'_v1',JSON.stringify(s));MKTYStory.menu(n);},n);await p.waitForTimeout(100);await p.screenshot({path:out+'/plan-'+n+'.png',fullPage:true});await p.locator('[data-story-step="0"]').click();await p.locator('#fieldResume').click();await p.clock.runFor(1200);await p.screenshot({path:out+'/space-'+n+'.png',fullPage:true});const before=await p.evaluate(()=>MKTYField.snapshot());await p.locator('#fieldPause').click();await p.clock.runFor(5000);assert.deepEqual(await p.evaluate(()=>MKTYField.snapshot()),before);await p.locator('#fieldExit').click();await p.reload();await p.locator('#enterBtn').click();await p.locator('[data-story-step="0"]').click();assert.deepEqual(await p.evaluate(()=>MKTYField.snapshot()),before);await solve(p);assert((await p.evaluate(n=>MKTYStory.read(n),n)).done.includes(0));report.chapters.push({n,complete:true,pauseReload:true});fs.writeFileSync(out+'/field-ui.json',JSON.stringify(report,null,2));
 }
 for(const n of [2,9])for(let stage=1;stage<=4;stage++){await p.evaluate(({n,stage})=>MKTYField.open({chapter:n,id:stage,fieldStage:stage,seed:900+stage,title:['Проверка варианта','Variant review'],save:()=>{},complete:()=>show('chapters'),exit:()=>show('chapters')},null),{n,stage});await solve(p);report.chapters.push({n,variant:stage,complete:true});}
 for(const lang of ['ru','en'])for(const [width,height]of[[320,480],[390,844],[568,320],[844,390]]){await p.evaluate(l=>setLang(l),lang);await p.setViewportSize({width,height});await p.evaluate(()=>MKTYStory.replay(9));await p.locator('[data-story-step="0"]').click();await p.locator('#fieldResume').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.locator('#fieldSubmit').scrollIntoViewIfNeeded();const box=await p.locator('#fieldSubmit').boundingBox();assert(box.height>=42&&box.x>=0&&box.x+box.width<=width+1);report.layouts.push({lang,width,height});if(lang==='ru')await p.screenshot({path:out+`/layout-${width}.png`});await p.locator('#fieldPause').click();await p.locator('#fieldExit').click();}
 assert.deepEqual(report.errors,[]);console.log(JSON.stringify(report));
})().catch(async e=>{report.failure=e.stack;console.error(e);await p?.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/field-ui.json',JSON.stringify(report,null,2));await browser?.close();server.close();});
