const {chromium}=require('./pace-hook.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),R=require('../mission-rules.js');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'mkty-ops-edges-'));fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[path.extname(file)]||'application/octet-stream'});res.end(data);});});
let browser,p;const report={errors:[],layouts:0,oldProfiles:[],replayCore:[]};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(6000);p.on('pageerror',e=>report.errors.push(e.message));await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date(new Date('2026-10-04T15:00Z').getTime()-60000)});await p.clock.pauseAt(new Date('2026-10-04T15:00Z'));await p.addInitScript(require('./story-finale-fixture.cjs'));await p.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});
const click=s=>p.locator(s).click(),cp=n=>p.evaluate(n=>JSON.parse(localStorage.getItem('mkty_operations_'+n+'_v1')),n);
await p.evaluate(()=>{setLang('ru');for(let n=1;n<=9;n++){localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life'+n+'_awarded','yes');}localStorage.setItem('mkty_points','12250');localStorage.setItem('mkty_final_moon_points','12250');localStorage.setItem('mkty_life3_memory_verified','yes');localStorage.setItem('mkty_life9_coordinates','41.257,68.014');show('chapters');});
for(let n=4;n<=9;n++){await click('[data-chapter="'+n+'"]');assert.equal(await p.locator('.screen.active').getAttribute('id'),'operationsDeck');assert.equal((await cp(n)).round,0);report.oldProfiles.push(n);await click('#opsMenu');await click('#opsExit');}
const base=n=>({version:1,n,seed:4821,round:2,phase:'planning',confirmed:false,actions:10,errors:0,hints:0,seconds:15,input:R.initial(R.board(n,2,4821))});
async function setup(data){await p.evaluate(data=>{show('chapters');localStorage.setItem('mkty_operations_'+data.n+'_v1',JSON.stringify(data));},data);await click('[data-chapter="'+data.n+'"]');}
for(let n=4;n<=9;n++)for(const solved of [false,true]){
const v=base(n),b=R.board(n,2,v.seed),input=v.input;
if(solved){if(n===4)input.path=b.path;if(n===5)b.path.forEach(i=>input.turns[i]=0);if(n===6)input.tiles=b.target;if(n===7)for(const i of R.solveShield(b,input)){R.toggle(input.lamps,i,b.n);input.history.push(i);}if(n===8)input.history=[b.secret];if(n===9)input.order=R.solveSystems(b,input);v.confirmed=true;}
for(const lang of ['ru','en']){await p.evaluate(lang=>setLang(lang),lang);await setup(v);for(const [width,height] of [[320,480],[390,844],[568,320],[844,390]]){await p.setViewportSize({width,height});await p.waitForTimeout(30);const rects=await p.locator('.ops-footer button').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({rect:e.getBoundingClientRect().toJSON(),display:getComputedStyle(e).display,visible:getComputedStyle(e).visibility})));for(const {rect,visible} of rects)assert(rect.top>=0&&rect.bottom<=height+1&&rect.left>=0&&rect.right<=width+1&&visible==='visible',JSON.stringify({n,solved,lang,width,height,rect,visible}));assert(await p.locator('#opsSubmit').isVisible());assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);report.layouts++;if(n===8&&solved&&lang==='ru'&&width===390){await p.waitForTimeout(750);await p.screenshot({path:out+'/cipher-complete.png'});}}
}}
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>setLang('ru'));
// Partial interaction on every board survives reload, with hints optional and persisted.
for(let n=4;n<=9;n++){const v=base(n),b=R.board(n,2,v.seed);await setup(v);await click('#opsHint');assert.equal((await cp(n)).hints,1);if(n===5){const hint=await p.locator('.ops-pipes .ops-tile.hinted').evaluate(el=>({outline:getComputedStyle(el).outlineStyle,width:getComputedStyle(el).outlineWidth,badge:getComputedStyle(el,'::after').content}));assert.equal(hint.outline,'solid');assert.equal(hint.width,'3px');assert.equal(hint.badge,'"?"');}let i=n===4?b.path[1]:n===9?R.solveSystems(b,v.input)[0]:0;await click('[data-op-cell="'+i+'"]');if(n===8)await click('[data-op-glyph="2"]');const before=await cp(n);await p.reload();await click('#enterBtn');assert.deepEqual((await cp(n)).input,before.input);assert.equal((await cp(n)).hints,1);}
// Exhaust the key's attempts; resetting affects only the current operation.
await setup(base(8));const b=R.board(8,2,4821),wrong=[0,1,2,3,4];if(wrong.every((v,i)=>v===b.secret[i]))[wrong[0],wrong[1]]=[wrong[1],wrong[0]];for(let attempt=0;attempt<8;attempt++){for(let i=0;i<5;i++){await click('[data-op-cell="'+i+'"]');await click('[data-op-glyph="'+wrong[i]+'"]');}await click('#opsSubmit');}assert.equal((await cp(8)).confirmed,false);assert.equal((await cp(8)).round,2);await click('#opsReset');assert.equal((await cp(8)).round,2);assert.equal((await cp(8)).input.history.length,0);assert.notEqual((await cp(8)).seed,4821);report.cipherFailureRecovery=true;
// Finished profiles must start the actual live stage, save it and restore it (never instant-complete).
for(let n=4;n<=9;n++){await setup({...base(n),round:3,phase:'core',input:null});assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission'+n);assert(await p.locator('#life'+n+'Complete').isHidden());await p.clock.runFor(1000);if(n===5){await click('#reactorHelp5');await click('#reactorExit5');}else if(n===6){await click('#liftoffHelp6');await click('#lfExit6');}else{await click('#mission'+n+' .chapter-menu');await click('#guideMissions');}await p.reload();await click('#enterBtn');assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission'+n);assert(await p.locator('#life'+n+'Complete').isHidden());report.replayCore.push(n);}
// Replay the final input of chapters 8 and 9; earned points and chapter 9's coordinates stay intact.
await p.evaluate(()=>{show('chapters');localStorage.setItem('mkty_campaign_checkpoint_8',JSON.stringify({version:1,stage:'pulse',frequency:40,phase:50,targetFrequency:40,targetPhase:50,round:3,pattern:[0,1,2,0,1,2],input:[0,1,2,0,1],ready:true}));});await click('[data-chapter="8"]');await click('#guideResume');await click('[data-pulse8="2"]');assert(await p.locator('#life8Complete').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_life9_coordinates')),'41.257,68.014');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');
await p.evaluate(()=>{show('chapters');localStorage.setItem('mkty_campaign_checkpoint_9',JSON.stringify({version:1,stage:'transmit',target:50,dial:50,latitude:'41.257',longitude:'68.014',round:3,health:100,power:65,sync:[0,1,2,0,1,2],syncInput:[],syncReady:false,final:[0,1,2,3,0,1],finalInput:[0,1,2,3,0],finalReady:true}));});await click('[data-chapter="9"]');await click('#guideResume');await click('[data-final9="1"]');await p.clock.runFor(1000);assert(await p.locator('#life9Complete').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_final_moon_points')),'12250');report.duplicateRewardsAndCoordinateChangesPrevented=true;
assert.deepEqual(report.errors,[]);fs.writeFileSync(out+'/operations-edges.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(async e=>{report.failure=e.stack;fs.writeFileSync(out+'/operations-edges.json',JSON.stringify(report,null,2));await p?.screenshot({path:out+'/failure.png'}).catch(()=>{});console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
