// Full chapters 4–9: solve all 18 new operations, then play the existing live missions.
const {chromium}=require('./pace-hook.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),R=require('../mission-rules.js');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'mkty-ops-'));fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png'})[path.extname(file)]||'application/octet-stream'});res.end(data);});});
let browser,p;const report={errors:[],bad:[],chapters:[],layouts:[]};
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(20000);p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.url().includes('127.0.0.1')&&r.status()>=400)report.bad.push(r.url());});await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date('2026-10-04T12:00Z')});await p.clock.pauseAt(new Date('2026-10-04T12:00Z'));await p.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});
 const click=s=>p.locator(s).click(),run=ms=>p.clock.runFor(ms),val=async id=>parseFloat(await p.locator('#'+id).textContent()),cp=n=>p.evaluate(n=>JSON.parse(localStorage.getItem('mkty_operations_'+n+'_v1')),n);
 const slider=(id,v)=>p.locator('#'+id).fill(String(v));let held=null;
 async function hold(id){if(id===held)return;if(held)await p.mouse.up();held=null;if(id){const b=await p.locator('#'+id).boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();held=id;}}
 async function reload(){await p.reload();await click('#enterBtn');}
 async function layout(n,round){for(const [width,height] of [[320,480],[390,844],[568,320],[844,390]]){await p.setViewportSize({width,height});const sizes=await p.locator('#operationsDeck').evaluate(e=>({width:document.documentElement.scrollWidth,footer:e.querySelector('footer').getBoundingClientRect().toJSON(),buttons:[...e.querySelectorAll('footer button')].filter(b=>b.getClientRects().length).map(b=>b.getBoundingClientRect().toJSON()),content:e.querySelector('.ops-content').getBoundingClientRect().toJSON()}));assert(sizes.width<=width,JSON.stringify(sizes));assert(sizes.content.height>70);for(const r of sizes.buttons)assert(r.y>=0&&r.bottom<=height+1&&r.x>=0&&r.right<=width+1&&r.height>=40,JSON.stringify({width,height,r}));report.layouts.push({n,round,width,height});}await p.setViewportSize({width:390,height:844});}
 await p.evaluate(()=>{setLang('ru');for(let n=1;n<=9;n++){const s=StoryPlan.fresh(n,n,1);s.done=[0,1,2,3,4,5,6,7];s.phase='core';localStorage.setItem('mkty_story_plan_'+n+'_v1',JSON.stringify(s));}for(let n=1;n<=3;n++){localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life'+n+'_awarded','yes');}localStorage.setItem('mkty_points','1750');localStorage.setItem('mkty_life1_code_presented','yes');localStorage.setItem('mkty_life3_memory_verified','yes');show('chapters');});
 function permutations(size){let out=[];function go(a){if(a.length===size){out.push(a);return;}for(let i=0;i<6;i++)if(!a.includes(i))go([...a,i]);}go([]);return out;}
 for(let n=4;n<=9;n++){
  await click('[data-chapter="'+n+'"]');assert.equal(await p.locator('.screen.active').getAttribute('id'),'operationsDeck');const entry={n,operations:[],core:false};report.chapters.push(entry);
  for(let round=0;round<3;round++){
   const data=await cp(n),b=R.board(n,round,data.seed);assert.equal(data.round,round);await layout(n,round);
   // A wrong confirmation never advances an operation.
   await click('#opsSubmit');assert.equal((await cp(n)).round,round);assert.equal((await cp(n)).confirmed,false);
   if(round===0){await click('#opsMenu');const before=await cp(n);await run(5000);assert.deepEqual(await cp(n),before);await click('#opsResume');await reload();assert.deepEqual((await cp(n)).input,before.input);}
   if(n===4){for(const i of b.path.slice(1))await click('[data-op-cell="'+i+'"]');}
   if(n===5){for(const i of b.path)for(let j=0;j<(4-b.turns[i])%4;j++)await click('[data-op-cell="'+i+'"]');}
   if(n===6){let tiles=b.tiles.slice();for(let i=0;i<tiles.length;i++)if(tiles[i]!==b.target[i]){const j=tiles.indexOf(b.target[i]);await click('[data-op-cell="'+i+'"]');await click('[data-op-cell="'+j+'"]');[tiles[i],tiles[j]]=[tiles[j],tiles[i]];}}
   if(n===7){for(const i of R.solveShield(b,R.initial(b)))await click('[data-op-cell="'+i+'"]');}
   if(n===8){let candidates=permutations(b.size);for(let attempt=0;attempt<b.limit;attempt++){
    let guess=candidates[0],best=Infinity;for(const trial of candidates){const groups=new Map();for(const candidate of candidates){const f=R.feedback(trial,candidate),k=f.exact+','+f.near;groups.set(k,(groups.get(k)||0)+1);}const worst=Math.max(...groups.values());if(worst<best){best=worst;guess=trial;}}
    for(let i=0;i<b.size;i++){await click('[data-op-cell="'+i+'"]');await click('[data-op-glyph="'+guess[i]+'"]');}await click('#opsSubmit');const result=await p.locator('.ops-history li').last().evaluate(e=>({exact:Number(e.dataset.exact),near:Number(e.dataset.near)}));if(result.exact===b.size)break;candidates=candidates.filter(c=>{const f=R.feedback(guess,c);return f.exact===result.exact&&f.near===result.near;});assert(candidates.length);
   }}
   if(n===9){if(round===0){await click('[data-op-cell="5"]');assert((await p.locator('#opsStatus').textContent()).includes('Ресурсов'));await click('#opsUndo');}for(const i of R.solveSystems(b,R.initial(b)))await click('[data-op-cell="'+i+'"]');}
   if(n!==8)await click('#opsSubmit');assert.equal((await cp(n)).confirmed,true);const solved=await cp(n);await reload();assert.equal((await cp(n)).confirmed,true);assert.equal((await cp(n)).actions,solved.actions);
   if(round===2){await p.waitForTimeout(700);await p.screenshot({path:out+'/operations-'+n+'.png'});}entry.operations.push({round:round+1,actions:solved.actions,hints:solved.hints});await click('#opsSubmit');
  }
  assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission'+n);assert.equal((await cp(n)).phase,'core');
  if(n===4){await slider('thrustDial',100);for(let i=0;i<240;i++){if(await p.locator('#life4Complete').isVisible())break;const alt=await val('altitude'),v=await val('velocity');await hold(alt<460&&v>11?'burnBtn':null);await run(300);}await hold(null);}
  if(n===5){for(let i=0;i<3;i++){await hold('chargeCore5');await run(8400);await hold(null);if(i<2){await hold('coolCore5');await run(2700);await hold(null);}}assert.equal(await p.locator('#mission5').getAttribute('data-reactor-phase'),'balance');await slider('coolantFlow5',50);await slider('fieldTrim5',50);await run(4000);await slider('fieldTrim5',Math.round(50+(50-await val('stabilityRead5'))/.8));await run(7000);await click('#stabilizeBtn');await click('#igniteBtn');for(let pulse=0;pulse<3;pulse++){for(let i=0;i<110;i++){const hit=await p.evaluate(()=>Math.abs(parseFloat($('reactorPulseNeedle5').style.left)-parseFloat($('reactorPulseWindow5').style.left)-10)<2.5);if(hit){await click('#igniteBtn');break;}await run(50);}await run(750);}await run(2700);}
  if(n===6){await click('#lfBegin6');const order=await p.locator('#lfOrder6 span').allTextContents();for(const name of order.slice(0,2))await click('[data-lf-system="'+name+'"]');const fault=await p.locator('#lfFaultTitle6').textContent();await click('[data-lf-response="'+(/PRESSURE|ДАВЛЕНИЕ/.test(fault)?'vent':/DESYNC|СИНХРОНИЗАЦИИ/.test(fault)?'reset':'bypass')+'"]');for(const name of order.slice(2))await click('[data-lf-system="'+name+'"]');await slider('lfThrottle6',62);await hold('lfIgnite6');await run(3100);await hold(null);await run(3100);for(let i=0;i<430;i++){if(await p.locator('#mission6').getAttribute('data-flight-phase')!=='flight')break;const position=await p.locator('#lfPosition6').evaluate(e=>parseFloat(e.style.left)),target=await p.locator('#lfTarget6').evaluate(e=>parseFloat(e.style.left));await hold(target-position>1?'lfRight6':position-target>1?'lfLeft6':null);await run(250);}await hold(null);assert.equal(await p.locator('#mission6').getAttribute('data-flight-phase'),'orbit');await run(3200);}
  if(n===7){await click('#v7Begin');for(let i=0;i<430;i++){if(await p.locator('#life7Complete').isVisible())break;assert.notEqual(await p.locator('#mission7').getAttribute('data-phase'),'abort');const g=await p.locator('.v7-warnings span').evaluateAll(es=>({lane:es.findIndex(e=>e.classList.contains('selected')),safe:es.map((e,i)=>e.classList.contains('danger')?-1:i).filter(i=>i>=0)}));if(!g.safe.includes(g.lane)&&g.safe.length){const to=g.safe.reduce((a,b)=>Math.abs(b-g.lane)<Math.abs(a-g.lane)?b:a);for(let j=0;j<Math.abs(to-g.lane);j++)await p.keyboard.press(to<g.lane?'ArrowLeft':'ArrowRight');}await run(200);}}
  if(n===8){for(let v=20;v<=80;v++){await slider('freq8',v);if(await p.locator('#strengthFill8').evaluate(e=>parseFloat(e.style.width))>=96)break;}await click('#lockFreq8');await slider('phase8',await p.locator('.phase-scope8').evaluate(e=>parseFloat(e.style.getPropertyValue('--phase-target'))));await click('#lockPhase8');await run(2850);for(let round=1;round<=3;round++){const seq=await p.locator('#pulseDisplay8 span').allTextContents();await run(3000);for(const s of seq)await click('[data-pulse8="'+['◯','△','◇'].indexOf(s)+'"]');if(round<3)await run(650);}}
  if(n===9){const parts=(await p.evaluate(()=>localStorage.getItem('mkty_life9_coordinates'))).split(',');await p.locator('#coordLat9').fill(parts[0].replace('.',','));await p.locator('#coordLon9').fill(parts[1].replace('.',','));await click('#verifyCoords9');await slider('navDial9',await p.locator('.corridor-meter9').evaluate(e=>parseFloat(e.style.getPropertyValue('--corridor-target'))));await click('#lockNav9');for(let round=1;round<=3;round++){const seq=await p.locator('#syncSequence9 span').allTextContents();await run(2700);for(const s of seq)await click('[data-sync9="'+['A','B','C'].indexOf(s)+'"]');if(round<3)await run(550);}const seq=await p.locator('#finalCode9 span').allTextContents();await run(2700);for(const s of seq)await click('[data-final9="'+['▲','●','◆','■'].indexOf(s)+'"]');await run(1000);}
  assert(await p.locator('#life'+n+'Complete').isVisible(),'Chapter '+n+' did not finish');assert.equal((await cp(n)).phase,'complete');entry.core=true;entry.points=await p.evaluate(()=>localStorage.getItem('mkty_points'));console.log('Chapter',n,JSON.stringify(entry));fs.writeFileSync(out+'/operations.json',JSON.stringify(report,null,2));await click('#life'+n+'ReturnBtn');await click('#missionsBtn');
 }
 assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_final_moon_points')),'12250');
 // Completed chapters expose explicit replays. Existing achievements are not removed.
 for(let n=4;n<=9;n++){await click('[data-chapter="'+n+'"]');if(await p.locator('#storyPlan').isVisible())await click('#storyCore');assert(await p.locator('#life'+n+'Complete').isVisible());await click('#life'+n+'Complete .ops-replay');assert.equal(await p.locator('.screen.active').getAttribute('id'),'operationsDeck');assert.equal((await cp(n)).round,0);assert.equal(await p.evaluate(n=>localStorage.getItem('mkty_life'+n),n),'complete');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');await reload();assert.equal(await p.locator('.screen.active').getAttribute('id'),'operationsDeck');await click('#opsMenu');await click('#opsExit');}
 report.replayPreservesAchievements=true;report.finalBalance=12250;assert.deepEqual(report.errors,[]);assert.deepEqual(report.bad,[]);fs.writeFileSync(out+'/operations.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,layouts:report.layouts.length}));
})().catch(async e=>{report.failure=e.stack;fs.writeFileSync(out+'/operations.json',JSON.stringify(report,null,2));await p?.screenshot({path:out+'/failure.png'}).catch(()=>{});console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve));});
