// Run with Node.js and Playwright installed; see README.md. No account or live rewards are used.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'moonkatty-qa-'));
fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.mp4':'video/mp4'};
const server=http.createServer((req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(data);});}catch{res.writeHead(400).end();}});
let browser;const report={errors:[],bad:[]};
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
 const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(6000);
 p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.url().includes('127.0.0.1')&&r.status()>=400)report.bad.push(r.url());});
 await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date('2026-10-04T12:00Z')});await p.clock.pauseAt(new Date('2026-10-04T12:00Z'));
 await p.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});
 const click=s=>p.locator(s).click(),run=ms=>p.clock.runFor(ms),cp=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('mkty_campaign_checkpoint_7')));
 await p.evaluate(()=>{setLang('en');for(let n=1;n<=6;n++){localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life'+n+'_awarded','yes');}localStorage.setItem('mkty_points','5500');localStorage.setItem('mkty_current_chapter','6');localStorage.setItem('mkty_life1_code_presented','yes');localStorage.setItem('mkty_life3_memory_verified','yes');show('home');});
 await click('#enterBtn');assert.equal(await p.locator('#mission7').getAttribute('data-phase'),'briefing');await run(10000);assert.equal(await p.locator('#distance7').textContent(),'0');await click('#v7Begin');
 let pausedOnce=false,checkpoints=new Set();
 for(let i=0;i<430;i++){
  const state=await p.locator('#mission7').getAttribute('data-phase');if(state==='complete')break;assert.notEqual(state,'abort','Autopilot must find a safe route using visible warnings');
  const guidance=await p.locator('.v7-warnings span').evaluateAll(es=>({lane:es.findIndex(e=>e.classList.contains('selected')),safe:es.map((e,i)=>e.classList.contains('danger')?-1:i).filter(i=>i>=0)}));
  if(!guidance.safe.includes(guidance.lane)&&guidance.safe.length){const to=guidance.safe.reduce((a,b)=>Math.abs(b-guidance.lane)<Math.abs(a-guidance.lane)?b:a);for(let j=0;j<Math.abs(to-guidance.lane);j++)await p.keyboard.press(to<guidance.lane?'ArrowLeft':'ArrowRight');}
  await run(200);checkpoints.add(await p.locator('.v7-route .done').count());
  if(!pausedOnce&&Number(await p.locator('#distance7').textContent())>=13){
   await click('#mission7 .chapter-menu');const before=await cp(),positions=await p.locator('.asteroid7').evaluateAll(es=>es.map(e=>e.style.transform));assert.equal(before.version,2);
   await run(5000);assert.deepEqual(await cp(),before);assert.deepEqual(await p.locator('.asteroid7').evaluateAll(es=>es.map(e=>e.style.transform)),positions);
   await p.reload();await click('#enterBtn');assert(await p.locator('#chapterGuide').isVisible());assert.deepEqual((await cp()).rocks,before.rocks);assert.equal((await cp()).distance,before.distance);assert.deepEqual(await p.locator('.asteroid7').evaluateAll(es=>es.map(e=>e.style.transform)),positions);await click('#guideResume');pausedOnce=true;
  }
 }
 assert(await p.locator('#life7Complete').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'7250');assert.equal(await p.locator('#hull7').textContent(),'100');assert(checkpoints.has(1)&&checkpoints.has(2)&&checkpoints.has(3));
 report.fullFlight={hull:100,points:7250,sectors:3,pauseReload:true,evaded:Number(await p.locator('#v7ReportEvades').textContent())};assert(report.fullFlight.evaded>10);await p.screenshot({path:out+'/void7-complete.png'});
 await click('#life7ReturnBtn');await click('#missionsBtn');await click('[data-chapter="7"]');assert(await p.locator('#life7Complete').isVisible());await run(5000);assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'7250');await click('#continueLife8Btn');await click('#life8SkipBtn');assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission8');report.completionReviewAndChapter8=true;
 // Deterministic initial checkpoints exercise collisions, recovery and migration; flight above uses only actual controls.
 const base={version:2,phase:'flight',lane:1,x:.5,hull:50,shields:1,distance:40,shieldActive:false,rocks:[],nextWave:4,seed:12345,lastSafe:1,elapsed:28.8,timeKnown:true,attempts:0,evaded:5,blocked:0,hits:0,phaseTime:0,grace:0};
 async function setup(v){await p.evaluate(v=>{show('home');localStorage.removeItem('mkty_life7');localStorage.removeItem('mkty_life7_awarded');localStorage.removeItem('mkty_void7_report_v2');localStorage.setItem('mkty_current_chapter','7');localStorage.setItem('mkty_campaign_checkpoint_7',JSON.stringify(v));MKTYCampaign.render();},v);await click('#enterBtn');}
 const rock={lane:1,big:true,age:2.15,duration:3,rotation:12,spin:20};
 await setup({...base,rocks:[rock]});await click('#guideResume');await click('#shieldBtn');await click('#mission7 .chapter-menu');assert.equal((await cp()).shieldActive,true);assert.equal((await cp()).shields,0);await p.reload();await click('#enterBtn');assert(await p.locator('#chapterGuide').isVisible());assert.equal(await p.locator('#shieldBtn').getAttribute('aria-pressed'),'true');await click('#guideResume');await run(650);await click('#mission7 .chapter-menu');const protectedState=await cp();assert.equal(protectedState.hull,50);assert.equal(protectedState.blocked,1);assert.equal(protectedState.shieldActive,false);assert.equal(protectedState.shields,0);report.shieldImpactAndArmedReload=true;
 await click('#guideMissions');await setup({...base,hull:18,shields:0,rocks:[{...rock,big:false}]});await click('#guideResume');await run(650);assert(await p.locator('#v7Abort').isVisible());const failure=await cp();assert.equal(failure.hull,0);await run(5000);assert.equal((await cp()).elapsed,failure.elapsed);await click('#v7Retry');await click('#mission7 .chapter-menu');const retried=await cp();assert.equal(retried.hull,100);assert.equal(retried.shields,3);assert.equal(retried.distance,100/3);assert.equal(retried.attempts,1);await p.reload();await click('#enterBtn');assert(await p.locator('#chapterGuide').isVisible());assert.equal((await cp()).distance,100/3);report.failedSectorRetryAndReload=true;
 await click('#guideMissions');await setup({version:1,lane:2,hull:46,shields:0,distance:57.8,shieldActive:true,rocks:[{lane:0,big:true,duration:1.4,progress:.8}]});assert(await p.locator('#chapterGuide').isVisible());const migrated=await cp();assert.equal(migrated.version,2);assert.equal(migrated.hull,46);assert.equal(migrated.shields,0);assert.equal(migrated.distance,57.8);assert.equal(migrated.lane,2);assert.equal(migrated.shieldActive,true);assert.equal(migrated.timeKnown,false);report.legacySaveMigration=true;
 await click('#guideMissions');await setup({...base,phase:'flight',hull:0});assert(await p.locator('#v7Brief').isVisible());assert.equal(await p.locator('#hull7').textContent(),'100');report.corruptCheckpointFallback=true;
 await setup({...base,hull:100,shields:3,nextWave:4});await click('#guideResume');await p.keyboard.down('ArrowRight');await run(400);await p.keyboard.up('ArrowRight');assert.equal(await p.locator('.v7-warnings .selected').getAttribute('data-v7-lane'),'2');
 const left=await p.locator('#voidLeft').boundingBox();await p.mouse.move(left.x+left.width/2,left.y+left.height/2);await p.mouse.down();await run(800);await p.mouse.up();assert.equal(await p.locator('.v7-warnings .selected').getAttribute('data-v7-lane'),'0');await run(150);const box=await p.locator('#voidWorld7').boundingBox();await p.mouse.move(box.x+50,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+130,box.y+box.height/2,{steps:3});await p.mouse.up();assert.equal(await p.locator('.v7-warnings .selected').getAttribute('data-v7-lane'),'1');await p.keyboard.press('Space');assert.equal(await p.locator('#shieldBtn').getAttribute('aria-pressed'),'true');report.keyboardHoldSwipeAndSpace=true;
 await p.keyboard.press('ArrowRight');await p.keyboard.down('ArrowLeft');await p.evaluate(()=>window.dispatchEvent(new Event('blur')));assert(await p.locator('#chapterGuide').isVisible());const blurred=await cp();await run(1000);assert.deepEqual(await cp(),blurred);await click('#guideResume');await run(600);assert.equal(await p.locator('.v7-warnings .selected').getAttribute('data-v7-lane'),'1');await p.keyboard.up('ArrowLeft');report.blurPausesAndReleasesHeldInput=true;
 await click('#mission7 .chapter-menu');await click('#guideMissions');const exited=await cp();await run(8000);assert.deepEqual(await cp(),exited);assert.equal(await p.locator('.asteroid7').count(),0);report.exitStopsSimulation=true;
 // The dense brief and result panels, active controls and Russian copy must all fit.
 report.layouts=[];
 for(const [width,height] of [[320,480],[320,568],[375,667],[390,844],[430,932],[844,390],[667,375],[568,320],[1024,768]]){
  await p.setViewportSize({width,height});for(const lang of ['en','ru']){await p.evaluate(lang=>setLang(lang),lang);for(const phase of ['briefing','flight','complete']){
   await p.evaluate(({v,phase})=>{show('home');localStorage.removeItem('mkty_life7');localStorage.setItem('mkty_current_chapter','7');if(phase==='complete'){localStorage.setItem('mkty_life7','complete');localStorage.setItem('mkty_void7_report_v2',JSON.stringify({version:2,time:72,hull:100,evaded:23}));}localStorage.setItem('mkty_campaign_checkpoint_7',JSON.stringify({...v,phase:phase==='complete'?'briefing':phase,distance:phase==='briefing'?0:v.distance,hull:phase==='briefing'?100:v.hull,shields:phase==='briefing'?3:v.shields}));MKTYCampaign.render();},{v:base,phase});if(phase==='complete'){await click('#missionsBtn');await click('[data-chapter="7"]');}else await click('#enterBtn');if(await p.locator('#chapterGuide').isVisible())await click('#guideResume');assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission7');assert.equal(await p.locator('#mission7').getAttribute('data-phase'),phase);
   const layout=await p.locator('#mission7').evaluate(e=>({scroll:e.scrollHeight,height:e.clientHeight,width:document.documentElement.scrollWidth,buttons:[...e.querySelectorAll('button')].filter(b=>b.getClientRects().length&&!b.closest('[hidden]')).map(b=>({id:b.id,rect:b.getBoundingClientRect().toJSON()}))}));assert(layout.scroll<=layout.height+1,JSON.stringify({width,height,lang,phase,layout}));assert(layout.width<=width);for(const b of layout.buttons){assert(b.rect.y>=-1&&b.rect.bottom<=height+1&&b.rect.x>=-1&&b.rect.right<=width+1,JSON.stringify({width,height,lang,phase,button:b}));assert(b.rect.height>=40,JSON.stringify(b));}
   if(lang==='ru'&&((width===390&&phase==='briefing')||(width===320&&phase==='complete')||(width===844&&phase==='flight'))){await p.waitForTimeout(700);await p.screenshot({path:out+`/void7-${phase}-${width}x${height}-${lang}.png`});}
   report.layouts.push({width,height,lang,phase,fit:true});
  }}
 }
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.bad,[]);fs.writeFileSync(out+'/void7.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,layouts:report.layouts.length}));
})().catch(e=>{report.failure=e.stack;fs.writeFileSync(out+'/void7.json',JSON.stringify(report,null,2));console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve));});
