// Run with Node.js and Playwright installed; see README.md. No account or live rewards are used.
const {chromium}=require('./pace-hook.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'moonkatty-qa-'));
fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.mp4':'video/mp4'};
const server=http.createServer((req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(data);});}catch{res.writeHead(400).end();}});
let browser;const report={errors:[],bad:[],warnings:[]};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.url().includes('127.0.0.1')&&r.status()>=400)report.bad.push(r.url());});await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date(new Date('2026-10-04T15:00Z').getTime()-60000)});await p.clock.pauseAt(new Date('2026-10-04T15:00Z'));await p.addInitScript(require('./story-finale-fixture.cjs'));await p.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});const click=s=>p.locator(s).click(),run=t=>p.clock.runFor(t);
await p.evaluate(()=>{setLang('ru');for(let n=7;n<=9;n++)localStorage.setItem('mkty_operations_'+n+'_v1',JSON.stringify({version:1,n,seed:1,round:3,phase:'core',input:null,confirmed:false,actions:50,hints:0,errors:0,seconds:120}));for(let n=1;n<=6;n++)localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life3_memory_verified','yes');localStorage.setItem('mkty_current_chapter','7');show('home');});
const base={version:2,phase:'flight',lane:0,x:.22,hull:100,shields:2,distance:40,shieldActive:true,nextWave:4,seed:12345,lastSafe:0,elapsed:28.8,timeKnown:true,attempts:0,evaded:5,blocked:0,hits:0,phaseTime:0,grace:0,rocks:[{lane:1,big:true,age:2.625,duration:3.5,rotation:12,spin:20}]};
for(const [width,height] of [[390,844],[320,480],[844,390]]){await p.setViewportSize({width,height});await p.evaluate(v=>{show('home');localStorage.setItem('mkty_campaign_checkpoint_7',JSON.stringify(v));MKTYCampaign.render();},base);await click('#enterBtn');assert(await p.locator('#chapterGuide').isVisible());assert(await p.locator('[data-v7-lane="1"]').evaluate(e=>e.classList.contains('danger')));assert(await p.locator('[data-v7-radar="1"]').evaluate(e=>e.classList.contains('danger')));await click('#guideResume');await run(64);assert(await p.locator('[data-v7-lane="1"]').evaluate(e=>e.classList.contains('danger')));await run(400);assert.equal(await p.locator('[data-v7-lane="1"]').evaluate(e=>e.classList.contains('danger')),false);assert.equal(await p.locator('[data-v7-radar="1"]').evaluate(e=>e.classList.contains('danger')),false);assert.equal(await p.locator('#hull7').textContent(),'100');report.warnings.push({width,height,warningPersistsThroughHullAndClearsAfterPass:true});}
await p.setViewportSize({width:390,height:844});await p.evaluate(v=>{show('home');localStorage.setItem('mkty_campaign_checkpoint_7',JSON.stringify({...v,lane:1,x:.5,rocks:[{...v.rocks[0],age:1.7}]}));MKTYCampaign.render();},base);await click('#enterBtn');await click('#guideResume');await run(150);await p.waitForTimeout(700);await p.screenshot({path:out+'/shield-and-asteroid.png'});await click('#mission7 .chapter-menu');const before=await p.evaluate(()=>({distance:document.getElementById('distance7').textContent,environment:document.querySelector('.v7-environment').style.transform,mesh:document.getElementById('shieldBubble7').style.getPropertyValue('--shield-angle'),canvas:document.getElementById('voidCanvas7').toDataURL(),rocks:[...document.querySelectorAll('.asteroid7')].map(e=>e.style.transform)}));await run(5000);const after=await p.evaluate(()=>({distance:document.getElementById('distance7').textContent,environment:document.querySelector('.v7-environment').style.transform,mesh:document.getElementById('shieldBubble7').style.getPropertyValue('--shield-angle'),canvas:document.getElementById('voidCanvas7').toDataURL(),rocks:[...document.querySelectorAll('.asteroid7')].map(e=>e.style.transform)}));assert.deepEqual(after,before);report.pauseFreezesAllMovingLayers=true;
await click('#guideResume');await run(250);assert.notEqual(await p.locator('.v7-environment').getAttribute('style'),'');const x=await p.locator('.asteroid7').first().getAttribute('style');await p.emulateMedia({reducedMotion:'reduce'});await run(100);assert.equal(await p.locator('.v7-environment').evaluate(e=>e.style.transform),'none');assert.equal(await p.locator('#shieldBubble7').evaluate(e=>e.style.getPropertyValue('--shield-angle')),'0deg');assert.notEqual(await p.locator('.asteroid7').first().getAttribute('style'),x);report.reducedMotionKeepsFlightReadable=true;
await p.emulateMedia({reducedMotion:'no-preference'});await run(450);await click('#mission7 .chapter-menu');const impact=await p.evaluate(()=>JSON.parse(localStorage.getItem('mkty_campaign_checkpoint_7')));assert.equal(impact.hull,100);assert.equal(impact.blocked,1);assert.equal(impact.shieldActive,false);report.newLargeRockShieldCollision=true;await click('#guideMissions');await p.evaluate(v=>{localStorage.setItem('mkty_campaign_checkpoint_7',JSON.stringify({...v,phase:'approach',distance:100,shieldActive:false,rocks:[],phaseTime:0}));},base);await click('[data-chapter="7"]');await click('#guideResume');const size=(await p.locator('#voidShip').boundingBox()).width;await run(1200);const middle=await p.locator('#voidShip').boundingBox();assert(middle.width<size&&middle.width>size*.4);await run(1400);assert(await p.locator('#life7Complete').isVisible());const end=await p.locator('#voidShip').boundingBox(),scene=await p.locator('#voidWorld7').boundingBox();assert(end.width<size*.45);assert(Math.abs((end.x+end.width/2-scene.x)/scene.width-.5)<.02);assert(Math.abs((end.y+end.height/2-scene.y)/scene.height-.35)<.02);await p.screenshot({path:out+'/arrival.png'});report.shipActuallyEntersGate=true;assert.deepEqual(report.errors,[]);assert.deepEqual(report.bad,[]);fs.writeFileSync(out+'/void7-effects.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(e=>{report.failure=e.stack;fs.writeFileSync(out+'/void7-effects.json',JSON.stringify(report,null,2));console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
