const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),http=require('http'),R=require('../field-model.js'),P=require('../story-plan.js'),solve=require('./field-browser-helper.cjs');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||'/tmp/worlds-edges';fs.mkdirSync(out,{recursive:true});let browser,p;const report={errors:[],checks:[]};
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://a').pathname,f=path.join(root,pathname==='/'?'index.html':pathname);fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[path.extname(f)]||'application/octet-stream'});res.end(e?'':b);});});
(async()=>{
 for(const [n,key,value] of [[2,'selected',99],[2,'crew',-1],[4,'selected',99],[4,'pad',1.1],[8,'pin',{x:NaN,y:1}],[8,'pin',{x:700,y:1}],[9,'selected',99],[9,'evacuated',[1,1]]]){const s=R.create(n,0,73);s[key]=value;assert.equal(R.restore(s,n,0,73),null);}for(const n of [3,5,8]){const s=R.create(n,0,73),before=structuredClone(s);assert.equal(R.act(s,n===5?'valve':'angle',n===5?[0,NaN]:NaN),false);assert.deepEqual(s,before);}report.checks.push('eight corrupt spatial checkpoints rejected; NaN input does not mutate state');
 await new Promise(r=>server.listen(0,r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.on('pageerror',e=>report.errors.push(e.message));await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date('2026-10-04T22:00Z')});await p.clock.pauseAt(new Date('2026-10-04T22:00Z'));await p.goto('http://localhost:'+server.address().port);await p.evaluate(()=>setLang('ru'));
 const click=s=>p.locator(s).click(),run=ms=>p.clock.runFor(ms),read=n=>p.evaluate(n=>MKTYStory.read(n),n);
 await click('#enterBtn');await click('#skipBtn');assert.equal((await read(1)).edition,2);assert(await p.locator('#storyCore').isDisabled());await p.evaluate(()=>MKTYStory.open(2));assert(await p.locator('[data-chapter="2"]').isDisabled());await click('[data-chapter="1"]');await click('[data-story-step="0"]');await click('#fieldResume');await run(2300);const saved=await p.evaluate(()=>MKTYField.snapshot());await click('#fieldPause');await run(5000);assert.deepEqual(await p.evaluate(()=>MKTYField.snapshot()),saved);await click('#fieldExit');await p.evaluate(()=>{const k='mkty_story_plan_1_v1',s=JSON.parse(localStorage.getItem(k));s.tasks[0].checkpoint.pos=999;localStorage.setItem(k,JSON.stringify(s));});await p.reload();await click('#enterBtn');await click('[data-story-step="0"]');const recovered=await p.evaluate(()=>MKTYField.snapshot());assert.equal(recovered.moves,0);assert.equal(recovered.pos,R.layout(recovered).start);assert.equal((await read(1)).done.length,0);report.checks.push('fresh edition-2 locks, paused time, corrupt stage recovery');
 // Isolate replay handoffs without bypasses in production.
 await p.evaluate(()=>{show('chapters');for(let n=1;n<=9;n++){localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life'+n+'_awarded','yes');}localStorage.setItem('mkty_points','12250');localStorage.setItem('mkty_final_moon_points','12250');localStorage.setItem('mkty_life1_code_presented','yes');localStorage.setItem('mkty_life3_memory_verified','yes');});
 for(const n of [1,2,3]){await p.evaluate(n=>MKTYStory.replay(n),n);assert.equal((await read(n)).edition,2);await p.evaluate(n=>{const k='mkty_story_plan_'+n+'_v1',s=JSON.parse(localStorage.getItem(k));s.done=[0,1,2,3,4,5,6,7];localStorage.setItem(k,JSON.stringify(s));MKTYStory.menu(n);},n);await click('#storyCore');assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission'+n);assert(await p.locator('#life'+n+'Complete').isHidden());if(n===1)assert.equal(await p.locator('#energyCount').innerText(),'0/3');if(n===2){assert.equal(await p.locator('.mate.joined').count(),0);assert.match(await p.locator('#crewChallengeTitle').innerText(),/SELECT A CREW MEMBER TO BEGIN|ВЫБЕРИТЕ УЧАСТНИКА ЭКИПАЖА/);}assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');}
 report.checks.push('completed chapter 1–3 profiles enter playable new finales; no automatic reward');
 // A partially completed finale must count time before the final chapter reward.
 await p.evaluate(()=>{show('chapters');const s=StoryPlan.fresh(8,800,2);s.done=[0,1,2,3,4,5,6,7];s.phase='core';s.coreSeconds=11;localStorage.setItem('mkty_story_plan_8_v1',JSON.stringify(s));localStorage.setItem('mkty_operations_8_v1',JSON.stringify({version:1,n:8,seed:1,round:3,phase:'complete',input:null,confirmed:false,actions:0,hints:0,errors:0,seconds:31}));localStorage.setItem('mkty_field_finale_8_v1',JSON.stringify({version:1,n:8,phase:0,seed:8,seconds:19,checkpoint:{seconds:7}}));MKTYStory.menu(8);});assert.equal(await p.locator('#storyTime').innerText(),'1:08');report.checks.push('chapter clock includes legacy operations and partial spatial finale');
 // First-time final rewards, checkpoint across phase transition, resume and duplicate protection.
 await p.evaluate(()=>{show('chapters');localStorage.setItem('mkty_points','7250');for(const n of [8,9]){localStorage.removeItem('mkty_life'+n);localStorage.removeItem('mkty_life'+n+'_awarded');localStorage.removeItem('mkty_field_finale_'+n+'_v1');const s=StoryPlan.fresh(n,n*17,2);s.done=[0,1,2,3,4,5,6,7];s.phase='core';localStorage.setItem('mkty_story_plan_'+n+'_v1',JSON.stringify(s));localStorage.setItem('mkty_operations_'+n+'_v1',JSON.stringify({version:1,n,seed:1,round:3,phase:'complete',input:null,confirmed:false,actions:0,hints:0,errors:0,seconds:0}));}MKTYStory.open(8);});
 for(const n of [8,9]){if(n===9)await p.evaluate(()=>MKTYStory.open(9));for(let phase=0;phase<(n===8?2:3);phase++){assert.equal(await p.evaluate(n=>MKTYSpatialFinale.read(n).phase,n),phase);if(phase===1){await p.reload();await click('#enterBtn');assert.equal(await p.evaluate(n=>MKTYSpatialFinale.read(n).phase,n),phase);}await solve(p);}assert.equal((await read(n)).phase,'complete');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),n===8?'9250':'12250');}
 await p.evaluate(()=>{awardLifePoints(8,2000);awardLifePoints(9,3000);});assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');report.checks.push('new finale 8–9 first awards, phase resume and duplicate rewards');
 assert.deepEqual(report.errors,[]);console.log(JSON.stringify(report));
})().catch(async e=>{report.failure=e.stack;console.error(e);await p?.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/edges.json',JSON.stringify(report,null,2));await browser?.close();server.close();});
