/* All 72 chapter stages, driven through visible controls. Old finale flags isolate the new arcs. */
const {chromium}=require('./pace-hook.cjs'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http'),R=require('../mission-rules.js'),P=require('../story-plan.js'),E=require('../expedition-model.js');
const solveField=require('./field-browser-helper.cjs');
const root=path.resolve(__dirname,'..'),out=process.env.MKTY_TEST_OUTPUT||fs.mkdtempSync(path.join(require('os').tmpdir(),'mkty-worlds-'));fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://local').pathname,f=path.join(root,name==='/'?'index.html':name);fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.css':'text/css','.js':'application/javascript'})[path.extname(f)]||'application/octet-stream'});res.end(e?'':b);});});
let browser,p;const report={errors:[],chapters:[],layouts:[]},distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function pathTo(r,target){const step=30,n=108,id=(x,y)=>y*n+x,pos=i=>({x:i%n*step,y:Math.floor(i/n)*step}),grid=o=>id(Math.round(o.x/step),Math.round(o.y/step));const start=grid(r.ship),end=grid(target),open=[start],previous=new Map(),cost=new Map([[start,0]]),seen=new Set(),blocked=new Map();const safe=i=>{if(!blocked.has(i)){const a=pos(i);blocked.set(i,a.x<60||a.x>3140||a.y<60||a.y>3140||r.rocks.some(b=>distance(a,b)<b.r+30)||r.fields.some(b=>distance(a,b)<b.r+30));}return i===start||i===end||!blocked.get(i);};let found=false;while(open.length){open.sort((a,b)=>(cost.get(a)+distance(pos(a),target))-(cost.get(b)+distance(pos(b),target)));const a=open.shift();if(a===end){found=true;break;}if(seen.has(a))continue;seen.add(a);const x=a%n,y=Math.floor(a/n);for(const [dx,dy]of[[0,1],[0,-1],[1,0],[-1,0],[1,1],[-1,1],[1,-1],[-1,-1]]){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=n||yy>=n)continue;const b=id(xx,yy);if(!safe(b)||(dx&&dy&&(!safe(id(x+dx,y))||!safe(id(x,y+dy)))))continue;const value=cost.get(a)+Math.hypot(dx,dy)*step;if(value<(cost.get(b)??Infinity)){cost.set(b,value);previous.set(b,a);open.push(b);}}}assert(found,'No clear navigation path');const points=[];for(let a=end;a!==start;a=previous.get(a))points.unshift(pos(a));points.push(target);return points;}
(async()=>{await new Promise(r=>server.listen(0,r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(20000);p.on('pageerror',e=>report.errors.push(e.message));await p.route('https://telegram.org/**',r=>r.fulfill({body:''}));await p.clock.install({time:new Date('2026-10-04T19:00Z')});await p.clock.pauseAt(new Date('2026-10-04T19:00Z'));
const profile=E.profile();profile.parts=345;profile.upgrades.hull=1;const free={version:1,profile,run:E.create(117,'salvage',1,profile)};await p.addInitScript(f=>{if(localStorage.getItem('story-fixture'))return;localStorage.setItem('story-fixture','yes');localStorage.setItem('mkty_lang','ru');localStorage.setItem('mkty_life1_code_presented','yes');localStorage.setItem('mkty_life3_memory_verified','yes');localStorage.setItem('mkty_points','12250');localStorage.setItem('mkty_final_moon_points','12250');localStorage.setItem('mkty_expeditions_v1',JSON.stringify(f));for(let n=1;n<=9;n++){localStorage.setItem('mkty_story_plan_'+n+'_v1',JSON.stringify({version:1,edition:2,n,seed:n*571,phase:'operations',done:[],tasks:{},coreSeconds:0,createdAt:Date.now()}));localStorage.setItem('mkty_life'+n,'complete');localStorage.setItem('mkty_life'+n+'_awarded','yes');if(n>=4)localStorage.setItem('mkty_operations_'+n+'_v1',JSON.stringify({version:1,n,seed:1,round:3,phase:'complete',input:null,confirmed:false,actions:0,hints:0,errors:0,seconds:0}));}},free);
await p.goto('http://localhost:'+server.address().port);const run=ms=>p.clock.runFor(ms),click=s=>p.locator(s).click(),story=n=>p.evaluate(n=>MKTYStory.read(n),n),snap=()=>p.evaluate(()=>MKTYExpedition.snapshot());let held=new Set();
async function steer(x,y){const next=new Set([...(x>.25?['ArrowRight']:x<-.25?['ArrowLeft']:[]),...(y>.25?['ArrowDown']:y<-.25?['ArrowUp']:[])]);for(const k of held)if(!next.has(k))await p.keyboard.up(k);for(const k of next)if(!held.has(k))await p.keyboard.down(k);held=next;}
async function fly(target){const route=pathTo((await snap()).run,target);let i=0,ticks=0;while(i<route.length&&ticks++<1800){const r=(await snap()).run;assert.equal(r.phase,'flight','Ship lost');const node=route[i],d=distance(node,r.ship);if(d<(i===route.length-1?45:29)){i++;continue;}const dx=node.x-r.ship.x,dy=node.y-r.ship.y;await steer(dx/Math.max(Math.abs(dx),Math.abs(dy)),dy/Math.max(Math.abs(dx),Math.abs(dy)));if(r.drones.some(d=>!d.disabled&&distance(d,r.ship)<320)&&r.emp===0&&r.ship.energy>=35)await p.keyboard.press('Space');await run(160);}assert(i===route.length);await steer(0,0);await run(700);}
async function interact(id){await fly((await snap()).run.points.find(o=>o.id===id));await p.keyboard.down('KeyE');await run(id==='wreck'?4500:3000);await p.keyboard.up('KeyE');assert((await snap()).run.points.find(o=>o.id===id).done,id);}
async function board(n,task){let s=await story(n),cp=s.tasks[task.id].checkpoint,b=R.board(task.board,task.round,cp.seed);await click('#opsSubmit');assert(!(await story(n)).done.includes(task.id));
if(task.board===4){for(const i of b.path.slice(1))await click('[data-op-cell="'+i+'"]');}
if(task.board===5){for(const i of b.path)for(let j=0;j<(4-b.turns[i])%4;j++)await click('[data-op-cell="'+i+'"]');}
if(task.board===6){let tiles=b.tiles.slice();for(let i=0;i<tiles.length;i++)if(tiles[i]!==b.target[i]){const j=tiles.indexOf(b.target[i]);await click('[data-op-cell="'+i+'"]');await click('[data-op-cell="'+j+'"]');[tiles[i],tiles[j]]=[tiles[j],tiles[i]];}}
if(task.board===7){for(const i of R.solveShield(b,R.initial(b)))await click('[data-op-cell="'+i+'"]');}
if(task.board===8){for(let i=0;i<b.size;i++){await click('[data-op-cell="'+i+'"]');await click('[data-op-glyph="'+b.secret[i]+'"]');}}
if(task.board===9){for(const i of R.solveSystems(b,R.initial(b)))await click('[data-op-cell="'+i+'"]');}
await click('#opsSubmit');assert((await story(n)).tasks[task.id].checkpoint.confirmed);
if(task.id===1){const before=(await story(n)).tasks[1].checkpoint;await p.reload();await click('#enterBtn');assert.equal(await p.locator('.screen.active').getAttribute('id'),'storyPlan');await click('[data-story-step="1"]');assert.deepEqual((await story(n)).tasks[1].checkpoint.input,before.input);assert((await story(n)).tasks[1].checkpoint.confirmed);}
await click('#opsSubmit');assert((await story(n)).done.includes(task.id));}
await click('#missionsBtn');const initialFree=await p.evaluate(()=>localStorage.getItem('mkty_expeditions_v1'));
for(let n=1;n<=9;n++){await click('[data-chapter="'+n+'"]');assert.equal(await p.locator('.screen.active').getAttribute('id'),'storyPlan');assert(await p.locator('#storyCore').isDisabled());assert.equal(await p.locator('[data-story-step]:enabled').count(),2);const chapter={n,stages:[]};report.chapters.push(chapter);
for(const task of P.plan(n).steps){assert(await p.locator('[data-story-step="'+task.id+'"]').isEnabled());await click('[data-story-step="'+task.id+'"]');
if(task.kind==='board')await board(n,task);
else if(task.kind==='field')await solveField(p);
else{await click('[data-exp-dialog="resume"]');await run(100);if(n===1&&task.id===2){await p.keyboard.down('ArrowRight');await run(600);await p.keyboard.up('ArrowRight');await click('#expPause');const before=(await snap()).run;await run(6000);assert.deepEqual((await snap()).run,before);await click('[data-exp-dialog="hangar"]');await p.reload();await click('#enterBtn');await click('[data-story-step="2"]');assert.deepEqual((await snap()).run.ship,before.ship);await click('[data-exp-dialog="resume"]');}
if(task.contract==='rescue'){await interact('pod-a');await interact('pod-b');}else if(task.contract==='salvage'){await interact('relay-a');await interact('relay-b');await interact('wreck');}else{await interact('relay-a');await interact('relay-b');await interact('relay-c');}
await fly(E.BASE);await p.keyboard.down('KeyE');await run(150);await p.keyboard.up('KeyE');assert((await snap()).run.report.success);await click('[data-exp-dialog="story-complete"]');assert((await story(n)).done.includes(task.id));const storedFree=JSON.parse(await p.evaluate(()=>localStorage.getItem('mkty_expeditions_v1')));assert.deepEqual(storedFree.profile,free.profile);assert.deepEqual(storedFree.run.ship,free.run.ship);}
chapter.stages.push({id:task.id,kind:task.kind,seconds:(await story(n)).tasks[task.id].seconds});assert.equal(await p.locator('.screen.active').getAttribute('id'),'storyPlan');assert(await p.locator('[data-story-step="'+task.id+'"]').isDisabled());}
assert.equal((await story(n)).done.length,8);assert(await p.locator('#storyCore').isEnabled());await click('#storyCore');if(n>=8){for(let phase=0;phase<(n===8?2:3);phase++){assert.equal(await p.locator('.screen.active').getAttribute('id'),'fieldMission');await solveField(p);}}assert.equal(await p.locator('.screen.active').getAttribute('id'),'mission'+n);if(n>=8)assert.equal((await story(n)).phase,'complete');assert.equal(await p.evaluate(()=>localStorage.getItem('mkty_points')),'12250');await p.evaluate(()=>show('chapters'));console.log('Completed expanded chapter',n);fs.writeFileSync(out+'/story.json',JSON.stringify(report,null,2));}
for(const lang of ['ru','en'])for(const [width,height]of [[320,480],[390,844],[568,320],[844,390]]){await p.evaluate(l=>localStorage.setItem('mkty_lang',l),lang);await p.setViewportSize({width,height});await p.evaluate(()=>MKTYStory.menu(9));const layout=await p.locator('#storyPlan').evaluate(e=>({width:document.documentElement.scrollWidth,buttons:[...e.querySelectorAll('button')].map(b=>b.getBoundingClientRect().toJSON())}));assert(layout.width<=width);for(const b of layout.buttons)assert(b.x>=0&&b.right<=width+1&&b.height>=43);report.layouts.push({lang,width,height});}
assert.deepEqual(report.errors,[]);console.log('PASS: 36 spatial missions, 27 boards, 9 flown sorties, five spatial finale phases, all chapter handoffs and reward isolation.');
})().catch(async e=>{report.failure=e.stack;report.failedState=await p?.evaluate(()=>({field:MKTYField.snapshot(),flight:MKTYExpedition.snapshot(),plan:MKTYStory.read(Number(localStorage.getItem('mkty_current_chapter')))})).catch(()=>null);console.error(e);await p?.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/story.json',JSON.stringify(report,null,2));await browser?.close();await new Promise(r=>server.close(r));});
