import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const enc=new TextEncoder();
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function hm(k:Uint8Array,m:string){const x=await crypto.subtle.importKey("raw",k,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",x,enc.encode(m)))}
const hx=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
function same(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function telegramUser(initData:string,token:string){const p=new URLSearchParams(initData),hash=p.get("hash"),raw=p.get("user");if(!hash||!raw)throw Error("bad telegram data");const ad=Number(p.get("auth_date")),now=Math.floor(Date.now()/1000);if(!Number.isFinite(ad)||now-ad>600||ad>now+60)throw Error("expired");const check=[...p.entries()].filter(([k])=>k!=="hash"&&k!=="signature").sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+"="+v).join("\n");const secret=await hm(enc.encode("WebAppData"),token);if(!same(hx(await hm(secret,check)),hash.toLowerCase()))throw Error("signature");const u=JSON.parse(raw);if(typeof u?.id!=="number")throw Error("user");return u}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"method"},405);try{const token=Deno.env.get("TELEGRAM_BOT_TOKEN"),url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!token||!url||!key)throw Error("config");const body=await req.json(),initData=typeof body.initData==="string"?body.initData:"";const user=await telegramUser(initData,token);const db=createClient(url,key,{auth:{persistSession:false}});
let q=await db.from("players").select("*").eq("telegram_id",user.id).maybeSingle();if(q.error)throw q.error;let player=q.data;if(!player){q=await db.from("players").insert({telegram_id:user.id,username:user.username||null,first_name:user.first_name||null}).select().single();if(q.error)throw q.error;player=q.data}
if(body.action==="complete_life"){const life=Number(body.life);if(!Number.isInteger(life)||life<1||life>9)return json({ok:false,error:"life"},400);if(life>Number(player.story_life)+1)return json({ok:false,error:"locked"},409);const reward=life===1?500:life*10,event_key="life_"+life+"_complete";const ev=await db.from("reward_events").insert({telegram_id:user.id,event_key,event_type:"life_complete",points:reward,verified:true});let points=Number(player.moon_points);if(!ev.error)points+=reward;else if(ev.error.code!=="23505")throw ev.error;const update:any={story_life:Math.max(Number(player.story_life),life),moon_points:points,updated_at:new Date().toISOString()};if(life===9){update.final_balance=points;update.balance_locked_at=new Date().toISOString()}q=await db.from("players").update(update).eq("telegram_id",user.id).select().single();if(q.error)throw q.error;player=q.data}
return json({ok:true,player});}catch(e){console.error(e);return json({ok:false,error:"auth"},401)}});