const {chromium}=require('playwright');const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.LUNAR_OUTPUT||'/tmp/moonkatty-lunar-concept';fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png'};
async function frameShot(page,name){await page.evaluate(()=>window.__LUNAR__.setRendering(false));try{await page.screenshot({path:path.join(out,name),timeout:90000});}finally{await page.evaluate(()=>window.__LUNAR__.setRendering(true));}console.log('Saved frame',name);}
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';p=path.join(root,p);if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('content-type',mime[path.extname(p)]||'application/octet-stream');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,errors=[],requests=[],report={commit:process.env.GITHUB_SHA||null,renderer:'Chromium WebGL / software GPU in CI. Not a physical-phone benchmark.',checks:[],views:[]};let browser;
try{browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});const context=await browser.newContext({viewport:{width:process.env.LUNAR_VISUAL_ONLY==='1'?960:1280,height:process.env.LUNAR_VISUAL_ONLY==='1'?540:720},deviceScaleFactor:1});const page=await context.newPage();page.setDefaultTimeout(180000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});page.on('request',r=>requests.push(r.url()));
await page.addInitScript(()=>{localStorage.setItem('mkty_campaign_isolation_sentinel','unchanged');sessionStorage.setItem('mkty_preview_isolation_sentinel','unchanged');});await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'networkidle'});console.log('Scene page loaded');await page.waitForFunction(()=>window.__LUNAR__?.ready===true);await page.waitForTimeout(1500);let s=await page.evaluate(()=>window.__LUNAR__.snapshot());assert.equal(s.contextLost,false);assert(s.triangles>20000);report.initial=s;report.checks.push('WebGL scene initialized with real mesh triangles');
console.log('Ready',s);await frameShot(page,'01-lunar-observatory-desktop.png');console.log('First frame saved');await page.keyboard.press('h');await page.waitForTimeout(300);await frameShot(page,'02-lunar-observatory-clean.png');await page.keyboard.press('h');if(process.env.LUNAR_VISUAL_ONLY==='1'){report.status='rendered';report.errors=errors;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));return;}
const before=await page.evaluate(()=>window.__LUNAR__.snapshot());await page.keyboard.down('KeyD');await page.waitForFunction(p=>{const a=window.__LUNAR__.snapshot().player;return Math.hypot(a[0]-p[0],a[2]-p[2])>.8},before.player,{timeout:45000});await page.keyboard.up('KeyD');const after=await page.evaluate(()=>window.__LUNAR__.snapshot());assert(Math.hypot(after.player[0]-before.player[0],after.player[2]-before.player[2])>.4);report.checks.push('WASD moves the actual 3D hero');
await page.mouse.move(1000,600);await page.mouse.down();await page.mouse.move(530,575,{steps:12});await page.mouse.up();const rotated=await page.evaluate(()=>window.__LUNAR__.snapshot());assert(Math.abs(rotated.yaw-after.yaw)>1);report.checks.push('Pointer drag rotates camera freely');await frameShot(page,'03-free-orbit-angle.png');await page.mouse.wheel(0,-420);const zoom=await page.evaluate(()=>window.__LUNAR__.snapshot());assert(zoom.distance<rotated.distance);report.checks.push('Wheel zoom changes camera distance');
await page.click('#menu');const pause=await page.evaluate(()=>window.__LUNAR__.snapshot());await page.keyboard.down('KeyW');await page.waitForTimeout(500);await page.keyboard.up('KeyW');const held=await page.evaluate(()=>window.__LUNAR__.snapshot());assert.equal(held.paused,true);assert.deepEqual(held.player,pause.player);await page.click('#resume');report.checks.push('Pause blocks movement and clears inputs');await page.click('#home');await page.waitForTimeout(1000);
assert.equal(await page.evaluate(()=>localStorage.getItem('mkty_campaign_isolation_sentinel')),'unchanged');assert.equal(await page.evaluate(()=>sessionStorage.getItem('mkty_preview_isolation_sentinel')),'unchanged');assert(requests.every(u=>u.startsWith(`http://127.0.0.1:${port}`)));report.checks.push('No external network, campaign, auth, backend or reward interaction');
await page.evaluate(()=>window.__LUNAR__.setView(.5,.10,11));await page.waitForTimeout(1400);await page.keyboard.press('h');await frameShot(page,'06-hero-material-closeup.png');await page.keyboard.press('h');await page.click('#home');await page.setViewportSize({width:844,height:390});await page.waitForTimeout(700);await frameShot(page,'04-phone-landscape.png');report.views.push({width:844,height:390,...await page.evaluate(()=>window.__LUNAR__.snapshot())});
await context.close();const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.setDefaultTimeout(180000);mp.on('pageerror',e=>errors.push(e.message));await mp.goto(`http://127.0.0.1:${port}/`);await mp.waitForFunction(()=>window.__LUNAR__?.ready);await mp.waitForTimeout(1000);assert(await mp.locator('#stick').isVisible());const overflow=await mp.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);await frameShot(mp,'05-phone-portrait.png');report.views.push({width:390,height:844,...await mp.evaluate(()=>window.__LUNAR__.snapshot())});
const cdp=await mobile.newCDPSession(mp),b=await mp.locator('#stick').boundingBox(),x=b.x+b.width/2,y=b.y+b.height/2;const pre=await mp.evaluate(()=>window.__LUNAR__.snapshot());await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,radiusX:2,radiusY:2,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+30,y,radiusX:2,radiusY:2,id:1}]});await mp.waitForFunction(p=>{const a=window.__LUNAR__.snapshot().player;return Math.hypot(a[0]-p[0],a[2]-p[2])>.7},pre.player,{timeout:45000});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const post=await mp.evaluate(()=>window.__LUNAR__.snapshot());assert(Math.hypot(post.player[0]-pre.player[0],post.player[2]-pre.player[2])>.3);report.checks.push('Touch joystick moves hero; portrait layout has no horizontal overflow');
await mobile.close();const standalone=path.join(out,'MOONKATTY-lunar-observatory-playable.html');if(fs.existsSync(standalone)){const offline=await browser.newContext({viewport:{width:1000,height:620},deviceScaleFactor:1}),op=await offline.newPage(),net=[];op.setDefaultTimeout(180000);op.on('request',r=>{if(/^https?:/.test(r.url()))net.push(r.url());});op.on('pageerror',e=>errors.push(e.message.slice(0,1500)));await op.goto(require('node:url').pathToFileURL(standalone).href);await op.waitForFunction(()=>window.__LUNAR__?.ready);assert.equal(net.length,0);await op.waitForTimeout(500);await frameShot(op,'07-standalone-offline.png');report.checks.push('Single-file HTML opens from file:// with no HTTP dependencies');await offline.close();}
report.errors=errors;assert.deepEqual(errors,[]);report.status='passed';fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){report.status='failed';report.error=e.stack;report.errors=errors;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));throw e;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})();
