// Generated by tools/build-server-models.cjs; edit the root model instead.
const module={exports:{}};
/* Deterministic, solvable mission boards. Shared by the browser and regression tests. */
(function(scope){
 'use strict';
 const dirs=[[-1,0],[0,1],[1,0],[0,-1]];
 function rng(seed){let x=seed>>>0;return()=>((x=(Math.imul(x,1664525)+1013904223)>>>0)/4294967296);}
 function shuffle(a,random){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function adjacent(a,b,n){return Math.abs(Math.floor(a/n)-Math.floor(b/n))+Math.abs(a%n-b%n)===1;}
 function direction(a,b,n){const dr=Math.floor(b/n)-Math.floor(a/n),dc=b%n-a%n;return dirs.findIndex(([r,c])=>r===dr&&c===dc);}
 // A randomized self-avoiding route with bounded search. The serpentine fallback is always valid.
 function route(n,random){
  const goal=n*n-1,min=n*3-2,max=n*n-2;let budget=12000,answer;
  function visit(path,used){if(--budget<0)return false;const i=path.at(-1);if(i===goal){if(path.length>=min){answer=path;return true;}return false;}if(path.length>=max)return false;
   const options=shuffle(dirs.map(([r,c])=>[Math.floor(i/n)+r,i%n+c]).filter(([r,c])=>r>=0&&c>=0&&r<n&&c<n).map(([r,c])=>r*n+c),random);
   for(const j of options)if(!used.has(j)){used.add(j);if(visit([...path,j],used))return true;used.delete(j);}return false;
  }
  visit([0],new Set([0]));if(answer)return answer;
  const p=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)p.push(r*n+(r%2?n-1-c:c));
  if(p.at(-1)!==goal)p.splice(p.indexOf(goal)+1);return p;
 }
 function board(chapter,round,seed){
  const random=rng((seed+round*65537+chapter*104729)>>>0);
  if(chapter===4||chapter===5){
   const n=(chapter===4?5:4)+round,path=route(n,random),beacons=[.25,.5,.75].map(t=>path[Math.floor((path.length-1)*t)]);
   if(chapter===4){const rocks=[],cost=Array.from({length:n*n},()=>random()<.24?3:1);for(let i=0;i<n*n;i++)if(!path.includes(i)&&random()<.55)rocks.push(i);
    return {type:'route',n,path,beacons,rocks,cost,budget:path.slice(1).reduce((sum,i)=>sum+cost[i],0)+2-round};}
   const ports=Array.from({length:n*n},()=>random()<.5?[0,2]:[0,1]),turns=Array.from({length:n*n},()=>Math.floor(random()*4));
   path.forEach((i,k)=>ports[i]=[k?direction(i,path[k-1],n):3,k<path.length-1?direction(i,path[k+1],n):1]);
   if(path.every(i=>turns[i]===0))turns[0]=1;
   return {type:'pipes',n,path,beacons,ports,turns};
  }
  if(chapter===6){const rows=round===0?2:3,cols=3,target=shuffle(Array.from({length:rows*cols},(_,i)=>i+1),random);let tiles=shuffle(target,random);
   const equalTotals=()=>Array.from({length:rows},(_,r)=>tiles.slice(r*cols,r*cols+cols).reduce((a,b)=>a+b,0)===target.slice(r*cols,r*cols+cols).reduce((a,b)=>a+b,0)).filter(Boolean).length+Array.from({length:cols},(_,c)=>tiles.filter((_,i)=>i%cols===c).reduce((a,b)=>a+b,0)===target.filter((_,i)=>i%cols===c).reduce((a,b)=>a+b,0)).filter(Boolean).length;
   while(equalTotals()>1)tiles=shuffle(target,random);
   return {type:'cargo',rows,cols,target,tiles,row: Array.from({length:rows},(_,r)=>target.slice(r*cols,r*cols+cols).reduce((a,b)=>a+b,0)),col:Array.from({length:cols},(_,c)=>target.filter((_,i)=>i%cols===c).reduce((a,b)=>a+b,0))};}
  if(chapter===7){const n=3+round,lamps=Array(n*n).fill(0),moves=shuffle(Array.from({length:n*n},(_,i)=>i),random).slice(0,4+round*2);moves.forEach(i=>toggle(lamps,i,n));if(!lamps.some(Boolean))toggle(lamps,0,n);return {type:'shield',n,lamps};}
  if(chapter===8)return {type:'cipher',size:3+round,secret:shuffle([0,1,2,3,4,5],random).slice(0,3+round),limit:8};
  const costs=[[2,0,0],[0,3,0],[0,0,2],[3,1,0],[0,2,2],[2,0,1]],gains=[[0,4,0],[0,0,4],[4,0,0],[0,0,1],[1,0,0],[0,0,0]];
  if(round>0){costs.push([1,0,round===2?1:0]);gains.push([0,1,round===2?1:0]);}if(round===2){costs.push([0,1,1]);gains.push([1,0,1]);}
  const perm=shuffle([0,1,2],random),rotate=a=>perm.map(i=>a[i]);
  return {type:'systems',stock:rotate([3,2,2]),capacity:8,tasks:shuffle(costs.map((cost,i)=>({id:i,cost:rotate(cost),gain:rotate(gains[i])})),random)};
 }
 function initial(b){return b.type==='route'?{path:[0]}:b.type==='pipes'?{turns:b.turns.slice()}:b.type==='cargo'?{tiles:b.tiles.slice(),selected:null}:b.type==='shield'?{lamps:b.lamps.slice(),history:[]}:b.type==='cipher'?{guess:Array(b.size).fill(null),slot:0,history:[],revealed:[]}: {order:[]};}
 function toggle(lamps,i,n){[i,...dirs.map(([r,c])=>[Math.floor(i/n)+r,i%n+c]).filter(([r,c])=>r>=0&&c>=0&&r<n&&c<n).map(([r,c])=>r*n+c)].forEach(j=>lamps[j]^=1);}
 function feedback(guess,secret){const exact=guess.filter((v,i)=>v===secret[i]).length;return {exact,near:guess.filter(v=>secret.includes(v)).length-exact};}
 function pipeTrace(b,p){const path=[],seen=new Set();let i=0,entry=3;while(!seen.has(i)){seen.add(i);const ports=b.ports[i].map(d=>(d+p.turns[i])%4);if(!ports.includes(entry))return {path,success:false};path.push(i);const exit=ports.find(d=>d!==entry);if(i===b.n*b.n-1&&exit===1)return {path,success:b.beacons.every(v=>path.includes(v))};const [dr,dc]=dirs[exit],r=Math.floor(i/b.n)+dr,c=i%b.n+dc;if(r<0||c<0||r>=b.n||c>=b.n)return {path,success:false};i=r*b.n+c;entry=(exit+2)%4;}return {path,success:false};}
 function stock(b,p){let value=b.stock.slice();for(const id of p.order){const t=b.tasks.find(t=>t.id===id);if(!t||t.cost.some((v,i)=>v>value[i]))return null;value=value.map((v,i)=>Math.min(b.capacity,v-t.cost[i]+t.gain[i]));}return value;}
 function canTask(b,p,t){const value=stock(b,p);return value&&!p.order.includes(t.id)&&t.cost.every((v,i)=>v<=value[i]);}
 function routeCost(b,p){return p.path.slice(1).reduce((sum,i)=>sum+b.cost[i],0);}
 function solved(b,p){
  if(b.type==='route')return p.path.at(-1)===b.n*b.n-1&&b.beacons.every(v=>p.path.includes(v))&&routeCost(b,p)<=b.budget;
  if(b.type==='pipes')return pipeTrace(b,p).success;
  if(b.type==='cargo')return b.row.every((v,r)=>p.tiles.slice(r*b.cols,r*b.cols+b.cols).reduce((a,b)=>a+b,0)===v)&&b.col.every((v,c)=>p.tiles.filter((_,i)=>i%b.cols===c).reduce((a,b)=>a+b,0)===v);
  if(b.type==='shield')return !p.lamps.some(Boolean);
  if(b.type==='cipher')return p.history.some(g=>feedback(g,b.secret).exact===b.size);
  return p.order.length===b.tasks.length&&stock(b,p)!==null;
 }
 function solveShield(b,p){const size=b.n*b.n,a=Array.from({length:size},(_,r)=>Array.from({length:size+1},(_,c)=>c===size?p.lamps[r]:Number(r===c||adjacent(r,c,b.n))));let row=0,pivots=[];
  for(let c=0;c<size;c++){const k=a.findIndex((r,i)=>i>=row&&r[c]);if(k<0)continue;[a[row],a[k]]=[a[k],a[row]];for(let r=0;r<size;r++)if(r!==row&&a[r][c])for(let j=c;j<=size;j++)a[r][j]^=a[row][j];pivots.push(c);row++;}
  if(a.some(r=>!r.slice(0,size).some(Boolean)&&r[size]))return null;return pivots.filter((c,i)=>a[i][size]);
 }
 function solveSystems(b,p){if(p.order.length===b.tasks.length)return [];for(const t of b.tasks)if(canTask(b,p,t)){const tail=solveSystems(b,{order:[...p.order,t.id]});if(tail)return [t.id,...tail];}return null;}
 function validate(b,p){
  if(!p||typeof p!=='object')return false;const ints=(a,len,min,max)=>Array.isArray(a)&&a.length===len&&a.every(v=>Number.isInteger(v)&&v>=min&&v<=max);
  if(b.type==='route')return Array.isArray(p.path)&&p.path.length>=1&&p.path.length<=b.n*b.n&&p.path[0]===0&&new Set(p.path).size===p.path.length&&p.path.every((v,i)=>Number.isInteger(v)&&v>=0&&v<b.n*b.n&&!b.rocks.includes(v)&&(!i||adjacent(v,p.path[i-1],b.n)))&&routeCost(b,p)<=b.budget;
  if(b.type==='pipes')return ints(p.turns,b.n*b.n,0,3);
  if(b.type==='cargo')return ints(p.tiles,b.target.length,1,b.target.length)&&new Set(p.tiles).size===p.tiles.length&&(p.selected===null||Number.isInteger(p.selected)&&p.selected>=0&&p.selected<p.tiles.length);
  if(b.type==='shield'){if(!ints(p.lamps,b.n*b.n,0,1)||!Array.isArray(p.history)||p.history.length>2000||!p.history.every(v=>Number.isInteger(v)&&v>=0&&v<b.n*b.n))return false;const lamps=b.lamps.slice();p.history.forEach(i=>toggle(lamps,i,b.n));return lamps.every((v,i)=>v===p.lamps[i]);}
  if(b.type==='cipher')return Array.isArray(p.guess)&&p.guess.length===b.size&&p.guess.every(v=>v===null||Number.isInteger(v)&&v>=0&&v<6)&&Number.isInteger(p.slot)&&p.slot>=0&&p.slot<b.size&&Array.isArray(p.history)&&p.history.length<=b.limit&&p.history.every(g=>ints(g,b.size,0,5)&&new Set(g).size===g.length)&&Array.isArray(p.revealed)&&p.revealed.length<=b.size&&p.revealed.every(v=>Number.isInteger(v)&&v>=0&&v<b.size);
  return Array.isArray(p.order)&&p.order.length<=b.tasks.length&&new Set(p.order).size===p.order.length&&p.order.every(id=>b.tasks.some(t=>t.id===id))&&stock(b,p)!==null;
 }
 const api={board,initial,adjacent,direction,toggle,feedback,pipeTrace,stock,canTask,routeCost,solved,solveShield,solveSystems,validate};
 if(typeof module==='object'&&module.exports)module.exports=api;else scope.MissionRules=api;
})(typeof window==='object'?window:globalThis);

export default module.exports;
