import * as T from './vendor/three-r170.module.min.js';
import {buildWorld,ground,walkHeight,clamp} from './world.js';
import {createHero} from './hero.js';
const $=s=>document.querySelector(s),canvas=$('#world'),keys=new Set();
let renderer,world,hero,camera,paused=false,quality='high',clean=false;
const player=new T.Vector3(-6,0,22),target=new T.Vector3(),cameraTarget=new T.Vector3();let yaw=.12,pitch=-.015,distance=40,walk=0,last=0,ready=false,rendering=true;const pointer=new Map(),stick={x:0,y:0,id:null},start={x:-6,z:22};
try{
renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',alpha:false});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
world=await buildWorld(renderer);hero=createHero();hero.root.position.copy(player);hero.root.rotation.y=.63;hero.root.scale.setScalar(1.45);world.scene.add(hero.root);camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.1,450);cameraTarget.set(player.x+6,8,player.z-28);resize();ready=true;window.__LUNAR__={ready:true,snapshot:()=>({player:player.toArray(),yaw,pitch,distance,paused,quality,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,pixelRatio:renderer.getPixelRatio(),heroTriangles:hero.triangleCount,contextLost:renderer.getContext().isContextLost(),storageKeys:Object.keys(localStorage)}),setView:(y,p,d)=>{yaw=y;pitch=p;distance=d;frameTarget(cameraTarget);},setRendering:v=>{if(v===rendering)return;rendering=v;if(v){last=0;requestAnimationFrame(frame);}},setPlayer:(x,z)=>{player.x=x;player.z=z;},scene:world.scene,renderer,camera};$('#loading').classList.add('done');requestAnimationFrame(frame);
}catch(e){$('#error').hidden=false;$('#error').textContent='Не удалось открыть 3D-сцену. Попробуйте современный браузер с WebGL 2. '+e.message;console.error(e);}
function frameTarget(out){const f=clamp((distance-10)/30,0,1),portrait=innerWidth<innerHeight;return out.set(player.x+(portrait?0:6)*f,player.y+2.5+(portrait?3:5.5)*f,player.z-(portrait?19:28)*f);}
function resize(){if(!renderer)return;const w=innerWidth,h=innerHeight;renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='low'?1:matchMedia('(pointer:coarse)').matches?1.5:1.75));renderer.setSize(w,h,false);if(camera){camera.aspect=w/h;camera.fov=w<h?62:52;camera.updateProjectionMatrix();frameTarget(cameraTarget);}}
addEventListener('resize',resize);
function release(){keys.clear();pointer.clear();stick.x=stick.y=0;stick.id=null;$('#stick div').style.transform='';}
function modal(v){paused=v;$('#modal').hidden=!v;release();}
$('#menu').onclick=()=>modal(!paused);$('#resume').onclick=()=>modal(false);$('#quality').onclick=()=>{quality=quality==='high'?'low':'high';$('#quality').textContent='Качество: '+(quality==='high'?'высокое':'экономное');renderer.shadowMap.enabled=quality==='high';resize();};
function reset(){player.set(start.x,0,start.z);yaw=.12;pitch=-.015;distance=40;hero.root.rotation.y=.63;cameraTarget.set(player.x+6,8,player.z-28);}
$('#home').onclick=reset;$('#photo').onclick=()=>{clean=!clean;document.body.classList.toggle('clean',clean);};
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='Escape'){if(clean){clean=false;document.body.classList.remove('clean');}else modal(!paused);}if(e.key.toLowerCase()==='h'){clean=!clean;document.body.classList.toggle('clean',clean);}if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','KeyQ','KeyE'].includes(e.code)){e.preventDefault();if(!paused)keys.add(e.code);}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{release();if(document.hidden)last=0;});
canvas.addEventListener('pointerdown',e=>{if(paused)return;canvas.setPointerCapture(e.pointerId);pointer.set(e.pointerId,{x:e.clientX,y:e.clientY});});
canvas.addEventListener('pointermove',e=>{if(paused||!pointer.has(e.pointerId))return;const prev=pointer.get(e.pointerId);if(pointer.size===1){yaw-=(e.clientX-prev.x)*.004;pitch=clamp(pitch+(e.clientY-prev.y)*.003,-.10,1.10);}else{const other=[...pointer.entries()].find(([id])=>id!==e.pointerId)?.[1];if(other){let a=Math.hypot(prev.x-other.x,prev.y-other.y),b=Math.hypot(e.clientX-other.x,e.clientY-other.y);distance=clamp(distance-(b-a)*.065,8,55);}}pointer.set(e.pointerId,{x:e.clientX,y:e.clientY});});
for(const evt of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(evt,e=>pointer.delete(e.pointerId));canvas.addEventListener('wheel',e=>{e.preventDefault();if(!paused)distance=clamp(distance+e.deltaY*.018,8,55);},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('#stick').addEventListener('pointerdown',e=>{if(paused)return;e.preventDefault();stick.id=e.pointerId;$('#stick').setPointerCapture(e.pointerId);stickMove(e);});function stickMove(e){if(e.pointerId!==stick.id)return;const b=$('#stick').getBoundingClientRect();let x=(e.clientX-b.left-b.width/2)/(b.width*.35),y=(e.clientY-b.top-b.height/2)/(b.width*.35),len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}stick.x=x;stick.y=y;$('#stick div').style.transform=`translate(${x*b.width*.26}px,${y*b.height*.26}px)`;}$('#stick').addEventListener('pointermove',stickMove);for(const evt of ['pointerup','pointercancel','lostpointercapture'])$('#stick').addEventListener(evt,e=>{if(e.pointerId===stick.id){stick.id=null;stick.x=stick.y=0;$('#stick div').style.transform='';}});
function collides(x,z){if(Math.hypot(x,z)>49)return true;for(const c of world.collisions){if(c.r&&Math.hypot(x-c.x,z-c.z)<c.r+.55)return true;if(c.w&&Math.abs(x-c.x)<c.w/2+.55&&Math.abs(z-c.z)<c.d/2+.55)return true;}return false;}
function frame(t){if(!ready||!rendering)return;const dt=last?Math.min((t-last)/1000,.05):.016;last=t;if(!paused&&!document.hidden){let sx=stick.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),sz=stick.y+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),len=Math.hypot(sx,sz);if(len>1){sx/=len;sz/=len;}if(keys.has('KeyQ'))yaw+=dt;if(keys.has('KeyE'))yaw-=dt;walk=T.MathUtils.damp(walk,len>.12?1:0,10,dt);if(len>.12){const dx=(sx*Math.cos(yaw)+sz*Math.sin(yaw))*dt*5,dz=(-sx*Math.sin(yaw)+sz*Math.cos(yaw))*dt*5;if(!collides(player.x+dx,player.z))player.x+=dx;if(!collides(player.x,player.z+dz))player.z+=dz;const rot=Math.atan2(dx,dz);hero.root.rotation.y+=Math.atan2(Math.sin(rot-hero.root.rotation.y),Math.cos(rot-hero.root.rotation.y))*Math.min(1,dt*12);}player.y=walkHeight(player.x,player.z);hero.root.position.copy(player);hero.update(t/1000,walk);}
 frameTarget(target);const viewYaw=yaw+(innerWidth<innerHeight?-.07:0);cameraTarget.lerp(target,1-Math.exp(-dt*3));camera.position.set(cameraTarget.x+Math.sin(viewYaw)*Math.cos(pitch)*distance,cameraTarget.y+Math.sin(pitch)*distance,cameraTarget.z+Math.cos(viewYaw)*Math.cos(pitch)*distance);camera.position.y=Math.max(camera.position.y,ground(camera.position.x,camera.position.z)+1.3);camera.lookAt(cameraTarget);renderer.render(world.scene,camera);$('#coords').textContent=`${player.x.toFixed(1)} · ${player.z.toFixed(1)}`;if(rendering)requestAnimationFrame(frame);}
