import * as T from './vendor/three-r170.module.min.js';import {loadAuthoredObservatory,reflectionEnvironment} from './authored.js';
try{
const renderer=new T.WebGLRenderer({canvas:document.querySelector('canvas'),antialias:true});renderer.setPixelRatio(1);renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.88;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color('#101b2a');const env=reflectionEnvironment(renderer);scene.environment=env.texture;const camera=new T.PerspectiveCamera(42,innerWidth/innerHeight,.1,150);
const sun=new T.DirectionalLight('#ffe0ae',4.0);sun.position.set(18,25,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-18,right:18,top:22,bottom:-15,near:1,far:85});sun.shadow.normalBias=.023;sun.shadow.bias=-.00015;sun.target.position.set(0,6,0);scene.add(sun,sun.target);scene.add(new T.HemisphereLight('#97bfff','#333437',.30));const cool=new T.DirectionalLight('#6ea7ec',.7);cool.position.set(-14,14,-12);scene.add(cool);
const model=await loadAuthoredObservatory();scene.add(model.root);const ground=new T.Mesh(new T.PlaneGeometry(160,160),new T.MeshStandardMaterial({color:'#686d71',roughness:.96}));ground.rotation.x=-Math.PI/2;ground.position.y=-.03;ground.receiveShadow=true;scene.add(ground);
const light=new T.PointLight('#ffb45b',35,12,2);light.position.set(0,4,7);scene.add(light);
let yaw=.32,pitch=.15,dist=39;function render(){const target=new T.Vector3(0,8,0);camera.position.set(Math.sin(yaw)*Math.cos(pitch)*dist,8+Math.sin(pitch)*dist,Math.cos(yaw)*Math.cos(pitch)*dist);camera.lookAt(target);renderer.render(scene,camera);}
render();window.__MODULE__={ready:true,render:()=>render(),setView:(y,p,d)=>{yaw=y;pitch=p;dist=d;render();},snapshot:()=>({triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,modelTriangles:model.triangles,contextLost:renderer.getContext().isContextLost()})};let pointer;document.querySelector('canvas').onpointerdown=e=>{pointer=[e.clientX,e.clientY];e.target.setPointerCapture(e.pointerId);};document.querySelector('canvas').onpointermove=e=>{if(!pointer)return;yaw-=(e.clientX-pointer[0])*.004;pitch=Math.max(-.08,Math.min(.65,pitch+(e.clientY-pointer[1])*.003));pointer=[e.clientX,e.clientY];render();};document.querySelector('canvas').onpointerup=()=>pointer=null;document.querySelector('canvas').onwheel=e=>{e.preventDefault();dist=Math.max(20,Math.min(55,dist+e.deltaY*.015));render();};addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();render();});
}catch(e){document.querySelector('#error').textContent=e.message;console.error(e);}
