import * as T from './vendor/three-r170.module.min.js';
import {loadAuthoredObservatory,reflectionEnvironment} from './authored.js';
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));const PI=Math.PI;
let seed=180;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
const hash=(x,z)=>{let n=Math.sin(x*127.1+z*311.7)*43758.5453;return n-Math.floor(n)};
function noise(x,z){let a=Math.floor(x),b=Math.floor(z),u=x-a,v=z-b;u=u*u*(3-2*u);v=v*v*(3-2*v);return (hash(a,b)*(1-u)+hash(a+1,b)*u)*(1-v)+(hash(a,b+1)*(1-u)+hash(a+1,b+1)*u)*v;}
const peaks=[[-70,-40,28,23],[-52,-69,38,24],[-28,-76,20,17],[4,-95,26,30],[36,-69,29,25],[70,-47,34,21],[-85,24,23,28],[81,37,17,24],[5,97,13,30]];
export function ground(x,z){const r=Math.hypot(x,z);let h=0;for(const [a,b,c,d]of peaks)h=Math.max(h,c*Math.exp(-((x-a)**2+(z-b)**2)/(d*d*.85)));const ridge=(1-Math.abs(noise(x*.09,z*.09)*2-1))*.35+.65;return h*ridge*clamp((r-39)/18,0,1)+clamp((r-36)/16,0,1)*(noise(x*.35,z*.35)-.5)*.7;}
export function walkHeight(x,z){let h=.15+ground(x,z);if(Math.abs(x)<3.65&&z>9.6&&z<14.9)h=Math.max(h,1.4-(z-9.6)*.245);return h;}
function canvasTexture(fn,w=512,h=w){const c=document.createElement('canvas');c.width=w;c.height=h;fn(c.getContext('2d'),w,h);return new T.CanvasTexture(c);}
export async function buildWorld(renderer){
const scene=new T.Scene();scene.background=new T.Color('#081324');scene.fog=new T.FogExp2('#152337',.0011);const root=new T.Group();scene.add(root);const collisions=[],environment=reflectionEnvironment(renderer);scene.environment=environment.texture;
const sun=new T.DirectionalLight('#ffe2b6',3.6);sun.position.set(35,27,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-40,right:40,top:38,bottom:-32,near:1,far:120});sun.shadow.normalBias=.028;sun.shadow.bias=-.00015;sun.target.position.set(0,3,5);scene.add(sun,sun.target);scene.add(new T.HemisphereLight('#9bc9fa','#35343b',.34));const fill=new T.DirectionalLight('#6cb8fa',.6);fill.position.set(-30,18,-30);scene.add(fill);
const obs=await loadAuthoredObservatory();scene.add(obs.root);collisions.push({x:0,z:0,r:9.5});const entryLight=new T.PointLight('#ffb154',42,14,2);entryLight.position.set(0,4.4,7);scene.add(entryLight);
const tex=new T.TextureLoader(),[regolith,earthMap]=await Promise.all([tex.loadAsync('./art/regolith.webp'),tex.loadAsync('./art/earth.webp')]);for(const t of [regolith,earthMap])t.colorSpace=T.SRGBColorSpace;regolith.wrapS=regolith.wrapT=T.RepeatWrapping;regolith.repeat.set(60,60);regolith.anisotropy=8;
const rockmap=regolith.clone();rockmap.repeat.set(1.4,1.4);rockmap.needsUpdate=true;
const paving=canvasTexture((c,w,h)=>{c.fillStyle='#d9d7d0';c.fillRect(0,0,w,h);for(let i=0;i<11000;i++){const g=150+random()*70;c.fillStyle=`rgba(${g},${g},${g},.09)`;c.fillRect(random()*w,random()*h,.5+random()*1.4,.5+random()*1.4);}c.fillStyle='rgba(81,76,64,.14)';for(let i=0;i<60;i++)c.fillRect(random()*w,random()*h,2+random()*5,.3);});paving.colorSpace=T.SRGBColorSpace;paving.wrapS=paving.wrapT=T.RepeatWrapping;paving.anisotropy=8;
const mat={white:obs.materials.porcelain,gold:obs.materials.gold,dark:obs.materials.navy,glass:obs.materials.glass,warm:obs.materials.light,cyan:obs.materials.cyan,path:new T.MeshStandardMaterial({color:'#ddd6c5',map:paving,bumpMap:paving,bumpScale:.018,roughness:.64,metalness:.04,envMapIntensity:.4}),soil:new T.MeshStandardMaterial({color:'#aaa7a1',map:regolith,bumpMap:regolith,bumpScale:.046,roughness:.96,envMapIntensity:.15}),rock:new T.MeshStandardMaterial({map:rockmap,color:'#a2a5a8',bumpMap:rockmap,bumpScale:.10,roughness:.92,vertexColors:true}),crystal:new T.MeshPhysicalMaterial({color:'#58d9ed',metalness:.12,roughness:.10,transparent:true,opacity:.87,depthWrite:true,emissive:'#056077',emissiveIntensity:.3,envMapIntensity:1.25}),leaf:new T.MeshStandardMaterial({color:'#487452',roughness:.88})};
// Runtime native geometry uses uncolored materials; authored meshes retain baked AO.
for(const k of ['white','gold','dark','glass','warm','cyan']){mat[k]=mat[k].clone();mat[k].vertexColors=false;}
mat.soil.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\ndiffuseColor.rgb=mix(diffuseColor.rgb,vec3(.35,.345,.335),.43);');};
function mesh(g,m,p,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o;}
const round=new T.Shape();round.moveTo(-.43,-.5);round.lineTo(.43,-.5);round.quadraticCurveTo(.5,-.5,.5,-.43);round.lineTo(.5,.43);round.quadraticCurveTo(.5,.5,.43,.5);round.lineTo(-.43,.5);round.quadraticCurveTo(-.5,.5,-.5,.43);round.lineTo(-.5,-.43);round.quadraticCurveTo(-.5,-.5,-.43,-.5);const boxgeo=new T.ExtrudeGeometry(round,{depth:.94,bevelEnabled:true,bevelThickness:.025,bevelSize:.025,bevelSegments:2,steps:1});boxgeo.translate(0,0,-.47);
function box(p,m,x,y,z,sx,sy,sz){const o=mesh(boxgeo,m,p,x,y,z);o.scale.set(sx,sy,sz);return o;}
function line(p,m,points,r=.03){return mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p))),Math.max(8,points.length*3),r,6,false),m,p);}
// Deliberately composed continuous ridge mesh, rather than repeated polygon mountains.
const terrain=new T.PlaneGeometry(280,280,200,200);terrain.rotateX(-PI/2);const tp=terrain.attributes.position;for(let i=0;i<tp.count;i++){let x=tp.getX(i),z=tp.getZ(i);tp.setY(i,ground(x,z)-.035+(noise(x*1.3,z*1.3)-.5)*.045);}terrain.computeVertexNormals();mesh(terrain,mat.soil,root).castShadow=false;
// Individual broad paving slabs follow the approach, with flush gold inlays and dark joints.
function path(points,width){const curve=new T.CatmullRomCurve3(points.map(v=>new T.Vector3(...v))),len=curve.getLength(),count=Math.ceil(len/1.25);for(let i=0;i<count;i++){const n=4,v=[],uv=[],idx=[];for(let j=0;j<=n;j++){const t=(i+(j+.012)/(n+.024))/count,q=curve.getPointAt(t),d=curve.getTangentAt(t),side=new T.Vector3(-d.z,0,d.x);for(const s of [-1,1]){const a=q.clone().addScaledVector(side,s*width/2);v.push(a.x,a.y,a.z);uv.push(s===-1?0:width/2,j/n*.6);}if(j<n){let k=j*2;idx.push(k,k+1,k+2,k+1,k+3,k+2);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();mesh(g,mat.path,root).castShadow=false;}
for(const side of [-1,1]){const v=[],idx=[];for(let i=0;i<=100;i++){const t=i/100,q=curve.getPointAt(t),d=curve.getTangentAt(t),n=new T.Vector3(-d.z,0,d.x);for(const k of [-1,1]){let p=q.clone().addScaledVector(n,side*(width/2+.02)+k*.075);v.push(p.x,p.y+.012,p.z);}if(i<100){const k=i*2;idx.push(k,k+1,k+2,k+1,k+3,k+2);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();mesh(g,mat.gold,root).castShadow=false;}}
path([[0,.14,43],[-2,.14,34],[-3,.14,25],[0,.14,18],[0,.14,14.9]],6.8);path([[-28,.14,7],[-18,.14,12],[-8,.14,17],[-1,.14,18]],3.8);path([[26,.14,9],[17,.14,12],[9,.14,17],[1,.14,18]],3.8);
// Greenhouse galleries: thick curved ceramic arch profiles and inset glazing.
function gallery(x,z,length){const g=new T.Group();g.position.set(x,0,z);root.add(g);box(g,mat.dark,0,.38,0,length,.76,5.0);box(g,mat.white,0,.83,0,length,.42,5.08);box(g,mat.gold,0,1.08,0,length,.09,5.14);
const cross=new T.Shape();cross.moveTo(-2.50,1.09);cross.lineTo(-2.50,3.07);cross.absarc(0,3.07,2.50,PI,0,true);cross.lineTo(2.50,1.09);cross.lineTo(2.08,1.09);cross.lineTo(2.08,3.07);cross.absarc(0,3.07,2.08,0,PI,false);cross.lineTo(-2.08,1.09);cross.closePath();const frame=new T.ExtrudeGeometry(cross,{depth:.50,bevelEnabled:true,bevelSegments:2,bevelSize:.055,bevelThickness:.045,curveSegments:18});frame.rotateY(PI/2);frame.translate(-.25,0,0);
for(let i=0;i<=Math.round(length/3);i++){const xx=-length/2+i*length/Math.round(length/3);mesh(frame,mat.white,g,xx,0,0);const pp=[];for(let j=0;j<=30;j++){let a=PI*j/30;pp.push([xx+.26,3.07+Math.sin(a)*2.43,-Math.cos(a)*2.43]);}line(g,mat.gold,[[xx+.26,1.10,-2.43],...pp,[xx+.26,1.1,2.43]],.035);}
const glass=new T.CylinderGeometry(2.39,2.39,length,32,1,true,0,PI);glass.rotateZ(PI/2);glass.rotateY(PI/2);const gl=mesh(glass,mat.glass,g,0,3.07,0);gl.castShadow=false;for(const s of [-1,1]){const pane=box(g,mat.glass,0,2.07,s*2.37,length,2.0,.03);pane.castShadow=false;box(g,mat.gold,0,1.1,s*2.44,length,.08,.09);box(g,mat.gold,0,3.08,s*2.44,length,.08,.09);box(g,mat.warm,0,4.45,s*1.36,length,.022,.033);}
for(let i=0;i<Math.floor(length/1.75);i++){let xx=-length/2+1+i*1.75;for(const s of [-1,1]){box(g,mat.white,xx,1.35,s*1.5,1.2,.50,.62);for(let j=0;j<3;j++){const stem=new T.Group();stem.position.set(xx+(j-1)*.28,1.62,s*1.5);g.add(stem);line(stem,mat.leaf,[[0,0,0],[.07,.5,0],[-.03,1.1,0]],.015);for(let k=0;k<5;k++){const leaf=mesh(new T.SphereGeometry(1,8,5),mat.leaf,stem,Math.sin(k*2.5)*.15,.25+k*.17,Math.cos(k*2.5)*.15);leaf.scale.set(.21,.055,.075);leaf.rotation.z=k*1.7;}}}}collisions.push({x,z,w:length,d:5.5});}
gallery(-16,-2,14);gallery(16,-2,14);
// A few sculptural geological masses have coherent planes, strata and dust-filled crevices.
function rockGeometry(salt){const g=new T.SphereGeometry(1,32,18),p=g.attributes.position,colors=[];const planes=[];for(let k=0;k<13;k++){const a=k*2.399+salt,b=.22+((k*7)%13)/13*1.15;planes.push([new T.Vector3(Math.cos(a)*Math.sin(b),Math.cos(b),Math.sin(a)*Math.sin(b)),.65+(k%4)*.10]);}for(let i=0;i<p.count;i++){let v=new T.Vector3(p.getX(i),p.getY(i),p.getZ(i)),r=1.0;for(const [n,d]of planes){const dot=v.dot(n);if(dot>.2)r=Math.min(r,d/dot);}const erosion=1+.025*Math.sin(v.x*33+salt)*Math.sin(v.z*27+v.y*10);v.multiplyScalar(r*erosion);v.y=Math.max(v.y,-.26);p.setXYZ(i,v.x,v.y,v.z);const c=.69+.18*(v.y+.3)+.09*noise(v.x*9+salt,v.z*9);colors.push(c,c*.99,c*.98);}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;}
const rocks=[0,1,2,3].map(rockGeometry);for(const [x,z,scale,rot]of [[10,28,3.25,.2],[13,24,2.15,1.1],[-10,23,2.4,2],[-14,19,2.9,.7],[14,14,1.8,2.8],[-9,8,1.8,.3],[23,8,2.7,1.4]]){const o=mesh(rocks[Math.floor(scale*3)%4],mat.rock,root,x,scale*.23,z);o.scale.set(scale,scale*.8,scale*1.25);o.rotation.y=rot;collisions.push({x,z,r:scale*.7});}
for(let i=0;i<38;i++){let a=random()*PI*2,r=17+random()*50,x=Math.sin(a)*r,z=Math.cos(a)*r;if(Math.abs(x)<7&&z>8||Math.abs(x)<27&&z<4&&z>-8)continue;const s=.12+random()*.8,o=mesh(rocks[i%4],mat.rock,root,x,ground(x,z)+s*.20,z);o.scale.set(s,s*.65,s*1.2);o.rotation.y=a;o.castShadow=s>.45;}
const pebbleMat=mat.rock.clone();pebbleMat.vertexColors=false;const gravel=new T.InstancedMesh(new T.IcosahedronGeometry(1,0),pebbleMat,680),dummy=new T.Object3D();for(let i=0;i<680;i++){let a=random()*PI*2,r=12+random()*37,x=Math.sin(a)*r,z=9+Math.cos(a)*r;if(Math.abs(x)<4&&z>14)x+=x<0?-4:4;const s=.025+random()*.12;dummy.position.set(x,ground(x,z)+.025,z);dummy.scale.set(s,s*.6,s*.8);dummy.rotation.set(random(),a,random());dummy.updateMatrix();gravel.setMatrixAt(i,dummy.matrix);}gravel.receiveShadow=true;root.add(gravel);
function crystalCluster(x,z,s){const cluster=new T.Group();cluster.position.set(x,.06,z);root.add(cluster);for(let i=0;i<7;i++){const a=i*2.399,r=i===0?0:.38+random()*.72,h=i===0?3.4:.9+random()*1.9,w=.17+random()*.15;const v=[],idx=[];for(let ring=0;ring<3;ring++)for(let k=0;k<6;k++){const aa=k*PI/3;v.push(Math.cos(aa)*w*(ring===2?.58:1),ring===0?0:ring===1?h*.77:h*.90,Math.sin(aa)*w*(ring===2?.58:1));}v.push(.04,h,0);for(let k=0;k<6;k++){let n=(k+1)%6;idx.push(k,n,k+6,n,n+6,k+6,k+6,n+6,k+12,n+6,n+12,k+12,k+12,n+12,18);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(v,3));geo.setIndex(idx);const flat=geo.toNonIndexed();flat.computeVertexNormals();const o=mesh(flat,mat.crystal,cluster,Math.sin(a)*r*s,0,Math.cos(a)*r*s);o.scale.setScalar(s);o.rotation.set(Math.cos(a)*.12,a,Math.sin(a)*.14);o.castShadow=false;}collisions.push({x,z,r:1.3*s});}
for(const [x,z,s]of [[11,26,1.4],[-10,13,1.0],[-22,8,.85],[20,12,.9],[10,8,.58],[-7,9,.6]])crystalCluster(x,z,s);
// Architectural light blades with a broad supported base, deliberately sparse.
for(const [x,z]of [[8,18],[-9,15],[22,8],[-22,5]]){box(root,mat.dark,x,.28,z,.52,.56,.58);box(root,mat.white,x,1.7,z,.36,2.8,.40);box(root,mat.gold,x+.2,1.72,z,.06,2.85,.38);box(root,mat.warm,x,1.85,z+.215,.16,2.23,.025);}
const skyMap=canvasTexture((c,w,h)=>{c.fillStyle='#051020';c.fillRect(0,0,w,h);for(let k=0;k<64;k++){let x=k*w/64,y=h*.42+Math.sin(k*.15)*h*.1,g=c.createRadialGradient(x,y,2,x,y,120);g.addColorStop(0,'rgba(18,115,135,.035)');g.addColorStop(1,'rgba(3,12,29,0)');c.fillStyle=g;c.fillRect(x-120,y-120,240,240);}for(let i=0;i<2800;i++){c.fillStyle=`rgba(201,225,255,${.18+random()*.58})`;c.fillRect(random()*w,random()*h,1,1);}},2048,1024);skyMap.colorSpace=T.SRGBColorSpace;const sky=mesh(new T.SphereGeometry(300,32,20),new T.MeshBasicMaterial({map:skyMap,side:T.BackSide,fog:false}),scene);sky.castShadow=sky.receiveShadow=false;
const earth=mesh(new T.SphereGeometry(26,48,32),new T.MeshStandardMaterial({map:earthMap,roughness:.95,emissive:'#1b4a65',emissiveIntensity:.28,fog:false,envMapIntensity:.12}),scene,56,44,-130);earth.rotation.set(.12,-1.2,.16);earth.castShadow=earth.receiveShadow=false;
const atmosphere=mesh(new T.SphereGeometry(26.4,48,32),new T.ShaderMaterial({side:T.BackSide,transparent:true,depthWrite:false,uniforms:{color:{value:new T.Color('#559fcc')}},vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'uniform vec3 color;varying vec3 n;varying vec3 v;void main(){gl_FragColor=vec4(color,pow(1.-abs(dot(normalize(n),normalize(v))),3.)*.65);}'}),scene,56,44,-130);atmosphere.castShadow=false;
// Batch static geometry by material, preserving model-generated AO on the observatory.
root.updateMatrixWorld(true);const batches=new Map();root.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||o.material.transparent||Array.isArray(o.material))return;const key=o.material.uuid+o.castShadow;if(!batches.has(key))batches.set(key,[]);batches.get(key).push(o);});for(const list of batches.values()){if(list.length<2)continue;const parts=list.map(o=>{let g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(o.matrixWorld);return g;}),g=new T.BufferGeometry();for(const key of ['position','normal','uv','color']){if(parts.some(p=>!p.attributes[key]))continue;const n=parts[0].attributes[key].itemSize,arr=new Float32Array(parts.reduce((sum,p)=>sum+p.attributes[key].array.length,0));let off=0;for(const p of parts){arr.set(p.attributes[key].array,off);off+=p.attributes[key].array.length;}g.setAttribute(key,new T.BufferAttribute(arr,n));}const m=new T.Mesh(g,list[0].material);m.castShadow=list[0].castShadow;m.receiveShadow=true;scene.add(m);list.forEach(o=>o.removeFromParent());parts.forEach(g=>g.dispose());}
return {scene,collisions,sun,earth,mat,dispose(){environment.dispose()}};
}
