# Generates locales/daily-retention.js (merged into MKTYLocales[code].strings at load).
import json
K=["EVERY UTC DAY","MOON SIGNAL & STREAK","LOGIN STREAK","Check in every UTC day. Rewards grow to day 7, then stay at the cap.","CHECK IN","Day 0","MOON SIGNAL","Daily cipher: decode the lore word sent in Morse code.","Tap a symbol to replay it. Enter dots and dashes, then press LETTER — or type the word.","LETTER","TYPE THE WORD","MORSE KEY","TRANSMIT ANSWER","YOUTUBE CODE WORD","Watch the new MOONKATTY video and enter the code word said or shown in it. Each code pays once.","CODE WORD","REDEEM","Codes expire — new ones appear with new videos.","Daily signals","Dot","Dash","Delete","DAILY SIGNALS 📡",
"Once per UTC day: login streak +3 to +25 ⭐ (day 7 cap; one shield per week saves one missed day), Moon Signal cipher +15 ⭐ with 5 attempts, and YouTube code words up to +50 ⭐ each, once per code. All are verified by the server through Telegram.",
"Already checked in today","Already decoded today","Attempts left: {n} / {m}","BALANCE LOCKED","CHECK IN +{n} ⭐","CHECKED IN ✓","Check-in +{n} ⭐","Code accepted! +{n} ⭐","Connection lost — try again","DEMO · local preview — rewards verified only in Telegram","Day {n}","Decoded ✓ +{n} ⭐","D{n}","Enter the code word from the video","NO ATTEMPTS — NEW SIGNAL AT 00:00 UTC","Need {n} letters","No attempts left today","SERVER VERIFIED · Telegram","SIGNAL DECODED ✓","Shield saved your streak! +{n} ⭐","Signal decoded! +{n} ⭐","TRANSMIT ANSWER +{n} ⭐","Unknown Morse letter — try again","Unknown or expired code","Wrong word — signal distorted","You already used this code","🛡 Shield ready — saves 1 missed day this week","🛡 Shield used this week"]
L={}
L['ru']=["КАЖДЫЙ ДЕНЬ UTC","СИГНАЛ ЛУНЫ И СТРИК","СТРИК ВХОДА","Отмечайся каждый день (UTC). Награда растёт до 7-го дня, дальше — максимум.","ОТМЕТИТЬСЯ","День 0","СИГНАЛ ЛУНЫ","Ежедневный шифр: расшифруй слово из истории, переданное азбукой Морзе.","Нажми на символ, чтобы повторить его. Вводи точки и тире и жми БУКВА — или напечатай слово.","БУКВА","ВВЕДИ СЛОВО","АЗБУКА МОРЗЕ","ПЕРЕДАТЬ ОТВЕТ","КОДОВОЕ СЛОВО YOUTUBE","Посмотри новое видео MOONKATTY и введи кодовое слово, которое там прозвучит или появится. Каждый код — один раз.","КОДОВОЕ СЛОВО","ПОЛУЧИТЬ","У кодов есть срок — новые появляются с новыми видео.","Ежедневные сигналы","Точка","Тире","Удалить","ЕЖЕДНЕВНЫЕ СИГНАЛЫ 📡",
"Раз в сутки (UTC): стрик входа от +3 до +25 ⭐ (максимум с 7-го дня; один щит в неделю спасает один пропущенный день), шифр «Сигнал Луны» +15 ⭐ и 5 попыток, кодовые слова из YouTube — до +50 ⭐ за код, один раз. Всё проверяет сервер через Telegram.",
"Сегодня уже отмечено","Сегодня уже расшифровано","Осталось попыток: {n} / {m}","БАЛАНС ЗАКРЫТ","ОТМЕТИТЬСЯ +{n} ⭐","ОТМЕЧЕНО ✓","Отметка +{n} ⭐","Код принят! +{n} ⭐","Нет связи — попробуй ещё раз","DEMO · локальный просмотр — награды проверяются только в Telegram","День {n}","Расшифровано ✓ +{n} ⭐","Д{n}","Введи кодовое слово из видео","ПОПЫТОК НЕТ — НОВЫЙ СИГНАЛ В 00:00 UTC","Нужно букв: {n}","Попытки на сегодня закончились","ПРОВЕРЕНО СЕРВЕРОМ · Telegram","СИГНАЛ РАСШИФРОВАН ✓","Щит спас твой стрик! +{n} ⭐","Сигнал расшифрован! +{n} ⭐","ПЕРЕДАТЬ ОТВЕТ +{n} ⭐","Неизвестная буква Морзе — попробуй снова","Неизвестный или просроченный код","Неверное слово — сигнал искажён","Ты уже использовал этот код","🛡 Щит готов — спасёт 1 пропуск на этой неделе","🛡 Щит на этой неделе использован"]
L['uk']=["ЩОДНЯ UTC","СИГНАЛ МІСЯЦЯ І СТРІК","СТРІК ВХОДУ","Відмічайся щодня (UTC). Нагорода зростає до 7-го дня, далі — максимум.","ВІДМІТИТИСЯ","День 0","СИГНАЛ МІСЯЦЯ","Щоденний шифр: розшифруй слово з історії, передане азбукою Морзе.","Торкнися символу, щоб повторити його. Вводь крапки й тире та тисни ЛІТЕРА — або надрукуй слово.","ЛІТЕРА","ВВЕДИ СЛОВО","АЗБУКА МОРЗЕ","ПЕРЕДАТИ ВІДПОВІДЬ","КОДОВЕ СЛОВО YOUTUBE","Переглянь нове відео MOONKATTY і введи кодове слово, яке там прозвучить або з’явиться. Кожен код — один раз.","КОДОВЕ СЛОВО","ОТРИМАТИ","Коди мають термін дії — нові з’являються з новими відео.","Щоденні сигнали","Крапка","Тире","Видалити","ЩОДЕННІ СИГНАЛИ 📡",
"Раз на добу (UTC): стрік входу від +3 до +25 ⭐ (максимум із 7-го дня; один щит на тиждень рятує один пропущений день), шифр «Сигнал Місяця» +15 ⭐ і 5 спроб, кодові слова з YouTube — до +50 ⭐ за код, один раз. Усе перевіряє сервер через Telegram.",
"Сьогодні вже відмічено","Сьогодні вже розшифровано","Залишилось спроб: {n} / {m}","БАЛАНС ЗАКРИТО","ВІДМІТИТИСЯ +{n} ⭐","ВІДМІЧЕНО ✓","Відмітка +{n} ⭐","Код прийнято! +{n} ⭐","Немає зв’язку — спробуй ще","DEMO · локальний перегляд — нагороди перевіряються лише в Telegram","День {n}","Розшифровано ✓ +{n} ⭐","Д{n}","Введи кодове слово з відео","СПРОБ НЕМАЄ — НОВИЙ СИГНАЛ О 00:00 UTC","Потрібно літер: {n}","Спроби на сьогодні закінчились","ПЕРЕВІРЕНО СЕРВЕРОМ · Telegram","СИГНАЛ РОЗШИФРОВАНО ✓","Щит урятував твій стрік! +{n} ⭐","Сигнал розшифровано! +{n} ⭐","ПЕРЕДАТИ ВІДПОВІДЬ +{n} ⭐","Невідома літера Морзе — спробуй знову","Невідомий або прострочений код","Неправильне слово — сигнал спотворено","Ти вже використав цей код","🛡 Щит готовий — врятує 1 пропуск цього тижня","🛡 Щит цього тижня використано"]
L['es']=["CADA DÍA UTC","SEÑAL LUNAR Y RACHA","RACHA DE ENTRADA","Entra cada día UTC. La recompensa crece hasta el día 7 y luego se mantiene en el tope.","REGISTRARSE","Día 0","SEÑAL LUNAR","Cifrado diario: descifra la palabra de la historia enviada en código Morse.","Toca un símbolo para repetirlo. Introduce puntos y rayas y pulsa LETRA, o escribe la palabra.","LETRA","ESCRIBE LA PALABRA","CLAVE MORSE","TRANSMITIR RESPUESTA","PALABRA CLAVE DE YOUTUBE","Mira el nuevo vídeo de MOONKATTY e introduce la palabra clave que se dice o muestra en él. Cada código paga una vez.","PALABRA CLAVE","CANJEAR","Los códigos caducan; aparecen nuevos con cada vídeo.","Señales diarias","Punto","Raya","Borrar","SEÑALES DIARIAS 📡",
"Una vez por día UTC: racha de entrada de +3 a +25 ⭐ (tope desde el día 7; un escudo por semana salva un día perdido), cifrado Señal Lunar +15 ⭐ con 5 intentos y palabras clave de YouTube hasta +50 ⭐ cada una, una vez por código. Todo lo verifica el servidor mediante Telegram.",
"Ya te registraste hoy","Ya descifrado hoy","Intentos restantes: {n} / {m}","SALDO BLOQUEADO","REGISTRARSE +{n} ⭐","REGISTRADO ✓","Registro +{n} ⭐","¡Código aceptado! +{n} ⭐","Sin conexión: inténtalo de nuevo","DEMO · vista local: las recompensas solo se verifican en Telegram","Día {n}","Descifrado ✓ +{n} ⭐","D{n}","Introduce la palabra clave del vídeo","SIN INTENTOS — NUEVA SEÑAL A LAS 00:00 UTC","Faltan letras: {n}","No quedan intentos hoy","VERIFICADO POR SERVIDOR · Telegram","SEÑAL DESCIFRADA ✓","¡El escudo salvó tu racha! +{n} ⭐","¡Señal descifrada! +{n} ⭐","TRANSMITIR RESPUESTA +{n} ⭐","Letra Morse desconocida: inténtalo de nuevo","Código desconocido o caducado","Palabra incorrecta: señal distorsionada","Ya usaste este código","🛡 Escudo listo: salva 1 día perdido esta semana","🛡 Escudo usado esta semana"]
L['pt']=["TODO DIA UTC","SINAL LUNAR E SEQUÊNCIA","SEQUÊNCIA DE LOGIN","Faça check-in todo dia UTC. A recompensa cresce até o dia 7 e depois fica no limite.","FAZER CHECK-IN","Dia 0","SINAL LUNAR","Cifra diária: decifre a palavra da história enviada em código Morse.","Toque num símbolo para repeti-lo. Digite pontos e traços e toque LETRA — ou escreva a palavra.","LETRA","DIGITE A PALAVRA","TABELA MORSE","TRANSMITIR RESPOSTA","PALAVRA-CÓDIGO DO YOUTUBE","Assista ao novo vídeo MOONKATTY e digite a palavra-código dita ou mostrada nele. Cada código paga uma vez.","PALAVRA-CÓDIGO","RESGATAR","Os códigos expiram — novos aparecem com novos vídeos.","Sinais diários","Ponto","Traço","Apagar","SINAIS DIÁRIOS 📡",
"Uma vez por dia UTC: sequência de login de +3 a +25 ⭐ (limite a partir do dia 7; um escudo por semana salva um dia perdido), cifra Sinal Lunar +15 ⭐ com 5 tentativas e palavras-código do YouTube até +50 ⭐ cada, uma vez por código. Tudo é verificado pelo servidor via Telegram.",
"Check-in de hoje já feito","Já decifrado hoje","Tentativas restantes: {n} / {m}","SALDO BLOQUEADO","CHECK-IN +{n} ⭐","CHECK-IN FEITO ✓","Check-in +{n} ⭐","Código aceito! +{n} ⭐","Sem conexão — tente novamente","DEMO · prévia local — recompensas verificadas só no Telegram","Dia {n}","Decifrado ✓ +{n} ⭐","D{n}","Digite a palavra-código do vídeo","SEM TENTATIVAS — NOVO SINAL ÀS 00:00 UTC","São necessárias {n} letras","Sem tentativas hoje","VERIFICADO PELO SERVIDOR · Telegram","SINAL DECIFRADO ✓","O escudo salvou sua sequência! +{n} ⭐","Sinal decifrado! +{n} ⭐","TRANSMITIR RESPOSTA +{n} ⭐","Letra Morse desconhecida — tente de novo","Código desconhecido ou expirado","Palavra errada — sinal distorcido","Você já usou este código","🛡 Escudo pronto — salva 1 dia perdido nesta semana","🛡 Escudo usado nesta semana"]
L['de']=["JEDEN UTC-TAG","MONDSIGNAL & SERIE","LOGIN-SERIE","Melde dich jeden UTC-Tag an. Die Belohnung steigt bis Tag 7 und bleibt dann am Maximum.","EINCHECKEN","Tag 0","MONDSIGNAL","Tägliche Chiffre: Entschlüssle das Story-Wort im Morsecode.","Tippe ein Symbol, um es abzuspielen. Gib Punkte und Striche ein und drücke BUCHSTABE – oder tippe das Wort.","BUCHSTABE","WORT EINGEBEN","MORSE-TABELLE","ANTWORT SENDEN","YOUTUBE-CODEWORT","Sieh dir das neue MOONKATTY-Video an und gib das darin genannte oder gezeigte Codewort ein. Jeder Code zahlt einmal.","CODEWORT","EINLÖSEN","Codes laufen ab – neue kommen mit neuen Videos.","Tägliche Signale","Punkt","Strich","Löschen","TÄGLICHE SIGNALE 📡",
"Einmal pro UTC-Tag: Login-Serie +3 bis +25 ⭐ (Maximum ab Tag 7; ein Schild pro Woche rettet einen verpassten Tag), Mondsignal-Chiffre +15 ⭐ mit 5 Versuchen und YouTube-Codewörter bis +50 ⭐ je Code, einmal pro Code. Alles wird vom Server über Telegram geprüft.",
"Heute schon eingecheckt","Heute schon entschlüsselt","Versuche übrig: {n} / {m}","GUTHABEN GESPERRT","EINCHECKEN +{n} ⭐","EINGECHECKT ✓","Check-in +{n} ⭐","Code akzeptiert! +{n} ⭐","Keine Verbindung – erneut versuchen","DEMO · lokale Vorschau – Belohnungen nur in Telegram geprüft","Tag {n}","Entschlüsselt ✓ +{n} ⭐","T{n}","Gib das Codewort aus dem Video ein","KEINE VERSUCHE – NEUES SIGNAL UM 00:00 UTC","{n} Buchstaben nötig","Heute keine Versuche mehr","VOM SERVER GEPRÜFT · Telegram","SIGNAL ENTSCHLÜSSELT ✓","Der Schild hat deine Serie gerettet! +{n} ⭐","Signal entschlüsselt! +{n} ⭐","ANTWORT SENDEN +{n} ⭐","Unbekannter Morse-Buchstabe – nochmal","Unbekannter oder abgelaufener Code","Falsches Wort – Signal verzerrt","Diesen Code hast du schon benutzt","🛡 Schild bereit – rettet diese Woche 1 verpassten Tag","🛡 Schild diese Woche verbraucht"]
L['fr']=["CHAQUE JOUR UTC","SIGNAL LUNAIRE & SÉRIE","SÉRIE DE CONNEXION","Pointe chaque jour UTC. La récompense augmente jusqu’au jour 7, puis reste au plafond.","POINTER","Jour 0","SIGNAL LUNAIRE","Chiffre du jour : décode le mot de l’histoire envoyé en morse.","Touche un symbole pour le rejouer. Saisis points et traits puis appuie sur LETTRE — ou tape le mot.","LETTRE","TAPE LE MOT","TABLE MORSE","TRANSMETTRE","MOT-CODE YOUTUBE","Regarde la nouvelle vidéo MOONKATTY et saisis le mot-code dit ou affiché. Chaque code paie une fois.","MOT-CODE","VALIDER","Les codes expirent — de nouveaux arrivent avec les vidéos.","Signaux quotidiens","Point","Trait","Effacer","SIGNAUX QUOTIDIENS 📡",
"Une fois par jour UTC : série de connexion de +3 à +25 ⭐ (plafond dès le jour 7 ; un bouclier par semaine sauve un jour manqué), chiffre Signal lunaire +15 ⭐ avec 5 essais, et mots-codes YouTube jusqu’à +50 ⭐ chacun, une fois par code. Tout est vérifié par le serveur via Telegram.",
"Déjà pointé aujourd’hui","Déjà décodé aujourd’hui","Essais restants : {n} / {m}","SOLDE VERROUILLÉ","POINTER +{n} ⭐","POINTÉ ✓","Pointage +{n} ⭐","Code accepté ! +{n} ⭐","Connexion perdue — réessaie","DEMO · aperçu local — récompenses vérifiées seulement dans Telegram","Jour {n}","Décodé ✓ +{n} ⭐","J{n}","Saisis le mot-code de la vidéo","PLUS D’ESSAIS — NOUVEAU SIGNAL À 00:00 UTC","Il faut {n} lettres","Plus d’essais aujourd’hui","VÉRIFIÉ PAR LE SERVEUR · Telegram","SIGNAL DÉCODÉ ✓","Le bouclier a sauvé ta série ! +{n} ⭐","Signal décodé ! +{n} ⭐","TRANSMETTRE +{n} ⭐","Lettre morse inconnue — réessaie","Code inconnu ou expiré","Mauvais mot — signal brouillé","Tu as déjà utilisé ce code","🛡 Bouclier prêt — sauve 1 jour manqué cette semaine","🛡 Bouclier utilisé cette semaine"]
L['it']=["OGNI GIORNO UTC","SEGNALE LUNARE E SERIE","SERIE DI ACCESSI","Fai check-in ogni giorno UTC. La ricompensa cresce fino al giorno 7, poi resta al massimo.","CHECK-IN","Giorno 0","SEGNALE LUNARE","Cifrario quotidiano: decifra la parola della storia inviata in codice Morse.","Tocca un simbolo per ripeterlo. Inserisci punti e linee e premi LETTERA, oppure scrivi la parola.","LETTERA","SCRIVI LA PAROLA","TABELLA MORSE","TRASMETTI RISPOSTA","PAROLA IN CODICE YOUTUBE","Guarda il nuovo video MOONKATTY e inserisci la parola in codice detta o mostrata. Ogni codice paga una volta.","PAROLA IN CODICE","RISCATTA","I codici scadono: nuovi arrivano con i nuovi video.","Segnali quotidiani","Punto","Linea","Cancella","SEGNALI QUOTIDIANI 📡",
"Una volta per giorno UTC: serie di accessi da +3 a +25 ⭐ (massimo dal giorno 7; uno scudo a settimana salva un giorno perso), cifrario Segnale lunare +15 ⭐ con 5 tentativi e parole in codice YouTube fino a +50 ⭐ ciascuna, una volta per codice. Tutto è verificato dal server tramite Telegram.",
"Check-in già fatto oggi","Già decifrato oggi","Tentativi rimasti: {n} / {m}","SALDO BLOCCATO","CHECK-IN +{n} ⭐","CHECK-IN FATTO ✓","Check-in +{n} ⭐","Codice accettato! +{n} ⭐","Connessione persa: riprova","DEMO · anteprima locale: ricompense verificate solo in Telegram","Giorno {n}","Decifrato ✓ +{n} ⭐","G{n}","Inserisci la parola in codice del video","NESSUN TENTATIVO — NUOVO SEGNALE ALLE 00:00 UTC","Servono {n} lettere","Tentativi finiti per oggi","VERIFICATO DAL SERVER · Telegram","SEGNALE DECIFRATO ✓","Lo scudo ha salvato la tua serie! +{n} ⭐","Segnale decifrato! +{n} ⭐","TRASMETTI RISPOSTA +{n} ⭐","Lettera Morse sconosciuta: riprova","Codice sconosciuto o scaduto","Parola errata: segnale distorto","Hai già usato questo codice","🛡 Scudo pronto: salva 1 giorno perso questa settimana","🛡 Scudo usato questa settimana"]
L['tr']=["HER UTC GÜNÜ","AY SİNYALİ VE SERİ","GİRİŞ SERİSİ","Her UTC günü giriş yap. Ödül 7. güne kadar artar, sonra en üst seviyede kalır.","GİRİŞ YAP","Gün 0","AY SİNYALİ","Günlük şifre: Mors koduyla gönderilen hikâye kelimesini çöz.","Tekrar oynatmak için bir sembole dokun. Nokta ve çizgi gir, sonra HARF'e bas — ya da kelimeyi yaz.","HARF","KELİMEYİ YAZ","MORS TABLOSU","CEVABI GÖNDER","YOUTUBE KOD KELİMESİ","Yeni MOONKATTY videosunu izle ve içinde söylenen ya da gösterilen kod kelimesini gir. Her kod bir kez ödül verir.","KOD KELİMESİ","KULLAN","Kodların süresi dolar — yeni videolarla yenileri gelir.","Günlük sinyaller","Nokta","Çizgi","Sil","GÜNLÜK SİNYALLER 📡",
"Her UTC gününde bir kez: giriş serisi +3 ile +25 ⭐ arası (7. günden itibaren üst sınır; haftada bir kalkan kaçırılan bir günü kurtarır), Ay Sinyali şifresi 5 denemeyle +15 ⭐ ve YouTube kod kelimeleri kod başına en fazla +50 ⭐, kod başına bir kez. Hepsi sunucu tarafından Telegram üzerinden doğrulanır.",
"Bugün zaten giriş yapıldı","Bugün zaten çözüldü","Kalan deneme: {n} / {m}","BAKİYE KİLİTLİ","GİRİŞ YAP +{n} ⭐","GİRİŞ YAPILDI ✓","Giriş +{n} ⭐","Kod kabul edildi! +{n} ⭐","Bağlantı yok — tekrar dene","DEMO · yerel önizleme — ödüller yalnızca Telegram'da doğrulanır","Gün {n}","Çözüldü ✓ +{n} ⭐","G{n}","Videodaki kod kelimesini gir","DENEME KALMADI — YENİ SİNYAL 00:00 UTC","{n} harf gerekli","Bugün deneme hakkı kalmadı","SUNUCU DOĞRULADI · Telegram","SİNYAL ÇÖZÜLDÜ ✓","Kalkan serini kurtardı! +{n} ⭐","Sinyal çözüldü! +{n} ⭐","CEVABI GÖNDER +{n} ⭐","Bilinmeyen Mors harfi — tekrar dene","Bilinmeyen veya süresi dolmuş kod","Yanlış kelime — sinyal bozuldu","Bu kodu zaten kullandın","🛡 Kalkan hazır — bu hafta 1 kaçırılan günü kurtarır","🛡 Bu hafta kalkan kullanıldı"]
L['he']=["כל יום UTC","אות הירח ורצף","רצף כניסות","היכנסו כל יום UTC. הפרס גדל עד היום ה-7 ואז נשאר בתקרה.","צ׳ק-אין","יום 0","אות הירח","צופן יומי: פענחו את מילת העלילה שנשלחה בקוד מורס.","הקישו על סמל כדי להשמיע אותו שוב. הזינו נקודות וקווים ולחצו אות — או הקלידו את המילה.","אות","הקלידו את המילה","טבלת מורס","שידור תשובה","מילת קוד מ-YOUTUBE","צפו בסרטון החדש של MOONKATTY והזינו את מילת הקוד שנאמרת או מוצגת בו. כל קוד משלם פעם אחת.","מילת קוד","מימוש","לקודים יש תוקף — חדשים מגיעים עם סרטונים חדשים.","אותות יומיים","נקודה","קו","מחיקה","אותות יומיים 📡",
"פעם ביום UTC: רצף כניסות ‎+3 עד ‎+25 ⭐ (תקרה מהיום ה-7; מגן אחד בשבוע מציל יום שהוחמץ), צופן אות הירח ‎+15 ⭐ עם 5 ניסיונות, ומילות קוד מ-YouTube עד ‎+50 ⭐ לקוד, פעם אחת לכל קוד. הכול מאומת בשרת דרך Telegram.",
"כבר עשית צ׳ק-אין היום","כבר פוענח היום","ניסיונות שנותרו: {n} / {m}","היתרה נעולה","צ׳ק-אין ‎+{n} ⭐","בוצע צ׳ק-אין ✓","צ׳ק-אין ‎+{n} ⭐","הקוד התקבל! ‎+{n} ⭐","אין חיבור — נסו שוב","DEMO · תצוגה מקומית — פרסים מאומתים רק ב-Telegram","יום {n}","פוענח ✓ ‎+{n} ⭐","י{n}","הזינו את מילת הקוד מהסרטון","אין ניסיונות — אות חדש ב-00:00 UTC","נדרשות {n} אותיות","נגמרו הניסיונות להיום","מאומת בשרת · Telegram","האות פוענח ✓","המגן הציל את הרצף! ‎+{n} ⭐","האות פוענח! ‎+{n} ⭐","שידור תשובה ‎+{n} ⭐","אות מורס לא מוכרת — נסו שוב","קוד לא מוכר או שפג תוקפו","מילה שגויה — האות שובש","כבר השתמשת בקוד הזה","🛡 המגן מוכן — מציל יום אחד שהוחמץ השבוע","🛡 המגן נוצל השבוע"]
L['ko']=["매일 UTC","달의 신호 & 연속 출석","연속 출석","매일 UTC 기준으로 출석하세요. 보상은 7일째까지 늘어나고 이후 최대치로 유지됩니다.","출석","0일","달의 신호","일일 암호: 모스 부호로 전송된 스토리 단어를 해독하세요.","기호를 탭하면 다시 재생됩니다. 점과 선을 입력하고 글자를 누르거나 단어를 직접 입력하세요.","글자","단어 입력","모스 표","답 전송","YOUTUBE 코드 단어","새 MOONKATTY 영상을 보고 영상에서 말하거나 보여 준 코드 단어를 입력하세요. 코드당 한 번 지급됩니다.","코드 단어","받기","코드는 만료됩니다 — 새 영상과 함께 새 코드가 나옵니다.","일일 신호","점","선","삭제","일일 신호 📡",
"UTC 하루 한 번: 연속 출석 +3~+25 ⭐ (7일째부터 최대; 주 1회 방패가 놓친 하루를 지켜 줌), 달의 신호 암호 +15 ⭐ (5회 시도), YouTube 코드 단어 코드당 최대 +50 ⭐, 코드당 한 번. 모두 Telegram을 통해 서버가 검증합니다.",
"오늘은 이미 출석했습니다","오늘은 이미 해독했습니다","남은 시도: {n} / {m}","잔액 잠김","출석 +{n} ⭐","출석 완료 ✓","출석 +{n} ⭐","코드 승인! +{n} ⭐","연결 끊김 — 다시 시도하세요","DEMO · 로컬 미리보기 — 보상은 Telegram에서만 검증","{n}일","해독 완료 ✓ +{n} ⭐","{n}일","영상의 코드 단어를 입력하세요","시도 없음 — 새 신호는 00:00 UTC","{n}글자가 필요합니다","오늘 시도를 모두 사용했습니다","서버 검증됨 · Telegram","신호 해독 완료 ✓","방패가 연속 출석을 지켰습니다! +{n} ⭐","신호 해독! +{n} ⭐","답 전송 +{n} ⭐","알 수 없는 모스 글자 — 다시 시도","알 수 없거나 만료된 코드","틀린 단어 — 신호 왜곡","이미 사용한 코드입니다","🛡 방패 준비 — 이번 주 놓친 하루 1회 보호","🛡 이번 주 방패 사용함"]
L['zh']=["每个 UTC 日","月之信号与连签","连续签到","每个 UTC 日签到。奖励逐日增加到第 7 天，之后保持上限。","签到","第 0 天","月之信号","每日密码：破译以摩尔斯电码发送的剧情单词。","点按符号可重放。输入点和划后按“字母”，或直接输入单词。","字母","输入单词","摩尔斯表","发送答案","YOUTUBE 口令","观看 MOONKATTY 新视频，输入视频中说出或显示的口令。每个口令只奖励一次。","口令","兑换","口令会过期——新视频会带来新口令。","每日信号","点","划","删除","每日信号 📡",
"每个 UTC 日一次：连续签到 +3 至 +25 ⭐（第 7 天起封顶；每周一个护盾可挽救一天漏签），月之信号密码 +15 ⭐（5 次机会），YouTube 口令每个最多 +50 ⭐，每个口令一次。全部由服务器通过 Telegram 验证。",
"今天已签到","今天已破译","剩余次数：{n} / {m}","余额已锁定","签到 +{n} ⭐","已签到 ✓","签到 +{n} ⭐","口令有效！+{n} ⭐","连接中断——请重试","DEMO · 本地预览——奖励仅在 Telegram 中验证","第 {n} 天","已破译 ✓ +{n} ⭐","{n}天","请输入视频中的口令","次数用完——新信号于 00:00 UTC","需要 {n} 个字母","今天的次数已用完","服务器已验证 · Telegram","信号已破译 ✓","护盾保住了你的连签！+{n} ⭐","信号已破译！+{n} ⭐","发送答案 +{n} ⭐","未知的摩尔斯字母——请重试","口令无效或已过期","单词错误——信号失真","你已使用过此口令","🛡 护盾就绪——本周可挽救 1 天漏签","🛡 本周护盾已使用"]
out=['/* MOONKATTY daily retention strings (streak / Moon Signal / YouTube code). Generated by tools/daily-locales.py */','(function(root){','\'use strict\';','const L=root.MKTYLocales=root.MKTYLocales||{};','const D='+json.dumps({c:dict(zip(K,v)) for c,v in L.items()},ensure_ascii=False,indent=1)+';','for(const c of Object.keys(D)){L[c]=L[c]||{};L[c].strings=Object.assign(L[c].strings||{},D[c]);}','})(typeof globalThis!==\'undefined\'?globalThis:this);']
for c,v in L.items(): assert len(v)==len(K),(c,len(v),len(K))
open('locales/daily-retention.js','w').write('\n'.join(out)+'\n')
print(len(K),len(L))
