# Generates locales/leaderboard.js (leaderboard identity + privacy strings, merged into MKTYLocales[code].strings).
import json
K=["Server profile standings. Pilots appear with their Telegram name and photo; anyone who hid themselves in settings appears under a callsign. Results on this device may differ.",
"What we store: your Telegram ID and username, game progress and reward events. For the global standings we store your Telegram name and photo (only from a verified session). You can hide yourself in Settings — a callsign is shown instead. This data is kept in Supabase and used only to run the game and its rewards.",
"Standings","Your Telegram name and photo are shown in the global standings. If you hide yourself, a callsign and a generic badge are shown instead.",
"Hide me in standings","You are hidden in standings: a callsign is shown.","Your Telegram name and photo are visible in standings.","Could not save the setting. Try again later.","This setting is available when the game runs in Telegram."]
L={}
L['ru']=["Данные серверных профилей. Пилоты показаны с именем и фото из Telegram; кто скрыл себя в настройках — под позывным. Результаты на этом устройстве могут отличаться.",
"Что мы храним: ваш Telegram ID и имя пользователя, игровой прогресс и события наград. Для общего рейтинга сохраняются ваши имя и фото из Telegram (только из подтверждённой сессии). Скрыть себя можно в Настройках — тогда показывается позывной. Данные хранятся в Supabase и используются только для работы игры и наград.",
"Рейтинг","В общем рейтинге видны ваши имя и фото из Telegram. Если скрыть себя, вместо них будут позывной и стандартный значок.",
"Скрыть меня в рейтинге","Вы скрыты в рейтинге: показан позывной.","Ваше имя и фото Telegram видны в рейтинге.","Не удалось сохранить настройку. Повторите позже.","Настройка доступна при запуске игры в Telegram."]
L['uk']=["Дані серверних профілів. Пілотів показано з іменем і фото з Telegram; хто приховав себе в налаштуваннях — під позивним. Результати на цьому пристрої можуть відрізнятися.",
"Що ми зберігаємо: ваш Telegram ID та ім’я користувача, ігровий прогрес і події нагород. Для загального рейтингу зберігаються ваші ім’я та фото з Telegram (лише з підтвердженої сесії). Приховати себе можна в Налаштуваннях — тоді показується позивний. Дані зберігаються в Supabase і використовуються лише для роботи гри та нагород.",
"Рейтинг","У загальному рейтингу видно ваші ім’я та фото з Telegram. Якщо приховати себе, замість них будуть позивний і стандартний значок.",
"Приховати мене в рейтингу","Вас приховано в рейтингу: показано позивний.","Ваші ім’я та фото Telegram видно в рейтингу.","Не вдалося зберегти налаштування. Спробуйте пізніше.","Налаштування доступне під час запуску гри в Telegram."]
L['es']=["Clasificación de perfiles del servidor. Los pilotos aparecen con su nombre y foto de Telegram; quien se ocultó en ajustes aparece con un indicativo. Los resultados en este dispositivo pueden variar.",
"Qué guardamos: tu ID y nombre de usuario de Telegram, el progreso del juego y los eventos de recompensa. Para la clasificación global guardamos tu nombre y foto de Telegram (solo de una sesión verificada). Puedes ocultarte en Ajustes y se mostrará un indicativo. Estos datos se guardan en Supabase y solo se usan para el juego y sus recompensas.",
"Clasificación","Tu nombre y foto de Telegram se muestran en la clasificación global. Si te ocultas, se mostrarán un indicativo y una insignia genérica.",
"Ocultarme en la clasificación","Estás oculto en la clasificación: se muestra un indicativo.","Tu nombre y foto de Telegram son visibles en la clasificación.","No se pudo guardar el ajuste. Inténtalo más tarde.","Este ajuste está disponible cuando el juego se abre en Telegram."]
L['pt']=["Classificação dos perfis do servidor. Os pilotos aparecem com nome e foto do Telegram; quem se ocultou nas configurações aparece com um indicativo. Os resultados neste dispositivo podem variar.",
"O que guardamos: seu ID e nome de usuário do Telegram, progresso no jogo e eventos de recompensa. Para a classificação geral guardamos seu nome e foto do Telegram (só de uma sessão verificada). Você pode se ocultar nas Configurações — então um indicativo é exibido. Esses dados ficam no Supabase e são usados só para o jogo e suas recompensas.",
"Classificação","Seu nome e foto do Telegram aparecem na classificação geral. Se você se ocultar, serão exibidos um indicativo e um emblema genérico.",
"Ocultar-me na classificação","Você está oculto na classificação: um indicativo é exibido.","Seu nome e foto do Telegram estão visíveis na classificação.","Não foi possível salvar a configuração. Tente mais tarde.","Esta configuração fica disponível quando o jogo roda no Telegram."]
L['de']=["Rangliste der Serverprofile. Piloten erscheinen mit Telegram-Name und -Foto; wer sich in den Einstellungen verborgen hat, erscheint mit Rufzeichen. Ergebnisse auf diesem Gerät können abweichen.",
"Was wir speichern: deine Telegram-ID und deinen Benutzernamen, Spielfortschritt und Belohnungsereignisse. Für die Rangliste speichern wir deinen Telegram-Namen und dein Foto (nur aus einer verifizierten Sitzung). In den Einstellungen kannst du dich verbergen – dann wird ein Rufzeichen angezeigt. Die Daten liegen bei Supabase und dienen nur dem Spiel und seinen Belohnungen.",
"Rangliste","In der Rangliste werden dein Telegram-Name und dein Foto angezeigt. Wenn du dich verbirgst, erscheinen stattdessen ein Rufzeichen und ein Standardabzeichen.",
"Mich in der Rangliste verbergen","Du bist in der Rangliste verborgen: ein Rufzeichen wird angezeigt.","Dein Telegram-Name und Foto sind in der Rangliste sichtbar.","Einstellung konnte nicht gespeichert werden. Später erneut versuchen.","Diese Einstellung ist verfügbar, wenn das Spiel in Telegram läuft."]
L['fr']=["Classement des profils serveur. Les pilotes apparaissent avec leur nom et leur photo Telegram ; ceux qui se sont masqués dans les réglages apparaissent sous un indicatif. Les résultats sur cet appareil peuvent différer.",
"Ce que nous conservons : ton ID et ton nom d’utilisateur Telegram, ta progression et tes événements de récompense. Pour le classement général, nous conservons ton nom et ta photo Telegram (uniquement depuis une session vérifiée). Tu peux te masquer dans les Réglages : un indicatif s’affiche alors. Ces données sont stockées dans Supabase et servent uniquement au jeu et à ses récompenses.",
"Classement","Ton nom et ta photo Telegram sont affichés dans le classement général. Si tu te masques, un indicatif et un badge générique s’affichent à la place.",
"Me masquer du classement","Tu es masqué dans le classement : un indicatif est affiché.","Ton nom et ta photo Telegram sont visibles dans le classement.","Impossible d’enregistrer le réglage. Réessaie plus tard.","Ce réglage est disponible quand le jeu est lancé dans Telegram."]
L['it']=["Classifica dei profili server. I piloti compaiono con nome e foto di Telegram; chi si è nascosto nelle impostazioni compare con un nominativo. I risultati su questo dispositivo possono differire.",
"Cosa conserviamo: il tuo ID e nome utente Telegram, i progressi di gioco e gli eventi premio. Per la classifica generale conserviamo nome e foto di Telegram (solo da una sessione verificata). Puoi nasconderti nelle Impostazioni: verrà mostrato un nominativo. I dati sono su Supabase e servono solo al gioco e ai suoi premi.",
"Classifica","Nella classifica generale sono mostrati nome e foto di Telegram. Se ti nascondi, al loro posto compaiono un nominativo e un badge generico.",
"Nascondimi in classifica","Sei nascosto in classifica: viene mostrato un nominativo.","Il tuo nome e la foto di Telegram sono visibili in classifica.","Impossibile salvare l’impostazione. Riprova più tardi.","Questa impostazione è disponibile quando il gioco è aperto in Telegram."]
L['tr']=["Sunucu profili sıralaması. Pilotlar Telegram adı ve fotoğrafıyla görünür; ayarlardan kendini gizleyenler çağrı adıyla görünür. Bu cihazdaki sonuçlar farklı olabilir.",
"Sakladıklarımız: Telegram kimliğin ve kullanıcı adın, oyun ilerlemen ve ödül olayları. Genel sıralama için Telegram adın ve fotoğrafın saklanır (yalnızca doğrulanmış oturumdan). Ayarlar'dan kendini gizleyebilirsin — o zaman çağrı adı gösterilir. Veriler Supabase'de tutulur ve yalnızca oyun ve ödülleri için kullanılır.",
"Sıralama","Genel sıralamada Telegram adın ve fotoğrafın görünür. Kendini gizlersen bunların yerine çağrı adı ve genel bir rozet gösterilir.",
"Beni sıralamada gizle","Sıralamada gizlisin: çağrı adı gösteriliyor.","Telegram adın ve fotoğrafın sıralamada görünüyor.","Ayar kaydedilemedi. Daha sonra tekrar dene.","Bu ayar oyun Telegram'da açıldığında kullanılabilir."]
L['he']=["דירוג פרופילי השרת. טייסים מוצגים עם השם והתמונה מ-Telegram; מי שהסתיר את עצמו בהגדרות מוצג באות קריאה. התוצאות במכשיר זה עשויות להיות שונות.",
"מה אנחנו שומרים: מזהה Telegram ושם המשתמש שלך, התקדמות במשחק ואירועי פרסים. לדירוג הכללי נשמרים השם והתמונה שלך מ-Telegram (רק מסשן מאומת). אפשר להסתתר בהגדרות — ואז מוצג אות קריאה. הנתונים נשמרים ב-Supabase ומשמשים רק להפעלת המשחק והפרסים.",
"דירוג","בדירוג הכללי מוצגים השם והתמונה שלך מ-Telegram. אם תסתתר, יוצגו במקומם אות קריאה וסמל כללי.",
"הסתר אותי בדירוג","אתה מוסתר בדירוג: מוצג אות קריאה.","השם והתמונה שלך מ-Telegram גלויים בדירוג.","לא ניתן לשמור את ההגדרה. נסו שוב מאוחר יותר.","ההגדרה זמינה כשהמשחק פועל ב-Telegram."]
L['ko']=["서버 프로필 순위입니다. 파일럿은 Telegram 이름과 사진으로 표시되며, 설정에서 숨긴 사람은 호출 부호로 표시됩니다. 이 기기의 결과와 다를 수 있습니다.",
"저장하는 정보: Telegram ID와 사용자 이름, 게임 진행 상황, 보상 이벤트. 전체 순위를 위해 Telegram 이름과 사진을 저장합니다(검증된 세션에서만). 설정에서 자신을 숨길 수 있으며, 그러면 호출 부호가 표시됩니다. 데이터는 Supabase에 보관되며 게임과 보상 운영에만 사용됩니다.",
"순위","전체 순위에 Telegram 이름과 사진이 표시됩니다. 숨기면 대신 호출 부호와 기본 배지가 표시됩니다.",
"순위에서 나 숨기기","순위에서 숨겨졌습니다: 호출 부호가 표시됩니다.","Telegram 이름과 사진이 순위에 표시됩니다.","설정을 저장하지 못했습니다. 나중에 다시 시도하세요.","이 설정은 Telegram에서 게임을 실행할 때 사용할 수 있습니다."]
L['zh']=["服务器档案排行榜。飞行员显示 Telegram 名字和头像；在设置中隐藏自己的玩家显示为呼号。本设备上的结果可能不同。",
"我们存储的内容：你的 Telegram ID 和用户名、游戏进度和奖励事件。为了总排行榜，我们会保存你的 Telegram 名字和头像（仅来自已验证的会话）。你可以在设置中隐藏自己——届时显示呼号。数据保存在 Supabase，仅用于运行游戏及其奖励。",
"排行榜","总排行榜会显示你的 Telegram 名字和头像。若隐藏自己，将改为显示呼号和通用徽章。",
"在排行榜中隐藏我","你已在排行榜中隐藏：显示呼号。","你的 Telegram 名字和头像在排行榜中可见。","无法保存设置，请稍后重试。","在 Telegram 中运行游戏时可使用此设置。"]
L['ar']=["ترتيب ملفات الخادم. يظهر الطيارون باسمهم وصورتهم في Telegram؛ ومن أخفى نفسه في الإعدادات يظهر باسم نداء. قد تختلف النتائج على هذا الجهاز.", "ما نخزّنه: معرّفك واسم المستخدم في Telegram، وتقدّمك في اللعبة، وأحداث المكافآت. ومن أجل الترتيب العالمي نخزّن اسمك وصورتك في Telegram (من جلسة مُتحقَّق منها فقط). يمكنك إخفاء نفسك في الإعدادات — فيظهر اسم نداء بدلًا من ذلك. تُحفظ هذه البيانات في Supabase وتُستخدم فقط لتشغيل اللعبة ومكافآتها.", "الترتيب", "يظهر اسمك وصورتك في Telegram في الترتيب العالمي. إذا أخفيت نفسك، يظهر اسم نداء وشارة عامة بدلًا من ذلك.", "أخفِني في الترتيب", "أنت مخفي في الترتيب: يظهر اسم نداء.", "اسمك وصورتك في Telegram ظاهران في الترتيب.", "تعذّر حفظ الإعداد. حاول لاحقًا.", "هذا الإعداد متاح عندما تعمل اللعبة داخل Telegram."]
assert len(L)==12 and all(len(v)==len(K) for v in L.values())
out=['/* MOONKATTY leaderboard identity strings. Generated by tools/leaderboard-locales.py */','(function(root){',"'use strict';",'const L=root.MKTYLocales=root.MKTYLocales||{};','const D='+json.dumps({c:dict(zip(K,v)) for c,v in L.items()},ensure_ascii=False,indent=1)+';','for(const c of Object.keys(D)){L[c]=L[c]||{};L[c].strings=Object.assign(L[c].strings||{},D[c]);}',"})(typeof globalThis!=='undefined'?globalThis:this);"]
open('locales/leaderboard.js','w').write('\n'.join(out)+'\n')
