# Generates locales/pacing.js (chapter pacing + life-loss strings, 12 locales; EN is the key).
import json
K=[
"CHAPTER {n} / 09",
"Next chapter in",
"A new chapter opens every day at 00:00 UTC. Meanwhile complete the Daily Missions, decode the Moon Signal and keep your streak.",
"📡 DAILY MISSIONS",
"👥 Invite a friend — open chapters early",
"🎟 Open now · referral passes: {n}",
"GOT IT",
"LIVES",
"Out of lives. Next life in",
"Every failed board, flight or finale costs 1 life. Each life restores 12 hours after it was spent. Daily Missions stay open.",
"Risky attempt",
"Failing a board, flight or chapter finale in this chapter costs 1 global life. Training and saved progress stay free. Lives restore 12 hours after they are spent.",
"START ▶",
"CANCEL",
"Chapter unlocked with a referral pass 🎟",
"No referral passes yet",
"Tutorial: no life lost in your first LIFE #1",
"−1 life · {n} / 9 left",
"Next chapter in {t}",
"Meanwhile: Daily Missions and the Moon Signal cipher",
"Out of lives. Next life in {t}",
"OPENS IN {t}",
"🎓 Tutorial chapter: failures in your first LIFE #1 cost no lives. Lives: {n} / 9",
"⚠️ A failed board, flight or finale costs 1 ❤️ · training is free · Lives: {n} / 9",
"🌙 CHAPTER {n} IN {t}",
"Complete LIFE #1 through LIFE #9 — one new chapter per day: after you finish a chapter, the next one opens at 00:00 UTC (an invited friend who completes LIFE #1 can open one chapter early). You have 9 global lives: every failed board, flight or chapter finale costs 1 life (training and the first LIFE #1 tutorial are free). At 0 lives missions pause until a life restores — each spent life restores after 12 hours.",
"You have up to 9 global lives. Every failed board, flight or chapter finale costs 1 life; training and your first LIFE #1 run are free. Each spent life restores automatically 12 hours later. At 0 lives missions are paused until a life restores.",
"When does the next chapter open?",
"One new chapter per day: after you finish a chapter, the next one opens at 00:00 UTC — the same reset as Daily Missions. Completed chapters always stay open. A friend who joins with your link and completes LIFE #1 gives you one pass to skip the wait. The full story takes about 9 days.",
"One new chapter per day: the next one opens at 00:00 UTC. The full story takes about 9 days.",
]
L={}
L['ru']=["ГЛАВА {n} / 09","Следующая глава через","Новая глава открывается каждый день в 00:00 UTC. А пока выполни ежедневные миссии, разгадай Сигнал Луны и сохрани стрик.","📡 ЕЖЕДНЕВНЫЕ МИССИИ","👥 Пригласи друга — открывай главы раньше","🎟 Открыть сейчас · пропусков: {n}","ПОНЯТНО","ЖИЗНИ","Жизни закончились. Следующая через","Каждый проваленный этап — доска, вылет или финал — стоит 1 жизнь. Жизнь восстанавливается через 12 часов. Ежедневные миссии остаются доступны.","Рискованная попытка","Провал доски, вылета или финала в этой главе стоит 1 общую жизнь. Тренировки и сохранённый прогресс бесплатны. Жизни восстанавливаются через 12 часов.","НАЧАТЬ ▶","ОТМЕНА","Глава открыта по пропуску за друга 🎟","Пропусков за друзей пока нет","Обучение: в первом прохождении LIFE #1 жизни не тратятся","−1 жизнь · осталось {n} / 9","Следующая глава через {t}","А пока — ежедневные миссии и шифр Сигнала Луны","Жизни закончились. Следующая через {t}","ОТКРОЕТСЯ ЧЕРЕЗ {t}","🎓 Обучающая глава: ошибки в первом прохождении LIFE #1 не стоят жизней. Жизни: {n} / 9","⚠️ Провал доски, вылета или финала стоит 1 ❤️ · тренировки бесплатны · Жизни: {n} / 9","🌙 ГЛАВА {n} ЧЕРЕЗ {t}",
"Пройди LIFE #1–LIFE #9 — по одной новой главе в день: после прохождения главы следующая открывается в 00:00 UTC (друг, пришедший по твоей ссылке и прошедший LIFE #1, открывает одну главу раньше). У тебя 9 общих жизней: каждый проваленный этап — доска, вылет или финал главы — стоит 1 жизнь (тренировки и первое обучение LIFE #1 бесплатны). При 0 жизней миссии на паузе, пока жизнь не восстановится — каждая потраченная жизнь возвращается через 12 часов.",
"У вас до 9 общих жизней. Каждый проваленный этап (доска, вылет или финал главы) стоит 1 жизнь; тренировки и первое прохождение LIFE #1 бесплатны. Каждая потраченная жизнь восстанавливается автоматически через 12 часов. При 0 жизней миссии недоступны до восстановления.",
"Когда открывается следующая глава?",
"Одна новая глава в день: после прохождения главы следующая открывается в 00:00 UTC — как и ежедневные задания. Пройденные главы всегда доступны. Друг, который пришёл по вашей ссылке и прошёл LIFE #1, даёт один пропуск ожидания. Вся история занимает около 9 дней.",
"Одна новая глава в день: следующая открывается в 00:00 UTC. Вся история — около 9 дней."]
L['uk']=["РОЗДІЛ {n} / 09","Наступний розділ через","Новий розділ відкривається щодня о 00:00 UTC. А поки виконай щоденні місії, розгадай Сигнал Місяця і збережи стрик.","📡 ЩОДЕННІ МІСІЇ","👥 Запроси друга — відкривай розділи раніше","🎟 Відкрити зараз · перепусток: {n}","ЗРОЗУМІЛО","ЖИТТЯ","Життя закінчились. Наступне через","Кожен провалений етап — дошка, виліт або фінал — коштує 1 життя. Життя відновлюється через 12 годин. Щоденні місії залишаються доступними.","Ризикована спроба","Провал дошки, вильоту або фіналу в цьому розділі коштує 1 спільне життя. Тренування і збережений прогрес безкоштовні. Життя відновлюються через 12 годин.","ПОЧАТИ ▶","СКАСУВАТИ","Розділ відкрито перепусткою за друга 🎟","Перепусток за друзів поки немає","Навчання: у першому проходженні LIFE #1 життя не витрачаються","−1 життя · залишилось {n} / 9","Наступний розділ через {t}","А поки — щоденні місії та шифр Сигналу Місяця","Життя закінчились. Наступне через {t}","ВІДКРИЄТЬСЯ ЧЕРЕЗ {t}","🎓 Навчальний розділ: помилки в першому проходженні LIFE #1 не коштують життів. Життя: {n} / 9","⚠️ Провал дошки, вильоту або фіналу коштує 1 ❤️ · тренування безкоштовні · Життя: {n} / 9","🌙 РОЗДІЛ {n} ЧЕРЕЗ {t}",
"Пройди LIFE #1–LIFE #9 — по одному новому розділу на день: після проходження розділу наступний відкривається о 00:00 UTC (друг, який прийшов за твоїм посиланням і пройшов LIFE #1, відкриває один розділ раніше). У тебе 9 спільних життів: кожен провалений етап — дошка, виліт або фінал розділу — коштує 1 життя (тренування і перше навчання LIFE #1 безкоштовні). При 0 життів місії на паузі, доки життя не відновиться — кожне витрачене життя повертається через 12 годин.",
"У вас до 9 спільних життів. Кожен провалений етап (дошка, виліт або фінал розділу) коштує 1 життя; тренування і перше проходження LIFE #1 безкоштовні. Кожне витрачене життя відновлюється автоматично через 12 годин. При 0 життів місії недоступні до відновлення.",
"Коли відкривається наступний розділ?",
"Один новий розділ на день: після проходження розділу наступний відкривається о 00:00 UTC — як і щоденні завдання. Пройдені розділи завжди доступні. Друг, який прийшов за вашим посиланням і пройшов LIFE #1, дає одну перепустку без очікування. Уся історія займає близько 9 днів.",
"Один новий розділ на день: наступний відкривається о 00:00 UTC. Уся історія — близько 9 днів."]
L['es']=["CAPÍTULO {n} / 09","Próximo capítulo en","Cada día a las 00:00 UTC se abre un capítulo nuevo. Mientras tanto, completa las Misiones diarias, descifra la Señal Lunar y mantén tu racha.","📡 MISIONES DIARIAS","👥 Invita a un amigo: abre capítulos antes","🎟 Abrir ya · pases de referido: {n}","ENTENDIDO","VIDAS","Sin vidas. Próxima vida en","Cada tablero, vuelo o final fallado cuesta 1 vida. Cada vida se recupera 12 horas después de gastarla. Las Misiones diarias siguen abiertas.","Intento arriesgado","Fallar un tablero, un vuelo o el final de este capítulo cuesta 1 vida global. El entrenamiento y el progreso guardado son gratis. Las vidas se recuperan 12 horas después de gastarse.","EMPEZAR ▶","CANCELAR","Capítulo abierto con un pase de referido 🎟","Aún no tienes pases de referido","Tutorial: no pierdes vidas en tu primera LIFE #1","−1 vida · quedan {n} / 9","Próximo capítulo en {t}","Mientras tanto: Misiones diarias y el cifrado de la Señal Lunar","Sin vidas. Próxima vida en {t}","SE ABRE EN {t}","🎓 Capítulo tutorial: los fallos en tu primera LIFE #1 no cuestan vidas. Vidas: {n} / 9","⚠️ Un tablero, vuelo o final fallado cuesta 1 ❤️ · el entrenamiento es gratis · Vidas: {n} / 9","🌙 CAPÍTULO {n} EN {t}",
"Completa de LIFE #1 a LIFE #9: un capítulo nuevo al día. Al terminar un capítulo, el siguiente se abre a las 00:00 UTC (un amigo invitado que complete LIFE #1 puede abrir un capítulo antes). Tienes 9 vidas globales: cada tablero, vuelo o final de capítulo fallado cuesta 1 vida (el entrenamiento y el primer tutorial de LIFE #1 son gratis). Con 0 vidas las misiones se pausan hasta que se recupere una vida; cada vida gastada se recupera a las 12 horas.",
"Tienes hasta 9 vidas globales. Cada tablero, vuelo o final de capítulo fallado cuesta 1 vida; el entrenamiento y tu primera partida de LIFE #1 son gratis. Cada vida gastada se recupera automáticamente 12 horas después. Con 0 vidas las misiones se pausan hasta que se recupere una vida.",
"¿Cuándo se abre el siguiente capítulo?",
"Un capítulo nuevo al día: al terminar un capítulo, el siguiente se abre a las 00:00 UTC, el mismo reinicio que las Misiones diarias. Los capítulos completados siempre siguen abiertos. Un amigo que llegue con tu enlace y complete LIFE #1 te da un pase para saltarte la espera. La historia completa dura unos 9 días.",
"Un capítulo nuevo al día: el siguiente se abre a las 00:00 UTC. La historia completa dura unos 9 días."]
L['pt']=["CAPÍTULO {n} / 09","Próximo capítulo em","Um novo capítulo abre todos os dias às 00:00 UTC. Enquanto isso, conclua as Missões diárias, decifre o Sinal da Lua e mantenha sua sequência.","📡 MISSÕES DIÁRIAS","👥 Convide um amigo — abra capítulos antes","🎟 Abrir agora · passes de indicação: {n}","ENTENDI","VIDAS","Sem vidas. Próxima vida em","Cada tabuleiro, voo ou final com falha custa 1 vida. Cada vida volta 12 horas depois de gasta. As Missões diárias continuam abertas.","Tentativa arriscada","Falhar em um tabuleiro, voo ou final deste capítulo custa 1 vida global. Treino e progresso salvo são grátis. As vidas voltam 12 horas depois de gastas.","COMEÇAR ▶","CANCELAR","Capítulo aberto com um passe de indicação 🎟","Ainda não há passes de indicação","Tutorial: nenhuma vida perdida na sua primeira LIFE #1","−1 vida · restam {n} / 9","Próximo capítulo em {t}","Enquanto isso: Missões diárias e a cifra do Sinal da Lua","Sem vidas. Próxima vida em {t}","ABRE EM {t}","🎓 Capítulo tutorial: falhas na sua primeira LIFE #1 não custam vidas. Vidas: {n} / 9","⚠️ Tabuleiro, voo ou final com falha custa 1 ❤️ · treino é grátis · Vidas: {n} / 9","🌙 CAPÍTULO {n} EM {t}",
"Conclua da LIFE #1 à LIFE #9 — um novo capítulo por dia: ao terminar um capítulo, o próximo abre às 00:00 UTC (um amigo convidado que concluir a LIFE #1 pode abrir um capítulo antes). Você tem 9 vidas globais: cada tabuleiro, voo ou final de capítulo com falha custa 1 vida (treino e o primeiro tutorial da LIFE #1 são grátis). Com 0 vidas as missões ficam pausadas até uma vida voltar — cada vida gasta volta após 12 horas.",
"Você tem até 9 vidas globais. Cada tabuleiro, voo ou final de capítulo com falha custa 1 vida; treino e sua primeira partida da LIFE #1 são grátis. Cada vida gasta volta automaticamente 12 horas depois. Com 0 vidas as missões ficam pausadas até uma vida voltar.",
"Quando abre o próximo capítulo?",
"Um novo capítulo por dia: ao terminar um capítulo, o próximo abre às 00:00 UTC — o mesmo reinício das Missões diárias. Capítulos concluídos continuam sempre abertos. Um amigo que entrar pelo seu link e concluir a LIFE #1 dá um passe para pular a espera. A história completa leva cerca de 9 dias.",
"Um novo capítulo por dia: o próximo abre às 00:00 UTC. A história completa leva cerca de 9 dias."]
L['de']=["KAPITEL {n} / 09","Nächstes Kapitel in","Jeden Tag um 00:00 UTC öffnet sich ein neues Kapitel. Erledige bis dahin die Tagesmissionen, entschlüssle das Mondsignal und halte deine Serie.","📡 TAGESMISSIONEN","👥 Freund einladen — Kapitel früher öffnen","🎟 Jetzt öffnen · Empfehlungspässe: {n}","VERSTANDEN","LEBEN","Keine Leben mehr. Nächstes Leben in","Jedes gescheiterte Brett, jeder Flug oder jedes Finale kostet 1 Leben. Jedes Leben kehrt 12 Stunden nach dem Verbrauch zurück. Tagesmissionen bleiben offen.","Riskanter Versuch","Scheitert ein Brett, ein Flug oder das Finale in diesem Kapitel, kostet das 1 globales Leben. Training und gespeicherter Fortschritt sind kostenlos. Leben kehren 12 Stunden nach dem Verbrauch zurück.","STARTEN ▶","ABBRECHEN","Kapitel mit einem Empfehlungspass geöffnet 🎟","Noch keine Empfehlungspässe","Tutorial: In deinem ersten LIFE #1 verlierst du kein Leben","−1 Leben · noch {n} / 9","Nächstes Kapitel in {t}","Bis dahin: Tagesmissionen und die Mondsignal-Chiffre","Keine Leben mehr. Nächstes Leben in {t}","ÖFFNET IN {t}","🎓 Tutorial-Kapitel: Fehler in deinem ersten LIFE #1 kosten keine Leben. Leben: {n} / 9","⚠️ Gescheitertes Brett, Flug oder Finale kostet 1 ❤️ · Training ist kostenlos · Leben: {n} / 9","🌙 KAPITEL {n} IN {t}",
"Schließe LIFE #1 bis LIFE #9 ab — ein neues Kapitel pro Tag: Nach einem Kapitel öffnet sich das nächste um 00:00 UTC (ein eingeladener Freund, der LIFE #1 abschließt, kann ein Kapitel früher öffnen). Du hast 9 globale Leben: Jedes gescheiterte Brett, jeder Flug oder jedes Kapitelfinale kostet 1 Leben (Training und das erste LIFE-#1-Tutorial sind kostenlos). Bei 0 Leben pausieren Missionen, bis ein Leben zurückkehrt — jedes verbrauchte Leben kehrt nach 12 Stunden zurück.",
"Du hast bis zu 9 globale Leben. Jedes gescheiterte Brett, jeder Flug oder jedes Kapitelfinale kostet 1 Leben; Training und dein erster LIFE-#1-Durchgang sind kostenlos. Jedes verbrauchte Leben kehrt nach 12 Stunden automatisch zurück. Bei 0 Leben pausieren Missionen, bis ein Leben zurückkehrt.",
"Wann öffnet sich das nächste Kapitel?",
"Ein neues Kapitel pro Tag: Nach einem Kapitel öffnet sich das nächste um 00:00 UTC — derselbe Reset wie bei den Tagesmissionen. Abgeschlossene Kapitel bleiben immer offen. Ein Freund, der über deinen Link kommt und LIFE #1 abschließt, gibt dir einen Pass, um das Warten zu überspringen. Die ganze Geschichte dauert etwa 9 Tage.",
"Ein neues Kapitel pro Tag: Das nächste öffnet sich um 00:00 UTC. Die ganze Geschichte dauert etwa 9 Tage."]
L['fr']=["CHAPITRE {n} / 09","Prochain chapitre dans","Un nouveau chapitre s’ouvre chaque jour à 00:00 UTC. En attendant, termine les Missions quotidiennes, déchiffre le Signal lunaire et garde ta série.","📡 MISSIONS QUOTIDIENNES","👥 Invite un ami — ouvre les chapitres plus tôt","🎟 Ouvrir maintenant · pass de parrainage : {n}","COMPRIS","VIES","Plus de vies. Prochaine vie dans","Chaque plateau, vol ou finale échoué coûte 1 vie. Chaque vie revient 12 heures après avoir été dépensée. Les Missions quotidiennes restent ouvertes.","Tentative risquée","Échouer un plateau, un vol ou la finale de ce chapitre coûte 1 vie globale. L’entraînement et la progression sauvegardée sont gratuits. Les vies reviennent 12 heures après avoir été dépensées.","COMMENCER ▶","ANNULER","Chapitre ouvert avec un pass de parrainage 🎟","Pas encore de pass de parrainage","Tutoriel : aucune vie perdue lors de ta première LIFE #1","−1 vie · il reste {n} / 9","Prochain chapitre dans {t}","En attendant : Missions quotidiennes et le chiffre du Signal lunaire","Plus de vies. Prochaine vie dans {t}","S’OUVRE DANS {t}","🎓 Chapitre tutoriel : les échecs de ta première LIFE #1 ne coûtent aucune vie. Vies : {n} / 9","⚠️ Un plateau, vol ou finale échoué coûte 1 ❤️ · l’entraînement est gratuit · Vies : {n} / 9","🌙 CHAPITRE {n} DANS {t}",
"Termine LIFE #1 à LIFE #9 — un nouveau chapitre par jour : après un chapitre, le suivant s’ouvre à 00:00 UTC (un ami invité qui termine LIFE #1 peut ouvrir un chapitre plus tôt). Tu as 9 vies globales : chaque plateau, vol ou finale de chapitre échoué coûte 1 vie (l’entraînement et le premier tutoriel LIFE #1 sont gratuits). À 0 vie, les missions sont en pause jusqu’au retour d’une vie — chaque vie dépensée revient après 12 heures.",
"Tu as jusqu’à 9 vies globales. Chaque plateau, vol ou finale de chapitre échoué coûte 1 vie ; l’entraînement et ta première partie de LIFE #1 sont gratuits. Chaque vie dépensée revient automatiquement 12 heures plus tard. À 0 vie, les missions sont en pause jusqu’au retour d’une vie.",
"Quand le prochain chapitre s’ouvre-t-il ?",
"Un nouveau chapitre par jour : après un chapitre, le suivant s’ouvre à 00:00 UTC — la même réinitialisation que les Missions quotidiennes. Les chapitres terminés restent toujours ouverts. Un ami qui arrive avec ton lien et termine LIFE #1 te donne un pass pour sauter l’attente. L’histoire complète dure environ 9 jours.",
"Un nouveau chapitre par jour : le suivant s’ouvre à 00:00 UTC. L’histoire complète dure environ 9 jours."]
L['it']=["CAPITOLO {n} / 09","Prossimo capitolo tra","Ogni giorno alle 00:00 UTC si apre un nuovo capitolo. Nel frattempo completa le Missioni giornaliere, decifra il Segnale lunare e mantieni la serie.","📡 MISSIONI GIORNALIERE","👥 Invita un amico — apri i capitoli prima","🎟 Apri ora · pass referral: {n}","HO CAPITO","VITE","Vite esaurite. Prossima vita tra","Ogni tabellone, volo o finale fallito costa 1 vita. Ogni vita torna 12 ore dopo essere stata spesa. Le Missioni giornaliere restano aperte.","Tentativo rischioso","Fallire un tabellone, un volo o il finale di questo capitolo costa 1 vita globale. Allenamento e progressi salvati sono gratuiti. Le vite tornano 12 ore dopo essere state spese.","INIZIA ▶","ANNULLA","Capitolo aperto con un pass referral 🎟","Ancora nessun pass referral","Tutorial: nessuna vita persa nella tua prima LIFE #1","−1 vita · ne restano {n} / 9","Prossimo capitolo tra {t}","Nel frattempo: Missioni giornaliere e il cifrario del Segnale lunare","Vite esaurite. Prossima vita tra {t}","SI APRE TRA {t}","🎓 Capitolo tutorial: gli errori nella tua prima LIFE #1 non costano vite. Vite: {n} / 9","⚠️ Tabellone, volo o finale fallito costa 1 ❤️ · l’allenamento è gratuito · Vite: {n} / 9","🌙 CAPITOLO {n} TRA {t}",
"Completa da LIFE #1 a LIFE #9 — un nuovo capitolo al giorno: finito un capitolo, il successivo si apre alle 00:00 UTC (un amico invitato che completa LIFE #1 può aprire un capitolo prima). Hai 9 vite globali: ogni tabellone, volo o finale di capitolo fallito costa 1 vita (allenamento e primo tutorial di LIFE #1 sono gratuiti). Con 0 vite le missioni sono in pausa finché una vita non torna — ogni vita spesa torna dopo 12 ore.",
"Hai fino a 9 vite globali. Ogni tabellone, volo o finale di capitolo fallito costa 1 vita; l’allenamento e la tua prima partita di LIFE #1 sono gratuiti. Ogni vita spesa torna automaticamente dopo 12 ore. Con 0 vite le missioni sono in pausa finché una vita non torna.",
"Quando si apre il prossimo capitolo?",
"Un nuovo capitolo al giorno: finito un capitolo, il successivo si apre alle 00:00 UTC — lo stesso reset delle Missioni giornaliere. I capitoli completati restano sempre aperti. Un amico che arriva dal tuo link e completa LIFE #1 ti dà un pass per saltare l’attesa. La storia completa dura circa 9 giorni.",
"Un nuovo capitolo al giorno: il successivo si apre alle 00:00 UTC. La storia completa dura circa 9 giorni."]
L['tr']=["BÖLÜM {n} / 09","Sonraki bölüm","Her gün 00:00 UTC'de yeni bir bölüm açılır. Bu arada Günlük Görevleri tamamla, Ay Sinyali'ni çöz ve serini koru.","📡 GÜNLÜK GÖREVLER","👥 Arkadaşını davet et — bölümleri erken aç","🎟 Şimdi aç · davet geçişi: {n}","ANLADIM","CANLAR","Canın kalmadı. Sonraki can","Başarısız her tahta, uçuş veya final 1 can harcar. Her can harcandıktan 12 saat sonra geri gelir. Günlük Görevler açık kalır.","Riskli deneme","Bu bölümde tahta, uçuş veya bölüm finalinde başarısız olmak 1 genel can harcar. Antrenman ve kayıtlı ilerleme ücretsizdir. Canlar harcandıktan 12 saat sonra geri gelir.","BAŞLA ▶","İPTAL","Bölüm davet geçişiyle açıldı 🎟","Henüz davet geçişi yok","Eğitim: ilk LIFE #1 oyununda can kaybı yok","−1 can · kalan {n} / 9","Sonraki bölüm: {t}","Bu arada: Günlük Görevler ve Ay Sinyali şifresi","Canın kalmadı. Sonraki can: {t}","{t} SONRA AÇILIR","🎓 Eğitim bölümü: ilk LIFE #1 oyunundaki hatalar can harcamaz. Canlar: {n} / 9","⚠️ Başarısız tahta, uçuş veya final 1 ❤️ harcar · antrenman ücretsiz · Canlar: {n} / 9","🌙 BÖLÜM {n}: {t}",
"LIFE #1'den LIFE #9'a kadar tamamla — günde bir yeni bölüm: bir bölümü bitirdiğinde sonraki 00:00 UTC'de açılır (LIFE #1'i tamamlayan davetli bir arkadaş bir bölümü erken açabilir). 9 genel canın var: başarısız her tahta, uçuş veya bölüm finali 1 can harcar (antrenman ve ilk LIFE #1 eğitimi ücretsiz). 0 canda görevler bir can geri gelene kadar durur — harcanan her can 12 saat sonra geri gelir.",
"En fazla 9 genel canın var. Başarısız her tahta, uçuş veya bölüm finali 1 can harcar; antrenman ve ilk LIFE #1 oyunun ücretsizdir. Harcanan her can 12 saat sonra otomatik geri gelir. 0 canda görevler bir can geri gelene kadar durur.",
"Sonraki bölüm ne zaman açılır?",
"Günde bir yeni bölüm: bir bölümü bitirdiğinde sonraki 00:00 UTC'de açılır — Günlük Görevlerle aynı sıfırlama. Tamamlanan bölümler her zaman açık kalır. Bağlantınla gelip LIFE #1'i tamamlayan bir arkadaş beklemeyi atlamak için bir geçiş verir. Hikâyenin tamamı yaklaşık 9 gün sürer.",
"Günde bir yeni bölüm: sonraki 00:00 UTC'de açılır. Hikâyenin tamamı yaklaşık 9 gün sürer."]
L['he']=["פרק {n} / 09","הפרק הבא בעוד","פרק חדש נפתח כל יום ב־00:00 UTC. בינתיים השלימו את המשימות היומיות, פענחו את אות הירח ושמרו על הרצף.","📡 משימות יומיות","👥 הזמינו חבר — פתחו פרקים מוקדם","🎟 לפתוח עכשיו · כרטיסי הפניה: {n}","הבנתי","חיים","נגמרו החיים. החיים הבאים בעוד","כל לוח, טיסה או גמר שנכשלו עולים חיים אחד. כל חיים חוזרים 12 שעות אחרי שנוצלו. המשימות היומיות נשארות פתוחות.","ניסיון מסוכן","כישלון בלוח, בטיסה או בגמר הפרק הזה עולה חיים גלובליים אחד. אימונים והתקדמות שמורה בחינם. חיים חוזרים 12 שעות אחרי שנוצלו.","התחלה ▶","ביטול","הפרק נפתח בכרטיס הפניה 🎟","אין עדיין כרטיסי הפניה","הדרכה: לא מאבדים חיים ב־LIFE #1 הראשון","‎−1 חיים · נותרו {n} / 9","הפרק הבא בעוד {t}","בינתיים: משימות יומיות וצופן אות הירח","נגמרו החיים. החיים הבאים בעוד {t}","נפתח בעוד {t}","🎓 פרק הדרכה: טעויות ב־LIFE #1 הראשון לא עולות חיים. חיים: {n} / 9","⚠️ לוח, טיסה או גמר שנכשלו עולים 1 ❤️ · אימונים בחינם · חיים: {n} / 9","🌙 פרק {n} בעוד {t}",
"השלימו את LIFE #1 עד LIFE #9 — פרק חדש אחד ביום: אחרי שמסיימים פרק, הבא נפתח ב־00:00 UTC (חבר שהוזמן והשלים את LIFE #1 יכול לפתוח פרק אחד מוקדם). יש לכם 9 חיים גלובליים: כל לוח, טיסה או גמר פרק שנכשלו עולים חיים אחד (אימונים וההדרכה הראשונה של LIFE #1 בחינם). ב־0 חיים המשימות מושהות עד שחיים חוזרים — כל חיים שנוצלו חוזרים אחרי 12 שעות.",
"יש לכם עד 9 חיים גלובליים. כל לוח, טיסה או גמר פרק שנכשלו עולים חיים אחד; אימונים והמשחק הראשון ב־LIFE #1 בחינם. כל חיים שנוצלו חוזרים אוטומטית אחרי 12 שעות. ב־0 חיים המשימות מושהות עד שחיים חוזרים.",
"מתי נפתח הפרק הבא?",
"פרק חדש אחד ביום: אחרי שמסיימים פרק, הבא נפתח ב־00:00 UTC — אותו איפוס כמו המשימות היומיות. פרקים שהושלמו תמיד נשארים פתוחים. חבר שמצטרף דרך הקישור שלכם ומשלים את LIFE #1 נותן כרטיס אחד לדילוג על ההמתנה. הסיפור המלא נמשך כ־9 ימים.",
"פרק חדש אחד ביום: הבא נפתח ב־00:00 UTC. הסיפור המלא נמשך כ־9 ימים."]
L['ar']=['الفصل {n} / 09', 'الفصل التالي بعد', 'يُفتح فصل جديد كل يوم في 00:00 UTC. في هذه الأثناء أكمل المهام اليومية وفكّ شيفرة إشارة القمر وحافظ على سلسلتك.', '📡 المهام اليومية', '👥 ادعُ صديقًا — افتح الفصول مبكرًا', '🎟 افتح الآن · تذاكر الإحالة: {n}', 'فهمت', 'الأرواح', 'نفدت الأرواح. الروح التالية بعد', 'كل لوحة أو رحلة أو نهاية فاشلة تكلّف روحًا واحدة. تعود كل روح بعد 12 ساعة من إنفاقها. تبقى المهام اليومية متاحة.', 'محاولة محفوفة بالمخاطر', 'الفشل في لوحة أو رحلة أو نهاية هذا الفصل يكلّف روحًا عامة واحدة. التدريب والتقدّم المحفوظ مجانيان. تعود الأرواح بعد 12 ساعة من إنفاقها.', 'ابدأ ▶', 'إلغاء', 'فُتح الفصل بتذكرة إحالة 🎟', 'لا توجد تذاكر إحالة بعد', 'تدريب: لا تخسر أي روح في أول LIFE #1', '\u200f−1 روح · المتبقي {n} / 9', 'الفصل التالي بعد {t}', 'في هذه الأثناء: المهام اليومية وشيفرة إشارة القمر', 'نفدت الأرواح. الروح التالية بعد {t}', 'يُفتح بعد {t}', '🎓 فصل تدريبي: الأخطاء في أول LIFE #1 لا تكلّف أرواحًا. الأرواح: {n} / 9', '⚠️ اللوحة أو الرحلة أو النهاية الفاشلة تكلّف 1 ❤️ · التدريب مجاني · الأرواح: {n} / 9', '🌙 الفصل {n} بعد {t}', 'أكمل من LIFE #1 إلى LIFE #9 — فصل جديد واحد كل يوم: بعد إنهاء فصل يُفتح التالي في 00:00 UTC (الصديق المدعو الذي يُكمل LIFE #1 يمكنه فتح فصل واحد مبكرًا). لديك 9 أرواح عامة: كل لوحة أو رحلة أو نهاية فصل فاشلة تكلّف روحًا واحدة (التدريب وأول تدريب في LIFE #1 مجانيان). عند 0 أرواح تتوقف المهام حتى تعود روح — كل روح مُنفقة تعود بعد 12 ساعة.', 'لديك حتى 9 أرواح عامة. كل لوحة أو رحلة أو نهاية فصل فاشلة تكلّف روحًا واحدة؛ التدريب وأول لعب في LIFE #1 مجانيان. تعود كل روح مُنفقة تلقائيًا بعد 12 ساعة. عند 0 أرواح تتوقف المهام حتى تعود روح.', 'متى يُفتح الفصل التالي؟', 'فصل جديد واحد كل يوم: بعد إنهاء فصل يُفتح التالي في 00:00 UTC — بنفس توقيت إعادة ضبط المهام اليومية. تبقى الفصول المكتملة مفتوحة دائمًا. الصديق الذي ينضم عبر رابطك ويُكمل LIFE #1 يمنحك تذكرة واحدة لتخطي الانتظار. تستغرق القصة كاملة نحو 9 أيام.', 'فصل جديد واحد كل يوم: يُفتح التالي في 00:00 UTC. تستغرق القصة كاملة نحو 9 أيام.']
L['ko']=["챕터 {n} / 09","다음 챕터까지","매일 00:00 UTC에 새 챕터가 열립니다. 그동안 일일 미션을 완료하고 달 신호를 해독하며 연속 기록을 유지하세요.","📡 일일 미션","👥 친구 초대 — 챕터를 더 일찍 열기","🎟 지금 열기 · 추천 패스: {n}","확인","생명","생명이 없습니다. 다음 생명까지","보드, 비행, 피날레에 실패할 때마다 생명 1개가 소모됩니다. 생명은 소모 후 12시간 뒤에 회복됩니다. 일일 미션은 계속 열려 있습니다.","위험한 시도","이 챕터에서 보드, 비행 또는 챕터 피날레에 실패하면 공용 생명 1개가 소모됩니다. 훈련과 저장된 진행은 무료입니다. 생명은 소모 후 12시간 뒤에 회복됩니다.","시작 ▶","취소","추천 패스로 챕터가 열렸습니다 🎟","아직 추천 패스가 없습니다","튜토리얼: 첫 LIFE #1에서는 생명이 줄지 않습니다","생명 −1 · 남은 생명 {n} / 9","다음 챕터까지 {t}","그동안: 일일 미션과 달 신호 암호","생명이 없습니다. 다음 생명까지 {t}","{t} 후 열림","🎓 튜토리얼 챕터: 첫 LIFE #1의 실패는 생명을 소모하지 않습니다. 생명: {n} / 9","⚠️ 보드·비행·피날레 실패 시 1 ❤️ 소모 · 훈련은 무료 · 생명: {n} / 9","🌙 챕터 {n} · {t} 후",
"LIFE #1부터 LIFE #9까지 완료하세요 — 하루에 새 챕터 하나: 챕터를 끝내면 다음 챕터는 00:00 UTC에 열립니다(초대한 친구가 LIFE #1을 완료하면 챕터 하나를 먼저 열 수 있습니다). 공용 생명은 9개입니다: 보드, 비행, 챕터 피날레에 실패할 때마다 생명 1개가 소모됩니다(훈련과 첫 LIFE #1 튜토리얼은 무료). 생명이 0이면 생명이 회복될 때까지 미션이 일시 중지되며, 소모된 생명은 12시간 후 회복됩니다.",
"공용 생명은 최대 9개입니다. 보드, 비행, 챕터 피날레에 실패할 때마다 생명 1개가 소모되며, 훈련과 첫 LIFE #1 플레이는 무료입니다. 소모된 생명은 12시간 후 자동으로 회복됩니다. 생명이 0이면 회복될 때까지 미션이 일시 중지됩니다.",
"다음 챕터는 언제 열리나요?",
"하루에 새 챕터 하나: 챕터를 끝내면 다음 챕터는 00:00 UTC에 열립니다 — 일일 미션과 같은 초기화 시간입니다. 완료한 챕터는 언제나 열려 있습니다. 내 링크로 들어와 LIFE #1을 완료한 친구는 대기를 건너뛰는 패스 1개를 줍니다. 전체 이야기는 약 9일이 걸립니다.",
"하루에 새 챕터 하나: 다음 챕터는 00:00 UTC에 열립니다. 전체 이야기는 약 9일이 걸립니다."]
L['zh']=["第 {n} 章 / 09","下一章开放倒计时","每天 00:00 UTC 开放一个新章节。在此期间，完成每日任务、破译月球信号并保持连签。","📡 每日任务","👥 邀请好友——提前开启章节","🎟 立即开启 · 邀请通行证：{n}","知道了","生命","生命已用完。下一条生命倒计时","每次棋盘、飞行或终章失败都会消耗 1 条生命。每条生命在消耗 12 小时后恢复。每日任务仍然开放。","高风险尝试","在本章中棋盘、飞行或章节终局失败将消耗 1 条全局生命。训练和已保存的进度免费。生命在消耗 12 小时后恢复。","开始 ▶","取消","已使用邀请通行证开启章节 🎟","暂无邀请通行证","教程：首次 LIFE #1 不会损失生命","−1 生命 · 剩余 {n} / 9","下一章开放：{t}","在此期间：每日任务与月球信号密码","生命已用完。下一条生命：{t}","{t} 后开放","🎓 教程章节：首次 LIFE #1 中的失败不消耗生命。生命：{n} / 9","⚠️ 棋盘、飞行或终章失败消耗 1 ❤️ · 训练免费 · 生命：{n} / 9","🌙 第 {n} 章 · {t} 后",
"完成 LIFE #1 至 LIFE #9——每天开放一个新章节：完成一章后，下一章在 00:00 UTC 开放（受邀好友完成 LIFE #1 后可提前开启一章）。你有 9 条全局生命：每次棋盘、飞行或章节终局失败消耗 1 条生命（训练和首次 LIFE #1 教程免费）。生命为 0 时任务暂停，直到生命恢复——每条消耗的生命在 12 小时后恢复。",
"你最多有 9 条全局生命。每次棋盘、飞行或章节终局失败消耗 1 条生命；训练和首次 LIFE #1 免费。每条消耗的生命会在 12 小时后自动恢复。生命为 0 时任务暂停，直到生命恢复。",
"下一章什么时候开放？",
"每天一个新章节：完成一章后，下一章在 00:00 UTC 开放——与每日任务同一时间重置。已完成的章节始终开放。通过你的链接加入并完成 LIFE #1 的好友，可为你提供一次跳过等待的通行证。完整故事大约需要 9 天。",
"每天一个新章节：下一章在 00:00 UTC 开放。完整故事大约需要 9 天。"]
for c,v in L.items(): assert len(v)==len(K),(c,len(v),len(K))
out=['/* MOONKATTY chapter pacing + life-loss strings. Generated by tools/pacing-locales.py */','(function(root){','\'use strict\';','const L=root.MKTYLocales=root.MKTYLocales||{};','const D='+json.dumps({c:dict(zip(K,v)) for c,v in L.items()},ensure_ascii=False,indent=1)+';','for(const c of Object.keys(D)){L[c]=L[c]||{};L[c].strings=Object.assign(L[c].strings||{},D[c]);}','})(typeof globalThis!==\'undefined\'?globalThis:this);']
open('locales/pacing.js','w').write('\n'.join(out)+'\n')
print(len(K),len(L))
