import json
K=json.load(open('tools/creator/keys.json'))
T={}
T['ru']=["Добавьте #MOONKATTY в вставленное описание.","Одна заявка в неделю. Попробуйте после указанной даты.","Это видео уже отправляли.","Вставьте прямую ссылку на видео в TikTok, YouTube, X или Instagram.","Подтвердите, что это ваше видео.","После LIFE #9 баланс зафиксирован — новые награды закрыты.","Вход через Telegram истёк. Откройте игру заново.","Сервер недоступен. Попробуйте позже.",
"НА ПРОВЕРКЕ","ОДОБРЕНО","ОТКЛОНЕНО","Заявок пока нет.","НАГРАДЫ ДЛЯ АВТОРОВ","Снимите видео о MOONKATTY",
"Опубликуйте своё видео об игре в TikTok, YouTube, X или Instagram с хэштегом #MOONKATTY и пришлите ссылку. Каждое видео проверяет команда.",
"Одобренное видео","1 000+ просмотров","10 000+ просмотров",
"Снимите своё видео о MOONKATTY.","Добавьте #MOONKATTY в описание и опубликуйте.","Вставьте ссылку и описание ниже.",
"Ссылка на видео","Описание видео","Вставьте описание — в нём должен быть #MOONKATTY",
"Это моё видео, и я соблюдаю правила честной игры.",
"ОТПРАВКА…","ОТПРАВИТЬ НА ПРОВЕРКУ","Следующая заявка доступна",
"1 заявка в неделю. Каждое видео можно отправить только один раз.",
"Откройте игру в Telegram, чтобы отправить видео.","Мои заявки","Загрузка…",
"Очки авторов добавляются к вашим лунным очкам и учитываются в итоговом балансе. Пороги просмотров команда проверяет вручную; каждый порог начисляется один раз за видео. Накрученные просмотры, перезаливы и чужие видео отклоняются.",
"Открыть проверку (админ)","Отправлено! Видео на проверке.",
"Награды для авторов","Видео с #MOONKATTY приносит бонусные очки",
"Как получить награду за видео?",
"Опубликуйте своё видео об игре в TikTok, YouTube, X или Instagram с хэштегом #MOONKATTY и отправьте ссылку в разделе «Награды для авторов». Не чаще одного раза в неделю; каждое видео — один раз. Команда проверяет видео вручную; за одобренное видео и за пороги 1 000 и 10 000 просмотров начисляются лунные очки, которые учитываются в итоговом балансе.",
"Зарабатывайте лунные очки за подходящие сюжетные миссии, подтверждённые ежедневные задания, подтверждённую активность рефералов и одобренные авторские видео, пока путешествие 9 ЖИЗНЕЙ продолжается.",
"Ваше собственное видео о MOONKATTY с #MOONKATTY может принести лунные очки после ручной проверки: не более одной заявки в неделю, каждое видео — один раз, пороги 1 000 и 10 000 просмотров — по одному разу. Очки авторов учитываются в итоговом балансе, как и другие лунные очки. Накрученные просмотры, перезаливы и чужой контент отклоняются.",
"Проверка видео авторов","Одобряйте или отклоняйте видео игроков. Очки начисляет сервер.","← Назад в игру","Ваш Telegram ID",
"Откройте эту страницу из бота MOONKATTY в Telegram.","Доступ запрещён. Эта страница только для администраторов MOONKATTY.",
"Чтобы получить доступ, отправьте этот ID владельцу проекта — его нужно добавить в серверный секрет ADMIN_TG_IDS.",
"ОДОБРИТЬ","ОТКЛОНИТЬ","Отклонить это видео?","Начислить очки за это видео?","Сохранено.","Ошибка"]
T['uk']=["Додайте #MOONKATTY до вставленого опису.","Одна заявка на тиждень. Спробуйте після вказаної дати.","Це відео вже надсилали.","Вставте пряме посилання на відео в TikTok, YouTube, X або Instagram.","Підтвердьте, що це ваше відео.","Після LIFE #9 баланс зафіксовано — нові нагороди закрито.","Вхід через Telegram сплив. Відкрийте гру знову.","Сервер недоступний. Спробуйте пізніше.",
"НА ПЕРЕВІРЦІ","СХВАЛЕНО","ВІДХИЛЕНО","Заявок поки немає.","НАГОРОДИ ДЛЯ АВТОРІВ","Зніміть відео про MOONKATTY",
"Опублікуйте своє відео про гру в TikTok, YouTube, X або Instagram з хештегом #MOONKATTY і надішліть посилання. Кожне відео перевіряє команда.",
"Схвалене відео","1 000+ переглядів","10 000+ переглядів",
"Зніміть своє відео про MOONKATTY.","Додайте #MOONKATTY в опис і опублікуйте.","Вставте посилання та опис нижче.",
"Посилання на відео","Опис відео","Вставте опис — у ньому має бути #MOONKATTY",
"Це моє відео, і я дотримуюсь правил чесної гри.",
"НАДСИЛАННЯ…","НАДІСЛАТИ НА ПЕРЕВІРКУ","Наступна заявка доступна",
"1 заявка на тиждень. Кожне відео можна надіслати лише один раз.",
"Відкрийте гру в Telegram, щоб надіслати відео.","Мої заявки","Завантаження…",
"Очки авторів додаються до ваших місячних очок і враховуються в підсумковому балансі. Пороги переглядів команда перевіряє вручну; кожен поріг нараховується один раз за відео. Накручені перегляди, перезаливи та чужі відео відхиляються.",
"Відкрити перевірку (адмін)","Надіслано! Відео на перевірці.",
"Нагороди для авторів","Відео з #MOONKATTY приносить бонусні очки",
"Як отримати нагороду за відео?",
"Опублікуйте своє відео про гру в TikTok, YouTube, X або Instagram з #MOONKATTY і надішліть посилання в розділі «Нагороди для авторів». Не частіше одного разу на тиждень; кожне відео — один раз. Команда перевіряє відео вручну; за схвалене відео та пороги 1 000 і 10 000 переглядів нараховуються місячні очки, які враховуються в підсумковому балансі.",
"Заробляйте місячні очки за відповідні сюжетні місії, підтверджені щоденні завдання, підтверджену активність рефералів і схвалені авторські відео, поки триває подорож 9 ЖИТТІВ.",
"Ваше власне відео про MOONKATTY з #MOONKATTY може принести місячні очки після ручної перевірки: не більше однієї заявки на тиждень, кожне відео — один раз, пороги 1 000 і 10 000 переглядів — по одному разу. Очки авторів враховуються в підсумковому балансі, як і інші місячні очки. Накручені перегляди, перезаливи та чужий контент відхиляються.",
"Перевірка відео авторів","Схвалюйте або відхиляйте відео гравців. Очки нараховує сервер.","← Назад у гру","Ваш Telegram ID",
"Відкрийте цю сторінку з бота MOONKATTY у Telegram.","Доступ заборонено. Ця сторінка лише для адміністраторів MOONKATTY.",
"Щоб отримати доступ, надішліть цей ID власнику проєкту — його треба додати в серверний секрет ADMIN_TG_IDS.",
"СХВАЛИТИ","ВІДХИЛИТИ","Відхилити це відео?","Нарахувати очки за це відео?","Збережено.","Помилка"]
T['es']=["Añade #MOONKATTY a la descripción que pegaste.","Un envío por semana. Inténtalo después de la fecha indicada.","Este vídeo ya fue enviado.","Pega un enlace directo a un vídeo de TikTok, YouTube, X o Instagram.","Confirma que el vídeo es tuyo.","Tu saldo quedó fijado tras LIFE #9: no hay nuevas recompensas.","La sesión de Telegram caducó. Vuelve a abrir el juego.","Servidor no disponible. Inténtalo más tarde.",
"EN REVISIÓN","APROBADO","RECHAZADO","Aún no hay envíos.","RECOMPENSAS PARA CREADORES","Haz un vídeo sobre MOONKATTY",
"Publica tu propio vídeo sobre el juego en TikTok, YouTube, X o Instagram con el hashtag #MOONKATTY y envíanos el enlace. El equipo revisa cada vídeo.",
"Vídeo aprobado","1.000+ vistas","10.000+ vistas",
"Graba tu propio vídeo sobre MOONKATTY.","Añade #MOONKATTY a la descripción y publícalo.","Pega abajo el enlace y la descripción.",
"Enlace del vídeo","Descripción del vídeo","Pega la descripción: debe incluir #MOONKATTY",
"Este vídeo es mío y respeto las reglas de juego limpio.",
"ENVIANDO…","ENVIAR A REVISIÓN","Próximo envío disponible",
"1 envío por semana. Cada vídeo solo puede enviarse una vez.",
"Abre el juego en Telegram para enviar un vídeo.","Mis envíos","Cargando…",
"Los puntos de creador se suman a tus Moon Points y cuentan para tu saldo final. El equipo comprueba manualmente los niveles de vistas; cada nivel se otorga una vez por vídeo. Se rechazan vistas compradas, resubidas y vídeos ajenos.",
"Abrir revisión (admin)","¡Enviado! Tu vídeo está en revisión.",
"Recompensas para creadores","Tu vídeo con #MOONKATTY gana puntos extra",
"¿Cómo funcionan las recompensas para creadores?",
"Publica tu propio vídeo sobre el juego en TikTok, YouTube, X o Instagram con #MOONKATTY y envía el enlace en Recompensas para creadores. Máximo un envío por semana; cada vídeo una vez. El equipo revisa los vídeos manualmente; los vídeos aprobados y los niveles de 1.000 y 10.000 vistas otorgan Moon Points que cuentan para tu saldo final.",
"Gana Moon Points con misiones de historia elegibles, misiones diarias verificadas, actividad de referidos verificada y vídeos de creador aprobados mientras tu viaje de 9 VIDAS siga activo.",
"Tu propio vídeo sobre MOONKATTY con #MOONKATTY puede ganar Moon Points tras una revisión manual: máximo un envío por semana, cada vídeo una vez, niveles de 1.000 y 10.000 vistas una vez cada uno. Los puntos de creador cuentan para tu saldo final como otros Moon Points. Se rechazan vistas compradas, resubidas y contenido ajeno.",
"Revisión de creadores","Aprueba o rechaza vídeos de jugadores. Los puntos los otorga el servidor.","← Volver al juego","Tu ID de Telegram",
"Abre esta página desde el bot de MOONKATTY en Telegram.","Acceso denegado. Esta página es solo para administradores de MOONKATTY.",
"Para obtener acceso, envía este ID al propietario del proyecto; debe añadirse al secreto del servidor ADMIN_TG_IDS.",
"APROBAR","RECHAZAR","¿Rechazar este vídeo?","¿Otorgar puntos por este vídeo?","Guardado.","Error"]
T['pt']=["Adicione #MOONKATTY à legenda colada.","Um envio por semana. Tente após a data indicada.","Este vídeo já foi enviado.","Cole um link direto para um vídeo do TikTok, YouTube, X ou Instagram.","Confirme que o vídeo é seu.","Seu saldo foi bloqueado após a LIFE #9 — novas recompensas encerradas.","A sessão do Telegram expirou. Reabra o jogo.","Servidor indisponível. Tente mais tarde.",
"EM ANÁLISE","APROVADO","REJEITADO","Nenhum envio ainda.","RECOMPENSAS PARA CRIADORES","Faça um vídeo sobre MOONKATTY",
"Publique seu próprio vídeo sobre o jogo no TikTok, YouTube, X ou Instagram com a hashtag #MOONKATTY e envie o link. A equipe analisa cada vídeo.",
"Vídeo aprovado","1.000+ visualizações","10.000+ visualizações",
"Grave seu próprio vídeo sobre MOONKATTY.","Adicione #MOONKATTY à legenda e publique.","Cole o link e a legenda abaixo.",
"Link do vídeo","Legenda do vídeo","Cole a legenda — ela deve conter #MOONKATTY",
"Este vídeo é meu e sigo as regras de jogo limpo.",
"ENVIANDO…","ENVIAR PARA ANÁLISE","Próximo envio disponível",
"1 envio por semana. Cada vídeo só pode ser enviado uma vez.",
"Abra o jogo no Telegram para enviar um vídeo.","Meus envios","Carregando…",
"Os pontos de criador somam-se aos seus Moon Points e contam para o saldo final. A equipe verifica manualmente os níveis de visualizações; cada nível é concedido uma vez por vídeo. Visualizações compradas, reenvios e vídeos de terceiros são rejeitados.",
"Abrir análise (admin)","Enviado! Seu vídeo está em análise.",
"Recompensas para criadores","Seu vídeo com #MOONKATTY rende pontos bônus",
"Como funcionam as recompensas para criadores?",
"Publique seu próprio vídeo sobre o jogo no TikTok, YouTube, X ou Instagram com #MOONKATTY e envie o link em Recompensas para criadores. No máximo um envio por semana; cada vídeo uma vez. A equipe analisa os vídeos manualmente; vídeos aprovados e os níveis de 1.000 e 10.000 visualizações rendem Moon Points que contam para o saldo final.",
"Ganhe Moon Points com missões de história elegíveis, missões diárias verificadas, atividade de indicações verificada e vídeos de criador aprovados enquanto sua jornada de 9 VIDAS estiver ativa.",
"Seu próprio vídeo sobre MOONKATTY com #MOONKATTY pode render Moon Points após análise manual: no máximo um envio por semana, cada vídeo uma vez, níveis de 1.000 e 10.000 visualizações uma vez cada. Pontos de criador contam para o saldo final como outros Moon Points. Visualizações compradas, reenvios e conteúdo de terceiros são rejeitados.",
"Análise de criadores","Aprove ou rejeite vídeos dos jogadores. Os pontos são concedidos pelo servidor.","← Voltar ao jogo","Seu ID do Telegram",
"Abra esta página pelo bot MOONKATTY no Telegram.","Acesso negado. Esta página é só para administradores do MOONKATTY.",
"Para obter acesso, envie este ID ao dono do projeto; ele deve ser adicionado ao segredo do servidor ADMIN_TG_IDS.",
"APROVAR","REJEITAR","Rejeitar este vídeo?","Conceder pontos por este vídeo?","Salvo.","Erro"]
T['de']=["Füge #MOONKATTY zur eingefügten Beschreibung hinzu.","Eine Einreichung pro Woche. Versuche es nach dem angezeigten Datum.","Dieses Video wurde bereits eingereicht.","Füge einen direkten Link zu einem TikTok-, YouTube-, X- oder Instagram-Video ein.","Bestätige, dass dies dein Video ist.","Dein Guthaben ist nach LIFE #9 gesperrt – keine neuen Belohnungen.","Telegram-Anmeldung abgelaufen. Öffne das Spiel erneut.","Server nicht erreichbar. Versuche es später.",
"IN PRÜFUNG","GENEHMIGT","ABGELEHNT","Noch keine Einreichungen.","CREATOR-BELOHNUNGEN","Mach ein Video über MOONKATTY",
"Veröffentliche dein eigenes Video über das Spiel auf TikTok, YouTube, X oder Instagram mit dem Hashtag #MOONKATTY und schick uns den Link. Jedes Video wird vom Team geprüft.",
"Genehmigtes Video","1.000+ Aufrufe","10.000+ Aufrufe",
"Nimm dein eigenes Video über MOONKATTY auf.","Füge #MOONKATTY in die Beschreibung ein und veröffentliche es.","Füge unten Link und Beschreibung ein.",
"Video-Link","Videobeschreibung","Beschreibung einfügen – sie muss #MOONKATTY enthalten",
"Das ist mein eigenes Video und ich halte mich an die Fair-Play-Regeln.",
"WIRD GESENDET…","ZUR PRÜFUNG EINREICHEN","Nächste Einreichung möglich",
"1 Einreichung pro Woche. Jedes Video kann nur einmal eingereicht werden.",
"Öffne das Spiel in Telegram, um ein Video einzureichen.","Meine Einreichungen","Wird geladen…",
"Creator-Punkte werden deinen Moon Points gutgeschrieben und zählen zu deinem Endguthaben. Aufrufstufen prüft das Team manuell; jede Stufe wird pro Video einmal vergeben. Gekaufte Aufrufe, Reuploads und fremde Videos werden abgelehnt.",
"Admin-Prüfung öffnen","Gesendet! Dein Video wird geprüft.",
"Creator-Belohnungen","Dein Video mit #MOONKATTY bringt Bonuspunkte",
"Wie funktionieren Creator-Belohnungen?",
"Veröffentliche dein eigenes Video über das Spiel auf TikTok, YouTube, X oder Instagram mit #MOONKATTY und sende den Link unter Creator-Belohnungen. Höchstens eine Einreichung pro Woche; jedes Video einmal. Das Team prüft Videos manuell; genehmigte Videos sowie die Stufen 1.000 und 10.000 Aufrufe bringen Moon Points, die zu deinem Endguthaben zählen.",
"Verdiene Moon Points mit berechtigten Story-Missionen, verifizierten Daily Missions, verifizierter Empfehlungsaktivität und genehmigten Creator-Videos, solange deine 9-LEBEN-Reise aktiv ist.",
"Dein eigenes Video über MOONKATTY mit #MOONKATTY kann nach manueller Prüfung Moon Points bringen: höchstens eine Einreichung pro Woche, jedes Video einmal, Aufrufstufen 1.000 und 10.000 je einmal. Creator-Punkte zählen wie andere Moon Points zu deinem Endguthaben. Gekaufte Aufrufe, Reuploads und fremde Inhalte werden abgelehnt.",
"Creator-Prüfung","Genehmige oder lehne Spielervideos ab. Punkte vergibt der Server.","← Zurück zum Spiel","Deine Telegram-ID",
"Öffne diese Seite über den MOONKATTY-Bot in Telegram.","Zugriff verweigert. Diese Seite ist nur für MOONKATTY-Admins.",
"Für Zugriff sende diese ID an den Projektinhaber; sie muss zum Server-Secret ADMIN_TG_IDS hinzugefügt werden.",
"GENEHMIGEN","ABLEHNEN","Dieses Video ablehnen?","Punkte für dieses Video vergeben?","Gespeichert.","Fehler"]
T['fr']=["Ajoute #MOONKATTY à la description collée.","Une soumission par semaine. Réessaie après la date indiquée.","Cette vidéo a déjà été soumise.","Colle un lien direct vers une vidéo TikTok, YouTube, X ou Instagram.","Confirme que cette vidéo est la tienne.","Ton solde est verrouillé après LIFE #9 — plus de nouvelles récompenses.","Connexion Telegram expirée. Rouvre le jeu.","Serveur indisponible. Réessaie plus tard.",
"EN EXAMEN","APPROUVÉE","REFUSÉE","Aucune soumission pour l’instant.","RÉCOMPENSES CRÉATEURS","Fais une vidéo sur MOONKATTY",
"Publie ta propre vidéo sur le jeu sur TikTok, YouTube, X ou Instagram avec le hashtag #MOONKATTY, puis envoie-nous le lien. Chaque vidéo est examinée par l’équipe.",
"Vidéo approuvée","1 000+ vues","10 000+ vues",
"Tourne ta propre vidéo sur MOONKATTY.","Ajoute #MOONKATTY à la description et publie-la.","Colle le lien et la description ci-dessous.",
"Lien de la vidéo","Description de la vidéo","Colle la description — elle doit contenir #MOONKATTY",
"C’est ma propre vidéo et je respecte les règles de fair-play.",
"ENVOI…","SOUMETTRE À L’EXAMEN","Prochaine soumission possible",
"1 soumission par semaine. Chaque vidéo ne peut être soumise qu’une fois.",
"Ouvre le jeu dans Telegram pour soumettre une vidéo.","Mes soumissions","Chargement…",
"Les points créateur s’ajoutent à tes Moon Points et comptent dans ton solde final. Les paliers de vues sont vérifiés manuellement par l’équipe ; chaque palier est accordé une fois par vidéo. Les vues achetées, les reuploads et les vidéos d’autrui sont refusés.",
"Ouvrir l’examen (admin)","Envoyé ! Ta vidéo est en examen.",
"Récompenses créateurs","Ta vidéo avec #MOONKATTY rapporte des points bonus",
"Comment fonctionnent les récompenses créateurs ?",
"Publie ta propre vidéo sur le jeu sur TikTok, YouTube, X ou Instagram avec #MOONKATTY et envoie le lien dans Récompenses créateurs. Une soumission par semaine au maximum ; chaque vidéo une fois. L’équipe examine les vidéos manuellement ; les vidéos approuvées et les paliers de 1 000 et 10 000 vues rapportent des Moon Points qui comptent dans ton solde final.",
"Gagne des Moon Points grâce aux missions d’histoire éligibles, aux missions quotidiennes vérifiées, à l’activité de parrainage vérifiée et aux vidéos créateur approuvées tant que ton voyage des 9 VIES est actif.",
"Ta propre vidéo sur MOONKATTY avec #MOONKATTY peut rapporter des Moon Points après examen manuel : une soumission par semaine au maximum, chaque vidéo une fois, paliers de 1 000 et 10 000 vues une fois chacun. Les points créateur comptent dans ton solde final comme les autres Moon Points. Les vues achetées, les reuploads et le contenu d’autrui sont refusés.",
"Examen des créateurs","Approuve ou refuse les vidéos des joueurs. Les points sont attribués par le serveur.","← Retour au jeu","Ton ID Telegram",
"Ouvre cette page depuis le bot MOONKATTY dans Telegram.","Accès refusé. Cette page est réservée aux admins MOONKATTY.",
"Pour obtenir l’accès, envoie cet ID au propriétaire du projet ; il doit être ajouté au secret serveur ADMIN_TG_IDS.",
"APPROUVER","REFUSER","Refuser cette vidéo ?","Attribuer des points pour cette vidéo ?","Enregistré.","Erreur"]
T['it']=["Aggiungi #MOONKATTY alla descrizione incollata.","Un invio a settimana. Riprova dopo la data indicata.","Questo video è già stato inviato.","Incolla un link diretto a un video TikTok, YouTube, X o Instagram.","Conferma che il video è tuo.","Il tuo saldo è bloccato dopo LIFE #9: nuove ricompense chiuse.","Accesso Telegram scaduto. Riapri il gioco.","Server non disponibile. Riprova più tardi.",
"IN REVISIONE","APPROVATO","RIFIUTATO","Ancora nessun invio.","RICOMPENSE CREATOR","Fai un video su MOONKATTY",
"Pubblica un tuo video sul gioco su TikTok, YouTube, X o Instagram con l’hashtag #MOONKATTY e inviaci il link. Ogni video viene esaminato dal team.",
"Video approvato","1.000+ visualizzazioni","10.000+ visualizzazioni",
"Registra un tuo video su MOONKATTY.","Aggiungi #MOONKATTY alla descrizione e pubblicalo.","Incolla qui sotto link e descrizione.",
"Link del video","Descrizione del video","Incolla la descrizione: deve contenere #MOONKATTY",
"Questo video è mio e rispetto le regole del fair play.",
"INVIO…","INVIA PER LA REVISIONE","Prossimo invio disponibile",
"1 invio a settimana. Ogni video può essere inviato una sola volta.",
"Apri il gioco in Telegram per inviare un video.","I miei invii","Caricamento…",
"I punti creator si sommano ai tuoi Moon Points e contano per il saldo finale. Le soglie di visualizzazioni sono verificate manualmente dal team; ogni soglia viene assegnata una volta per video. Visualizzazioni comprate, ricaricamenti e video altrui vengono rifiutati.",
"Apri revisione (admin)","Inviato! Il tuo video è in revisione.",
"Ricompense creator","Il tuo video con #MOONKATTY vale punti bonus",
"Come funzionano le ricompense creator?",
"Pubblica un tuo video sul gioco su TikTok, YouTube, X o Instagram con #MOONKATTY e invia il link in Ricompense creator. Al massimo un invio a settimana; ogni video una volta. Il team esamina i video manualmente; i video approvati e le soglie di 1.000 e 10.000 visualizzazioni danno Moon Points che contano per il saldo finale.",
"Guadagna Moon Points con missioni della storia idonee, missioni giornaliere verificate, attività di referral verificata e video creator approvati finché il tuo viaggio delle 9 VITE è attivo.",
"Il tuo video su MOONKATTY con #MOONKATTY può far guadagnare Moon Points dopo revisione manuale: al massimo un invio a settimana, ogni video una volta, soglie di 1.000 e 10.000 visualizzazioni una volta ciascuna. I punti creator contano per il saldo finale come gli altri Moon Points. Visualizzazioni comprate, ricaricamenti e contenuti altrui vengono rifiutati.",
"Revisione creator","Approva o rifiuta i video dei giocatori. I punti li assegna il server.","← Torna al gioco","Il tuo ID Telegram",
"Apri questa pagina dal bot MOONKATTY in Telegram.","Accesso negato. Questa pagina è solo per gli admin MOONKATTY.",
"Per ottenere l’accesso invia questo ID al proprietario del progetto; va aggiunto al secret del server ADMIN_TG_IDS.",
"APPROVA","RIFIUTA","Rifiutare questo video?","Assegnare punti per questo video?","Salvato.","Errore"]
T['tr']=["Yapıştırdığın açıklamaya #MOONKATTY ekle.","Haftada bir gönderim. Gösterilen tarihten sonra tekrar dene.","Bu video zaten gönderildi.","TikTok, YouTube, X veya Instagram videosunun doğrudan bağlantısını yapıştır.","Bu videonun sana ait olduğunu onayla.","LIFE #9 sonrası bakiyen kilitlendi — yeni ödül yok.","Telegram oturumu sona erdi. Oyunu yeniden aç.","Sunucuya ulaşılamıyor. Daha sonra dene.",
"İNCELEMEDE","ONAYLANDI","REDDEDİLDİ","Henüz gönderim yok.","İÇERİK ÜRETİCİ ÖDÜLLERİ","MOONKATTY hakkında video çek",
"Oyun hakkındaki kendi videonu #MOONKATTY etiketiyle TikTok, YouTube, X veya Instagram’da paylaş ve bağlantıyı bize gönder. Her video ekip tarafından incelenir.",
"Onaylanan video","1.000+ izlenme","10.000+ izlenme",
"MOONKATTY hakkında kendi videonu çek.","Açıklamaya #MOONKATTY ekle ve yayınla.","Bağlantıyı ve açıklamayı aşağıya yapıştır.",
"Video bağlantısı","Video açıklaması","Açıklamayı yapıştır — #MOONKATTY içermeli",
"Bu benim videom ve adil oyun kurallarına uyuyorum.",
"GÖNDERİLİYOR…","İNCELEMEYE GÖNDER","Sonraki gönderim",
"Haftada 1 gönderim. Her video yalnızca bir kez gönderilebilir.",
"Video göndermek için oyunu Telegram’da aç.","Gönderimlerim","Yükleniyor…",
"Üretici puanları Moon Points’ine eklenir ve son bakiyende sayılır. İzlenme seviyeleri ekip tarafından elle kontrol edilir; her seviye video başına bir kez verilir. Satın alınmış izlenmeler, yeniden yüklemeler ve başkalarının videoları reddedilir.",
"Yönetici incelemesini aç","Gönderildi! Videon incelemede.",
"İçerik üretici ödülleri","#MOONKATTY etiketli videon bonus puan kazandırır",
"İçerik üretici ödülleri nasıl çalışır?",
"Oyun hakkındaki kendi videonu #MOONKATTY ile TikTok, YouTube, X veya Instagram’da paylaş ve bağlantıyı İçerik üretici ödülleri bölümünden gönder. Haftada en fazla bir gönderim; her video bir kez. Ekip videoları elle inceler; onaylanan videolar ile 1.000 ve 10.000 izlenme seviyeleri son bakiyende sayılan Moon Points kazandırır.",
"9 CAN yolculuğun sürerken uygun hikâye görevleri, doğrulanmış günlük görevler, doğrulanmış davet etkinliği ve onaylanan üretici videolarıyla Moon Points kazan.",
"MOONKATTY hakkındaki #MOONKATTY etiketli kendi videon, elle inceleme sonrası Moon Points kazandırabilir: haftada en fazla bir gönderim, her video bir kez, 1.000 ve 10.000 izlenme seviyeleri birer kez. Üretici puanları diğer Moon Points gibi son bakiyende sayılır. Satın alınmış izlenmeler, yeniden yüklemeler ve başkalarının içerikleri reddedilir.",
"Üretici incelemesi","Oyuncu videolarını onayla veya reddet. Puanları sunucu verir.","← Oyuna dön","Telegram kimliğin",
"Bu sayfayı Telegram’daki MOONKATTY botundan aç.","Erişim reddedildi. Bu sayfa yalnızca MOONKATTY yöneticileri içindir.",
"Erişim için bu kimliği proje sahibine gönder; ADMIN_TG_IDS sunucu sırrına eklenmesi gerekir.",
"ONAYLA","REDDET","Bu video reddedilsin mi?","Bu video için puan verilsin mi?","Kaydedildi.","Hata"]
T['he']=["הוסיפו ‎#MOONKATTY לתיאור שהדבקתם.","הגשה אחת בשבוע. נסו שוב אחרי התאריך המוצג.","הסרטון הזה כבר הוגש.","הדביקו קישור ישיר לסרטון ב-TikTok, ‏YouTube, ‏X או Instagram.","אשרו שהסרטון שלכם.","היתרה ננעלה אחרי LIFE #9 — אין תגמולים חדשים.","החיבור לטלגרם פג. פתחו את המשחק מחדש.","השרת אינו זמין. נסו מאוחר יותר.",
"בבדיקה","אושר","נדחה","אין הגשות עדיין.","תגמולי יוצרים","צרו סרטון על MOONKATTY",
"פרסמו סרטון משלכם על המשחק ב-TikTok, ‏YouTube, ‏X או Instagram עם ההאשטג ‎#MOONKATTY ושלחו לנו את הקישור. הצוות בודק כל סרטון.",
"סרטון שאושר","‎1,000+ צפיות","‎10,000+ צפיות",
"צלמו סרטון משלכם על MOONKATTY.","הוסיפו ‎#MOONKATTY לתיאור ופרסמו.","הדביקו את הקישור והתיאור למטה.",
"קישור לסרטון","תיאור הסרטון","הדביקו את התיאור — הוא חייב לכלול ‎#MOONKATTY",
"זה הסרטון שלי ואני מקפיד/ה על כללי משחק הוגן.",
"שולח…","שליחה לבדיקה","ההגשה הבאה זמינה",
"הגשה אחת בשבוע. כל סרטון ניתן להגיש פעם אחת בלבד.",
"פתחו את המשחק בטלגרם כדי להגיש סרטון.","ההגשות שלי","טוען…",
"נקודות יוצרים מתווספות לנקודות הירח שלכם ונספרות ביתרה הסופית. רמות הצפיות נבדקות ידנית על ידי הצוות; כל רמה מוענקת פעם אחת לכל סרטון. צפיות קנויות, העלאות חוזרות וסרטונים של אחרים נדחים.",
"פתיחת בדיקת מנהל","נשלח! הסרטון בבדיקה.",
"תגמולי יוצרים","סרטון עם ‎#MOONKATTY מעניק נקודות בונוס",
"איך עובדים תגמולי יוצרים?",
"פרסמו סרטון משלכם על המשחק ב-TikTok, ‏YouTube, ‏X או Instagram עם ‎#MOONKATTY ושלחו את הקישור בתגמולי יוצרים. עד הגשה אחת בשבוע; כל סרטון פעם אחת. הצוות בודק סרטונים ידנית; סרטונים שאושרו ורמות 1,000 ו-10,000 צפיות מעניקים נקודות ירח שנספרות ביתרה הסופית.",
"צברו נקודות ירח ממשימות סיפור מתאימות, משימות יומיות מאומתות, פעילות הפניות מאומתת וסרטוני יוצרים שאושרו כל עוד מסע 9 החיים שלכם פעיל.",
"סרטון משלכם על MOONKATTY עם ‎#MOONKATTY יכול להעניק נקודות ירח לאחר בדיקה ידנית: עד הגשה אחת בשבוע, כל סרטון פעם אחת, רמות 1,000 ו-10,000 צפיות פעם אחת כל אחת. נקודות יוצרים נספרות ביתרה הסופית כמו נקודות ירח אחרות. צפיות קנויות, העלאות חוזרות ותוכן של אחרים נדחים.",
"בדיקת יוצרים","אשרו או דחו סרטוני שחקנים. הנקודות מוענקות על ידי השרת.","→ חזרה למשחק","מזהה הטלגרם שלך",
"פתחו דף זה דרך הבוט של MOONKATTY בטלגרם.","הגישה נדחתה. דף זה מיועד למנהלי MOONKATTY בלבד.",
"כדי לקבל גישה, שלחו מזהה זה לבעל הפרויקט; יש להוסיף אותו לסוד השרת ADMIN_TG_IDS.",
"אישור","דחייה","לדחות את הסרטון?","להעניק נקודות לסרטון?","נשמר.","שגיאה"]
T['ko']=["붙여넣은 설명에 #MOONKATTY를 추가하세요.","주 1회 제출할 수 있습니다. 표시된 날짜 이후에 다시 시도하세요.","이미 제출된 영상입니다.","TikTok, YouTube, X 또는 Instagram 영상의 직접 링크를 붙여넣으세요.","본인 영상임을 확인해 주세요.","LIFE #9 이후 잔액이 고정되어 새 보상이 종료되었습니다.","텔레그램 로그인이 만료되었습니다. 게임을 다시 여세요.","서버를 사용할 수 없습니다. 나중에 다시 시도하세요.",
"검토 중","승인됨","거절됨","아직 제출한 영상이 없습니다.","크리에이터 보상","MOONKATTY 영상을 만들어 보세요",
"게임에 관한 본인 영상을 #MOONKATTY 해시태그와 함께 TikTok, YouTube, X 또는 Instagram에 올리고 링크를 보내 주세요. 모든 영상은 팀이 검토합니다.",
"승인된 영상","조회수 1,000+","조회수 10,000+",
"MOONKATTY에 관한 본인 영상을 촬영하세요.","설명에 #MOONKATTY를 넣고 게시하세요.","아래에 링크와 설명을 붙여넣으세요.",
"영상 링크","영상 설명","설명을 붙여넣으세요 — #MOONKATTY가 포함되어야 합니다",
"본인이 만든 영상이며 공정 플레이 규칙을 지킵니다.",
"전송 중…","검토 요청","다음 제출 가능 시각",
"주 1회 제출. 각 영상은 한 번만 제출할 수 있습니다.",
"영상을 제출하려면 텔레그램에서 게임을 여세요.","내 제출","불러오는 중…",
"크리에이터 포인트는 문 포인트에 더해지며 최종 잔액에 포함됩니다. 조회수 단계는 팀이 직접 확인하며, 각 단계는 영상당 한 번만 지급됩니다. 구매한 조회수, 재업로드, 타인의 영상은 거절됩니다.",
"관리자 검토 열기","전송 완료! 영상이 검토 중입니다.",
"크리에이터 보상","#MOONKATTY 영상으로 보너스 포인트 획득",
"크리에이터 보상은 어떻게 작동하나요?",
"게임에 관한 본인 영상을 #MOONKATTY와 함께 TikTok, YouTube, X 또는 Instagram에 올리고 크리에이터 보상에서 링크를 보내세요. 주 최대 1회, 영상당 1회 제출할 수 있습니다. 팀이 직접 검토하며, 승인된 영상과 조회수 1,000·10,000 단계에 최종 잔액에 포함되는 문 포인트가 지급됩니다.",
"9 LIVES 여정이 진행되는 동안 해당 스토리 미션, 인증된 일일 미션, 인증된 추천 활동, 승인된 크리에이터 영상으로 문 포인트를 획득하세요.",
"#MOONKATTY를 단 MOONKATTY 본인 영상은 수동 검토 후 문 포인트를 받을 수 있습니다: 주 최대 1회 제출, 영상당 1회, 조회수 1,000·10,000 단계는 각각 1회. 크리에이터 포인트는 다른 문 포인트처럼 최종 잔액에 포함됩니다. 구매한 조회수, 재업로드, 타인의 콘텐츠는 거절됩니다.",
"크리에이터 검토","플레이어 영상을 승인하거나 거절하세요. 포인트는 서버가 지급합니다.","← 게임으로 돌아가기","내 텔레그램 ID",
"텔레그램의 MOONKATTY 봇에서 이 페이지를 여세요.","접근이 거부되었습니다. 이 페이지는 MOONKATTY 관리자 전용입니다.",
"접근 권한을 받으려면 이 ID를 프로젝트 소유자에게 보내세요. 서버 시크릿 ADMIN_TG_IDS에 추가되어야 합니다.",
"승인","거절","이 영상을 거절할까요?","이 영상에 포인트를 지급할까요?","저장되었습니다.","오류"]
T['zh']=["请在粘贴的说明中加入 #MOONKATTY。","每周只能提交一次。请在显示的日期之后再试。","该视频已被提交过。","请粘贴 TikTok、YouTube、X 或 Instagram 视频的直接链接。","请确认这是你自己的视频。","完成 LIFE #9 后余额已锁定——不再发放新奖励。","Telegram 登录已过期。请重新打开游戏。","服务器不可用，请稍后再试。",
"审核中","已通过","已拒绝","暂无提交。","创作者奖励","为 MOONKATTY 制作视频",
"在 TikTok、YouTube、X 或 Instagram 发布你自己关于游戏的视频并带上话题 #MOONKATTY，然后把链接发给我们。每个视频都由团队审核。",
"视频通过","1,000+ 播放","10,000+ 播放",
"录制你自己关于 MOONKATTY 的视频。","在说明中加入 #MOONKATTY 并发布。","在下方粘贴链接和说明。",
"视频链接","视频说明","粘贴说明——必须包含 #MOONKATTY",
"这是我自己的视频，并且我遵守公平游戏规则。",
"发送中…","提交审核","下次可提交时间",
"每周 1 次提交。每个视频只能提交一次。",
"请在 Telegram 中打开游戏以提交视频。","我的提交","加载中…",
"创作者积分会计入你的月球点数，并计入最终余额。播放量档位由团队人工核查；每个档位每个视频仅发放一次。购买的播放量、搬运和他人视频将被拒绝。",
"打开管理审核","已提交！视频正在审核。",
"创作者奖励","带 #MOONKATTY 的视频可获得额外积分",
"创作者奖励如何运作？",
"在 TikTok、YouTube、X 或 Instagram 发布你自己关于游戏的视频并带上 #MOONKATTY，然后在“创作者奖励”中提交链接。每周最多一次；每个视频一次。团队人工审核；通过的视频以及 1,000 和 10,000 播放档位可获得计入最终余额的月球点数。",
"在你的 9 LIVES 旅程进行期间，通过符合条件的剧情任务、已验证的每日任务、已验证的推荐活动和已通过的创作者视频获得月球点数。",
"你自己带 #MOONKATTY 的 MOONKATTY 视频经人工审核后可获得月球点数：每周最多提交一次，每个视频一次，1,000 和 10,000 播放档位各一次。创作者积分与其他月球点数一样计入最终余额。购买的播放量、搬运和他人内容将被拒绝。",
"创作者审核","批准或拒绝玩家视频。积分由服务器发放。","← 返回游戏","你的 Telegram ID",
"请从 Telegram 中的 MOONKATTY 机器人打开此页面。","拒绝访问。此页面仅供 MOONKATTY 管理员使用。",
"如需访问，请将此 ID 发送给项目所有者；需将其加入服务器密钥 ADMIN_TG_IDS。",
"通过","拒绝","拒绝这个视频？","为这个视频发放积分？","已保存。","错误"]
T['ar']=["أضف ‎#MOONKATTY إلى الوصف الذي لصقته.", "مشاركة واحدة في الأسبوع. حاول مجددًا بعد التاريخ المبيّن.", "تم إرسال هذا الفيديو من قبل.", "الصق رابطًا مباشرًا لفيديو على TikTok أو YouTube أو X أو Instagram.", "أكّد أن هذا الفيديو لك.", "رصيدك مُثبَّت بعد LIFE #9 — المكافآت الجديدة مغلقة.", "انتهت صلاحية تسجيل الدخول عبر Telegram. أعد فتح اللعبة.", "الخادم غير متاح. حاول لاحقًا.", "قيد المراجعة", "مقبول", "مرفوض", "لا مشاركات بعد.", "مكافآت صنّاع المحتوى", "اصنع فيديو عن MOONKATTY", "انشر فيديو خاصًا بك عن اللعبة على TikTok أو YouTube أو X أو Instagram مع الوسم ‎#MOONKATTY، ثم أرسل لنا الرابط. يراجع الفريق كل فيديو.", "فيديو مقبول", "أكثر من 1,000 مشاهدة", "أكثر من 10,000 مشاهدة", "صوّر فيديو خاصًا بك عن MOONKATTY.", "أضف ‎#MOONKATTY إلى الوصف وانشره.", "الصق الرابط والوصف أدناه.", "رابط الفيديو", "وصف الفيديو", "الصق الوصف — يجب أن يتضمن ‎#MOONKATTY", "هذا الفيديو من صنعي وألتزم بقواعد اللعب النظيف.", "جارٍ الإرسال…", "أرسل للمراجعة", "المشاركة التالية متاحة", "مشاركة واحدة في الأسبوع. يمكن إرسال كل فيديو مرة واحدة فقط.", "افتح اللعبة داخل Telegram لإرسال فيديو.", "مشاركاتي", "جارٍ التحميل…", "تُضاف نقاط صنّاع المحتوى إلى نقاط القمر لديك وتُحتسب ضمن رصيدك النهائي. يفحص الفريق مستويات المشاهدات يدويًا؛ ويُمنح كل مستوى مرة واحدة لكل فيديو. تُرفض المشاهدات المشتراة وإعادة الرفع ومقاطع الآخرين.", "افتح مراجعة المشرف", "تم الإرسال! الفيديو قيد المراجعة.", "مكافآت صنّاع المحتوى", "الفيديو الخاص بك مع ‎#MOONKATTY يكسب نقاطًا إضافية", "كيف تعمل مكافآت صنّاع المحتوى؟", "انشر فيديو خاصًا بك عن اللعبة على TikTok أو YouTube أو X أو Instagram مع ‎#MOONKATTY وأرسل الرابط في «مكافآت صنّاع المحتوى». مشاركة واحدة كحد أقصى في الأسبوع؛ وكل فيديو مرة واحدة. يراجع الفريق الفيديوهات يدويًا؛ وتكسب الفيديوهات المقبولة ومستويا 1,000 و10,000 مشاهدة نقاطَ قمر تُحتسب ضمن رصيدك النهائي.", "اكسب نقاط القمر من مهام القصة المؤهلة، والمهام اليومية المُتحقَّق منها، ونشاط الإحالة المُتحقَّق منه، وفيديوهات صنّاع المحتوى المقبولة طوال رحلتك في الأرواح التسع.", "يمكن لفيديو خاص بك عن MOONKATTY مع ‎#MOONKATTY أن يكسب نقاط القمر بعد مراجعة يدوية: مشاركة واحدة كحد أقصى في الأسبوع، وكل فيديو مرة واحدة، ويُمنح مستويا 1,000 و10,000 مشاهدة مرة واحدة لكلٍّ منهما. تُحتسب نقاط صنّاع المحتوى ضمن رصيدك النهائي مثل نقاط القمر الأخرى. تُرفض المشاهدات المشتراة وإعادة الرفع ومحتوى الآخرين.", "مراجعة صنّاع المحتوى", "اقبل فيديوهات اللاعبين أو ارفضها. يمنح الخادم النقاط.", "→ العودة إلى اللعبة", "معرّفك في Telegram", "افتح هذه الصفحة من بوت MOONKATTY في Telegram.", "تم رفض الوصول. هذه الصفحة لمشرفي MOONKATTY فقط.", "للحصول على الوصول، أرسل هذا المعرّف إلى مالك المشروع؛ ويجب إضافته إلى سرّ الخادم ADMIN_TG_IDS.", "قبول", "رفض", "رفض هذا الفيديو؟", "منح نقاط لهذا الفيديو؟", "تم الحفظ.", "خطأ"]
out={}
for l,v in T.items():
  assert len(v)==len(K),(l,len(v))
  out[l]=dict(zip(K,v))
js="/* MOONKATTY creator rewards strings. Generated by tools/creator/tr.py */\n(function(root){\n'use strict';\nconst L=root.MKTYLocales=root.MKTYLocales||{};\nconst D="+json.dumps(out,ensure_ascii=False,indent=1)+";\nfor(const [code,strings] of Object.entries(D)){L[code]=L[code]||{};L[code].strings=Object.assign(L[code].strings||{},strings);}\n})(typeof window!=='undefined'?window:globalThis);\n"
open('locales/creator.js','w').write(js)
print('ok',len(T))
